
# WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.

# This file was generated from rosetta.idl
# using RTI Code Generator (rtiddsgen) version 4.3.0.
# The rtiddsgen tool is part of the RTI Connext DDS distribution.
# For more information, type 'rtiddsgen -help' at a command shell
# or consult the Code Generator User's Manual.

from dataclasses import field
from typing import Union, Sequence, Optional
import rti.idl as idl
from enum import IntEnum
import sys
import os


rosetta = idl.get_module("rosetta")

rosetta_MDC_ACCELERATION_INDEX = "MDC_ACCELERATION_INDEX"

rosetta.MDC_ACCELERATION_INDEX = rosetta_MDC_ACCELERATION_INDEX

rosetta_MDC_AREA_BODY_SURF_ACTUAL = "MDC_AREA_BODY_SURF_ACTUAL"

rosetta.MDC_AREA_BODY_SURF_ACTUAL = rosetta_MDC_AREA_BODY_SURF_ACTUAL

rosetta_MDC_ATTR_ALARM_INACTIVATION_STATE = "MDC_ATTR_ALARM_INACTIVATION_STATE"

rosetta.MDC_ATTR_ALARM_INACTIVATION_STATE = rosetta_MDC_ATTR_ALARM_INACTIVATION_STATE

rosetta_MDC_ATTR_ALARM_PRIORITY = "MDC_ATTR_ALARM_PRIORITY"

rosetta.MDC_ATTR_ALARM_PRIORITY = rosetta_MDC_ATTR_ALARM_PRIORITY

rosetta_MDC_ATTR_ALARM_STATE = "MDC_ATTR_ALARM_STATE"

rosetta.MDC_ATTR_ALARM_STATE = rosetta_MDC_ATTR_ALARM_STATE

rosetta_MDC_ATTR_ALERT_SOURCE = "MDC_ATTR_ALERT_SOURCE"

rosetta.MDC_ATTR_ALERT_SOURCE = rosetta_MDC_ATTR_ALERT_SOURCE

rosetta_MDC_ATTR_ALERT_TYPE = "MDC_ATTR_ALERT_TYPE"

rosetta.MDC_ATTR_ALERT_TYPE = rosetta_MDC_ATTR_ALERT_TYPE

rosetta_MDC_ATTR_AL_COND = "MDC_ATTR_AL_COND"

rosetta.MDC_ATTR_AL_COND = rosetta_MDC_ATTR_AL_COND

rosetta_MDC_ATTR_EVENT_PHASE = "MDC_ATTR_EVENT_PHASE"

rosetta.MDC_ATTR_EVENT_PHASE = rosetta_MDC_ATTR_EVENT_PHASE

rosetta_MDC_ATTR_PT_HEIGHT = "MDC_ATTR_PT_HEIGHT"

rosetta.MDC_ATTR_PT_HEIGHT = rosetta_MDC_ATTR_PT_HEIGHT

rosetta_MDC_ATTR_PT_WEIGHT = "MDC_ATTR_PT_WEIGHT"

rosetta.MDC_ATTR_PT_WEIGHT = rosetta_MDC_ATTR_PT_WEIGHT

rosetta_MDC_AWAY_AR = "MDC_AWAY_AR"

rosetta.MDC_AWAY_AR = rosetta_MDC_AWAY_AR

rosetta_MDC_AWAY_AR_EXP = "MDC_AWAY_AR_EXP"

rosetta.MDC_AWAY_AR_EXP = rosetta_MDC_AWAY_AR_EXP

rosetta_MDC_AWAY_AR_INSP = "MDC_AWAY_AR_INSP"

rosetta.MDC_AWAY_AR_INSP = rosetta_MDC_AWAY_AR_INSP

rosetta_MDC_AWAY_CO2 = "MDC_AWAY_CO2"

rosetta.MDC_AWAY_CO2 = rosetta_MDC_AWAY_CO2

rosetta_MDC_AWAY_CO2_ET = "MDC_AWAY_CO2_ET"

rosetta.MDC_AWAY_CO2_ET = rosetta_MDC_AWAY_CO2_ET

rosetta_MDC_AWAY_CO2_EXP = "MDC_AWAY_CO2_EXP"

rosetta.MDC_AWAY_CO2_EXP = rosetta_MDC_AWAY_CO2_EXP

rosetta_MDC_AWAY_CO2_INSP = "MDC_AWAY_CO2_INSP"

rosetta.MDC_AWAY_CO2_INSP = rosetta_MDC_AWAY_CO2_INSP

rosetta_MDC_AWAY_CO2_INSP_MIN = "MDC_AWAY_CO2_INSP_MIN"

rosetta.MDC_AWAY_CO2_INSP_MIN = rosetta_MDC_AWAY_CO2_INSP_MIN

rosetta_MDC_AWAY_DESFL = "MDC_AWAY_DESFL"

rosetta.MDC_AWAY_DESFL = rosetta_MDC_AWAY_DESFL

rosetta_MDC_AWAY_DESFL_EXP = "MDC_AWAY_DESFL_EXP"

rosetta.MDC_AWAY_DESFL_EXP = rosetta_MDC_AWAY_DESFL_EXP

rosetta_MDC_AWAY_DESFL_INSP = "MDC_AWAY_DESFL_INSP"

rosetta.MDC_AWAY_DESFL_INSP = rosetta_MDC_AWAY_DESFL_INSP

rosetta_MDC_AWAY_ENFL = "MDC_AWAY_ENFL"

rosetta.MDC_AWAY_ENFL = rosetta_MDC_AWAY_ENFL

rosetta_MDC_AWAY_ENFL_EXP = "MDC_AWAY_ENFL_EXP"

rosetta.MDC_AWAY_ENFL_EXP = rosetta_MDC_AWAY_ENFL_EXP

rosetta_MDC_AWAY_ENFL_INSP = "MDC_AWAY_ENFL_INSP"

rosetta.MDC_AWAY_ENFL_INSP = rosetta_MDC_AWAY_ENFL_INSP

rosetta_MDC_AWAY_HALOTH = "MDC_AWAY_HALOTH"

rosetta.MDC_AWAY_HALOTH = rosetta_MDC_AWAY_HALOTH

rosetta_MDC_AWAY_HALOTH_EXP = "MDC_AWAY_HALOTH_EXP"

rosetta.MDC_AWAY_HALOTH_EXP = rosetta_MDC_AWAY_HALOTH_EXP

rosetta_MDC_AWAY_HALOTH_INSP = "MDC_AWAY_HALOTH_INSP"

rosetta.MDC_AWAY_HALOTH_INSP = rosetta_MDC_AWAY_HALOTH_INSP

rosetta_MDC_AWAY_HE = "MDC_AWAY_HE"

rosetta.MDC_AWAY_HE = rosetta_MDC_AWAY_HE

rosetta_MDC_AWAY_HE_EXP = "MDC_AWAY_HE_EXP"

rosetta.MDC_AWAY_HE_EXP = rosetta_MDC_AWAY_HE_EXP

rosetta_MDC_AWAY_HE_INSP = "MDC_AWAY_HE_INSP"

rosetta.MDC_AWAY_HE_INSP = rosetta_MDC_AWAY_HE_INSP

rosetta_MDC_AWAY_ISOFL = "MDC_AWAY_ISOFL"

rosetta.MDC_AWAY_ISOFL = rosetta_MDC_AWAY_ISOFL

rosetta_MDC_AWAY_ISOFL_EXP = "MDC_AWAY_ISOFL_EXP"

rosetta.MDC_AWAY_ISOFL_EXP = rosetta_MDC_AWAY_ISOFL_EXP

rosetta_MDC_AWAY_ISOFL_INSP = "MDC_AWAY_ISOFL_INSP"

rosetta.MDC_AWAY_ISOFL_INSP = rosetta_MDC_AWAY_ISOFL_INSP

rosetta_MDC_AWAY_N2 = "MDC_AWAY_N2"

rosetta.MDC_AWAY_N2 = rosetta_MDC_AWAY_N2

rosetta_MDC_AWAY_N2O = "MDC_AWAY_N2O"

rosetta.MDC_AWAY_N2O = rosetta_MDC_AWAY_N2O

rosetta_MDC_AWAY_N2O_EXP = "MDC_AWAY_N2O_EXP"

rosetta.MDC_AWAY_N2O_EXP = rosetta_MDC_AWAY_N2O_EXP

rosetta_MDC_AWAY_N2O_INSP = "MDC_AWAY_N2O_INSP"

rosetta.MDC_AWAY_N2O_INSP = rosetta_MDC_AWAY_N2O_INSP

rosetta_MDC_AWAY_N2_EXP = "MDC_AWAY_N2_EXP"

rosetta.MDC_AWAY_N2_EXP = rosetta_MDC_AWAY_N2_EXP

rosetta_MDC_AWAY_N2_INSP = "MDC_AWAY_N2_INSP"

rosetta.MDC_AWAY_N2_INSP = rosetta_MDC_AWAY_N2_INSP

rosetta_MDC_AWAY_NO2 = "MDC_AWAY_NO2"

rosetta.MDC_AWAY_NO2 = rosetta_MDC_AWAY_NO2

rosetta_MDC_AWAY_NO2_EXP = "MDC_AWAY_NO2_EXP"

rosetta.MDC_AWAY_NO2_EXP = rosetta_MDC_AWAY_NO2_EXP

rosetta_MDC_AWAY_NO2_INSP = "MDC_AWAY_NO2_INSP"

rosetta.MDC_AWAY_NO2_INSP = rosetta_MDC_AWAY_NO2_INSP

rosetta_MDC_AWAY_O2 = "MDC_AWAY_O2"

rosetta.MDC_AWAY_O2 = rosetta_MDC_AWAY_O2

rosetta_MDC_AWAY_O2_EXP = "MDC_AWAY_O2_EXP"

rosetta.MDC_AWAY_O2_EXP = rosetta_MDC_AWAY_O2_EXP

rosetta_MDC_AWAY_O2_INSP = "MDC_AWAY_O2_INSP"

rosetta.MDC_AWAY_O2_INSP = rosetta_MDC_AWAY_O2_INSP

rosetta_MDC_AWAY_RESP_RATE = "MDC_AWAY_RESP_RATE"

rosetta.MDC_AWAY_RESP_RATE = rosetta_MDC_AWAY_RESP_RATE

rosetta_MDC_AWAY_SEVOFL = "MDC_AWAY_SEVOFL"

rosetta.MDC_AWAY_SEVOFL = rosetta_MDC_AWAY_SEVOFL

rosetta_MDC_AWAY_SEVOFL_EXP = "MDC_AWAY_SEVOFL_EXP"

rosetta.MDC_AWAY_SEVOFL_EXP = rosetta_MDC_AWAY_SEVOFL_EXP

rosetta_MDC_AWAY_SEVOFL_INSP = "MDC_AWAY_SEVOFL_INSP"

rosetta.MDC_AWAY_SEVOFL_INSP = rosetta_MDC_AWAY_SEVOFL_INSP

rosetta_MDC_BASE_EXCESS_BLD_ART = "MDC_BASE_EXCESS_BLD_ART"

rosetta.MDC_BASE_EXCESS_BLD_ART = rosetta_MDC_BASE_EXCESS_BLD_ART

rosetta_MDC_BASE_EXCESS_BLD_ART_INDEX = "MDC_BASE_EXCESS_BLD_ART_INDEX"

rosetta.MDC_BASE_EXCESS_BLD_ART_INDEX = rosetta_MDC_BASE_EXCESS_BLD_ART_INDEX

rosetta_MDC_BASE_EXCESS_FLUID_EXTRACELLULAR = "MDC_BASE_EXCESS_FLUID_EXTRACELLULAR"

rosetta.MDC_BASE_EXCESS_FLUID_EXTRACELLULAR = rosetta_MDC_BASE_EXCESS_FLUID_EXTRACELLULAR

rosetta_MDC_BLD_PERF_INDEX = "MDC_BLD_PERF_INDEX"

rosetta.MDC_BLD_PERF_INDEX = rosetta_MDC_BLD_PERF_INDEX

rosetta_MDC_BLD_PULS_RATE_INV = "MDC_BLD_PULS_RATE_INV"

rosetta.MDC_BLD_PULS_RATE_INV = rosetta_MDC_BLD_PULS_RATE_INV

rosetta_MDC_BLD_SHUNT_FRACTION = "MDC_BLD_SHUNT_FRACTION"

rosetta.MDC_BLD_SHUNT_FRACTION = rosetta_MDC_BLD_SHUNT_FRACTION

rosetta_MDC_CAPAC_VITAL = "MDC_CAPAC_VITAL"

rosetta.MDC_CAPAC_VITAL = rosetta_MDC_CAPAC_VITAL

rosetta_MDC_CIRCUM_HEAD = "MDC_CIRCUM_HEAD"

rosetta.MDC_CIRCUM_HEAD = rosetta_MDC_CIRCUM_HEAD

rosetta_MDC_CO2_RESP_RATE = "MDC_CO2_RESP_RATE"

rosetta.MDC_CO2_RESP_RATE = rosetta_MDC_CO2_RESP_RATE

rosetta_MDC_CO2_TCUT = "MDC_CO2_TCUT"

rosetta.MDC_CO2_TCUT = rosetta_MDC_CO2_TCUT

rosetta_MDC_COMM_STATUS = "MDC_COMM_STATUS"

rosetta.MDC_COMM_STATUS = rosetta_MDC_COMM_STATUS

rosetta_MDC_COMPL_LUNG = "MDC_COMPL_LUNG"

rosetta.MDC_COMPL_LUNG = rosetta_MDC_COMPL_LUNG

rosetta_MDC_COMPL_LUNG_DYN = "MDC_COMPL_LUNG_DYN"

rosetta.MDC_COMPL_LUNG_DYN = rosetta_MDC_COMPL_LUNG_DYN

rosetta_MDC_COMPL_LUNG_STATIC = "MDC_COMPL_LUNG_STATIC"

rosetta.MDC_COMPL_LUNG_STATIC = rosetta_MDC_COMPL_LUNG_STATIC

rosetta_MDC_CONC_AR = "MDC_CONC_AR"

rosetta.MDC_CONC_AR = rosetta_MDC_CONC_AR

rosetta_MDC_CONC_AR_BREATH = "MDC_CONC_AR_BREATH"

rosetta.MDC_CONC_AR_BREATH = rosetta_MDC_CONC_AR_BREATH

rosetta_MDC_CONC_AR_ET = "MDC_CONC_AR_ET"

rosetta.MDC_CONC_AR_ET = rosetta_MDC_CONC_AR_ET

rosetta_MDC_CONC_AR_EXP = "MDC_CONC_AR_EXP"

rosetta.MDC_CONC_AR_EXP = rosetta_MDC_CONC_AR_EXP

rosetta_MDC_CONC_AR_INSP = "MDC_CONC_AR_INSP"

rosetta.MDC_CONC_AR_INSP = rosetta_MDC_CONC_AR_INSP

rosetta_MDC_CONC_AWAY_AGENT = "MDC_CONC_AWAY_AGENT"

rosetta.MDC_CONC_AWAY_AGENT = rosetta_MDC_CONC_AWAY_AGENT

rosetta_MDC_CONC_AWAY_AGENT_ET = "MDC_CONC_AWAY_AGENT_ET"

rosetta.MDC_CONC_AWAY_AGENT_ET = rosetta_MDC_CONC_AWAY_AGENT_ET

rosetta_MDC_CONC_AWAY_AGENT_INSP = "MDC_CONC_AWAY_AGENT_INSP"

rosetta.MDC_CONC_AWAY_AGENT_INSP = rosetta_MDC_CONC_AWAY_AGENT_INSP

rosetta_MDC_CONC_AWAY_CO2 = "MDC_CONC_AWAY_CO2"

rosetta.MDC_CONC_AWAY_CO2 = rosetta_MDC_CONC_AWAY_CO2

rosetta_MDC_CONC_AWAY_CO2_ET = "MDC_CONC_AWAY_CO2_ET"

rosetta.MDC_CONC_AWAY_CO2_ET = rosetta_MDC_CONC_AWAY_CO2_ET

rosetta_MDC_CONC_AWAY_CO2_EXP = "MDC_CONC_AWAY_CO2_EXP"

rosetta.MDC_CONC_AWAY_CO2_EXP = rosetta_MDC_CONC_AWAY_CO2_EXP

rosetta_MDC_CONC_AWAY_CO2_INSP = "MDC_CONC_AWAY_CO2_INSP"

rosetta.MDC_CONC_AWAY_CO2_INSP = rosetta_MDC_CONC_AWAY_CO2_INSP

rosetta_MDC_CONC_AWAY_DESFL = "MDC_CONC_AWAY_DESFL"

rosetta.MDC_CONC_AWAY_DESFL = rosetta_MDC_CONC_AWAY_DESFL

rosetta_MDC_CONC_AWAY_DESFL_ET = "MDC_CONC_AWAY_DESFL_ET"

rosetta.MDC_CONC_AWAY_DESFL_ET = rosetta_MDC_CONC_AWAY_DESFL_ET

rosetta_MDC_CONC_AWAY_DESFL_INSP = "MDC_CONC_AWAY_DESFL_INSP"

rosetta.MDC_CONC_AWAY_DESFL_INSP = rosetta_MDC_CONC_AWAY_DESFL_INSP

rosetta_MDC_CONC_AWAY_ENFL = "MDC_CONC_AWAY_ENFL"

rosetta.MDC_CONC_AWAY_ENFL = rosetta_MDC_CONC_AWAY_ENFL

rosetta_MDC_CONC_AWAY_ENFL_ET = "MDC_CONC_AWAY_ENFL_ET"

rosetta.MDC_CONC_AWAY_ENFL_ET = rosetta_MDC_CONC_AWAY_ENFL_ET

rosetta_MDC_CONC_AWAY_ENFL_INSP = "MDC_CONC_AWAY_ENFL_INSP"

rosetta.MDC_CONC_AWAY_ENFL_INSP = rosetta_MDC_CONC_AWAY_ENFL_INSP

rosetta_MDC_CONC_AWAY_HALOTH = "MDC_CONC_AWAY_HALOTH"

rosetta.MDC_CONC_AWAY_HALOTH = rosetta_MDC_CONC_AWAY_HALOTH

rosetta_MDC_CONC_AWAY_HALOTH_ET = "MDC_CONC_AWAY_HALOTH_ET"

rosetta.MDC_CONC_AWAY_HALOTH_ET = rosetta_MDC_CONC_AWAY_HALOTH_ET

rosetta_MDC_CONC_AWAY_HALOTH_INSP = "MDC_CONC_AWAY_HALOTH_INSP"

rosetta.MDC_CONC_AWAY_HALOTH_INSP = rosetta_MDC_CONC_AWAY_HALOTH_INSP

rosetta_MDC_CONC_AWAY_ISOFL = "MDC_CONC_AWAY_ISOFL"

rosetta.MDC_CONC_AWAY_ISOFL = rosetta_MDC_CONC_AWAY_ISOFL

rosetta_MDC_CONC_AWAY_ISOFL_ET = "MDC_CONC_AWAY_ISOFL_ET"

rosetta.MDC_CONC_AWAY_ISOFL_ET = rosetta_MDC_CONC_AWAY_ISOFL_ET

rosetta_MDC_CONC_AWAY_ISOFL_INSP = "MDC_CONC_AWAY_ISOFL_INSP"

rosetta.MDC_CONC_AWAY_ISOFL_INSP = rosetta_MDC_CONC_AWAY_ISOFL_INSP

rosetta_MDC_CONC_AWAY_N2 = "MDC_CONC_AWAY_N2"

rosetta.MDC_CONC_AWAY_N2 = rosetta_MDC_CONC_AWAY_N2

rosetta_MDC_CONC_AWAY_N2O = "MDC_CONC_AWAY_N2O"

rosetta.MDC_CONC_AWAY_N2O = rosetta_MDC_CONC_AWAY_N2O

rosetta_MDC_CONC_AWAY_N2O_ET = "MDC_CONC_AWAY_N2O_ET"

rosetta.MDC_CONC_AWAY_N2O_ET = rosetta_MDC_CONC_AWAY_N2O_ET

rosetta_MDC_CONC_AWAY_N2O_INSP = "MDC_CONC_AWAY_N2O_INSP"

rosetta.MDC_CONC_AWAY_N2O_INSP = rosetta_MDC_CONC_AWAY_N2O_INSP

rosetta_MDC_CONC_AWAY_N2_ET = "MDC_CONC_AWAY_N2_ET"

rosetta.MDC_CONC_AWAY_N2_ET = rosetta_MDC_CONC_AWAY_N2_ET

rosetta_MDC_CONC_AWAY_N2_INSP = "MDC_CONC_AWAY_N2_INSP"

rosetta.MDC_CONC_AWAY_N2_INSP = rosetta_MDC_CONC_AWAY_N2_INSP

rosetta_MDC_CONC_AWAY_O2 = "MDC_CONC_AWAY_O2"

rosetta.MDC_CONC_AWAY_O2 = rosetta_MDC_CONC_AWAY_O2

rosetta_MDC_CONC_AWAY_O2_ET = "MDC_CONC_AWAY_O2_ET"

rosetta.MDC_CONC_AWAY_O2_ET = rosetta_MDC_CONC_AWAY_O2_ET

rosetta_MDC_CONC_AWAY_O2_INSP = "MDC_CONC_AWAY_O2_INSP"

rosetta.MDC_CONC_AWAY_O2_INSP = rosetta_MDC_CONC_AWAY_O2_INSP

rosetta_MDC_CONC_AWAY_SEVOFL = "MDC_CONC_AWAY_SEVOFL"

rosetta.MDC_CONC_AWAY_SEVOFL = rosetta_MDC_CONC_AWAY_SEVOFL

rosetta_MDC_CONC_AWAY_SEVOFL_ET = "MDC_CONC_AWAY_SEVOFL_ET"

rosetta.MDC_CONC_AWAY_SEVOFL_ET = rosetta_MDC_CONC_AWAY_SEVOFL_ET

rosetta_MDC_CONC_AWAY_SEVOFL_INSP = "MDC_CONC_AWAY_SEVOFL_INSP"

rosetta.MDC_CONC_AWAY_SEVOFL_INSP = rosetta_MDC_CONC_AWAY_SEVOFL_INSP

rosetta_MDC_CONC_CA_ART = "MDC_CONC_CA_ART"

rosetta.MDC_CONC_CA_ART = rosetta_MDC_CONC_CA_ART

rosetta_MDC_CONC_CA_GEN = "MDC_CONC_CA_GEN"

rosetta.MDC_CONC_CA_GEN = rosetta_MDC_CONC_CA_GEN

rosetta_MDC_CONC_CA_PH_NORMALIZED_ART = "MDC_CONC_CA_PH_NORMALIZED_ART"

rosetta.MDC_CONC_CA_PH_NORMALIZED_ART = rosetta_MDC_CONC_CA_PH_NORMALIZED_ART

rosetta_MDC_CONC_CHLORIDE_GEN = "MDC_CONC_CHLORIDE_GEN"

rosetta.MDC_CONC_CHLORIDE_GEN = rosetta_MDC_CONC_CHLORIDE_GEN

rosetta_MDC_CONC_CHLOR_GEN = "MDC_CONC_CHLOR_GEN"

rosetta.MDC_CONC_CHLOR_GEN = rosetta_MDC_CONC_CHLOR_GEN

rosetta_MDC_CONC_CO2 = "MDC_CONC_CO2"

rosetta.MDC_CONC_CO2 = rosetta_MDC_CONC_CO2

rosetta_MDC_CONC_CO2_BREATH = "MDC_CONC_CO2_BREATH"

rosetta.MDC_CONC_CO2_BREATH = rosetta_MDC_CONC_CO2_BREATH

rosetta_MDC_CONC_CO2_ET = "MDC_CONC_CO2_ET"

rosetta.MDC_CONC_CO2_ET = rosetta_MDC_CONC_CO2_ET

rosetta_MDC_CONC_CO2_ET_SETTING = "MDC_CONC_CO2_ET_SETTING"

rosetta.MDC_CONC_CO2_ET_SETTING = rosetta_MDC_CONC_CO2_ET_SETTING

rosetta_MDC_CONC_CO2_EXP = "MDC_CONC_CO2_EXP"

rosetta.MDC_CONC_CO2_EXP = rosetta_MDC_CONC_CO2_EXP

rosetta_MDC_CONC_CO2_EXP_SETTING = "MDC_CONC_CO2_EXP_SETTING"

rosetta.MDC_CONC_CO2_EXP_SETTING = rosetta_MDC_CONC_CO2_EXP_SETTING

rosetta_MDC_CONC_CO2_FG_SETTING = "MDC_CONC_CO2_FG_SETTING"

rosetta.MDC_CONC_CO2_FG_SETTING = rosetta_MDC_CONC_CO2_FG_SETTING

rosetta_MDC_CONC_CO2_INSP = "MDC_CONC_CO2_INSP"

rosetta.MDC_CONC_CO2_INSP = rosetta_MDC_CONC_CO2_INSP

rosetta_MDC_CONC_CO2_INSP_SETTING = "MDC_CONC_CO2_INSP_SETTING"

rosetta.MDC_CONC_CO2_INSP_SETTING = rosetta_MDC_CONC_CO2_INSP_SETTING

rosetta_MDC_CONC_CO2_SETTING = "MDC_CONC_CO2_SETTING"

rosetta.MDC_CONC_CO2_SETTING = rosetta_MDC_CONC_CO2_SETTING

rosetta_MDC_CONC_DESFL = "MDC_CONC_DESFL"

rosetta.MDC_CONC_DESFL = rosetta_MDC_CONC_DESFL

rosetta_MDC_CONC_DESFL_BREATH = "MDC_CONC_DESFL_BREATH"

rosetta.MDC_CONC_DESFL_BREATH = rosetta_MDC_CONC_DESFL_BREATH

rosetta_MDC_CONC_DESFL_ET = "MDC_CONC_DESFL_ET"

rosetta.MDC_CONC_DESFL_ET = rosetta_MDC_CONC_DESFL_ET

rosetta_MDC_CONC_DESFL_ET_SETTING = "MDC_CONC_DESFL_ET_SETTING"

rosetta.MDC_CONC_DESFL_ET_SETTING = rosetta_MDC_CONC_DESFL_ET_SETTING

rosetta_MDC_CONC_DESFL_EXP = "MDC_CONC_DESFL_EXP"

rosetta.MDC_CONC_DESFL_EXP = rosetta_MDC_CONC_DESFL_EXP

rosetta_MDC_CONC_DESFL_EXP_SETTING = "MDC_CONC_DESFL_EXP_SETTING"

rosetta.MDC_CONC_DESFL_EXP_SETTING = rosetta_MDC_CONC_DESFL_EXP_SETTING

rosetta_MDC_CONC_DESFL_FG_SETTING = "MDC_CONC_DESFL_FG_SETTING"

rosetta.MDC_CONC_DESFL_FG_SETTING = rosetta_MDC_CONC_DESFL_FG_SETTING

rosetta_MDC_CONC_DESFL_INSP = "MDC_CONC_DESFL_INSP"

rosetta.MDC_CONC_DESFL_INSP = rosetta_MDC_CONC_DESFL_INSP

rosetta_MDC_CONC_DESFL_INSP_SETTING = "MDC_CONC_DESFL_INSP_SETTING"

rosetta.MDC_CONC_DESFL_INSP_SETTING = rosetta_MDC_CONC_DESFL_INSP_SETTING

rosetta_MDC_CONC_DESFL_SETTING = "MDC_CONC_DESFL_SETTING"

rosetta.MDC_CONC_DESFL_SETTING = rosetta_MDC_CONC_DESFL_SETTING

rosetta_MDC_CONC_DRUG = "MDC_CONC_DRUG"

rosetta.MDC_CONC_DRUG = rosetta_MDC_CONC_DRUG

rosetta_MDC_CONC_ENFL = "MDC_CONC_ENFL"

rosetta.MDC_CONC_ENFL = rosetta_MDC_CONC_ENFL

rosetta_MDC_CONC_ENFL_BREATH = "MDC_CONC_ENFL_BREATH"

rosetta.MDC_CONC_ENFL_BREATH = rosetta_MDC_CONC_ENFL_BREATH

rosetta_MDC_CONC_ENFL_ET = "MDC_CONC_ENFL_ET"

rosetta.MDC_CONC_ENFL_ET = rosetta_MDC_CONC_ENFL_ET

rosetta_MDC_CONC_ENFL_ET_SETTING = "MDC_CONC_ENFL_ET_SETTING"

rosetta.MDC_CONC_ENFL_ET_SETTING = rosetta_MDC_CONC_ENFL_ET_SETTING

rosetta_MDC_CONC_ENFL_EXP = "MDC_CONC_ENFL_EXP"

rosetta.MDC_CONC_ENFL_EXP = rosetta_MDC_CONC_ENFL_EXP

rosetta_MDC_CONC_ENFL_EXP_SETTING = "MDC_CONC_ENFL_EXP_SETTING"

rosetta.MDC_CONC_ENFL_EXP_SETTING = rosetta_MDC_CONC_ENFL_EXP_SETTING

rosetta_MDC_CONC_ENFL_FG_SETTING = "MDC_CONC_ENFL_FG_SETTING"

rosetta.MDC_CONC_ENFL_FG_SETTING = rosetta_MDC_CONC_ENFL_FG_SETTING

rosetta_MDC_CONC_ENFL_INSP = "MDC_CONC_ENFL_INSP"

rosetta.MDC_CONC_ENFL_INSP = rosetta_MDC_CONC_ENFL_INSP

rosetta_MDC_CONC_ENFL_INSP_SETTING = "MDC_CONC_ENFL_INSP_SETTING"

rosetta.MDC_CONC_ENFL_INSP_SETTING = rosetta_MDC_CONC_ENFL_INSP_SETTING

rosetta_MDC_CONC_ENFL_SETTING = "MDC_CONC_ENFL_SETTING"

rosetta.MDC_CONC_ENFL_SETTING = rosetta_MDC_CONC_ENFL_SETTING

rosetta_MDC_CONC_GLU_GEN = "MDC_CONC_GLU_GEN"

rosetta.MDC_CONC_GLU_GEN = rosetta_MDC_CONC_GLU_GEN

rosetta_MDC_CONC_HALOTH = "MDC_CONC_HALOTH"

rosetta.MDC_CONC_HALOTH = rosetta_MDC_CONC_HALOTH

rosetta_MDC_CONC_HALOTH_BREATH = "MDC_CONC_HALOTH_BREATH"

rosetta.MDC_CONC_HALOTH_BREATH = rosetta_MDC_CONC_HALOTH_BREATH

rosetta_MDC_CONC_HALOTH_ET = "MDC_CONC_HALOTH_ET"

rosetta.MDC_CONC_HALOTH_ET = rosetta_MDC_CONC_HALOTH_ET

rosetta_MDC_CONC_HALOTH_ET_SETTING = "MDC_CONC_HALOTH_ET_SETTING"

rosetta.MDC_CONC_HALOTH_ET_SETTING = rosetta_MDC_CONC_HALOTH_ET_SETTING

rosetta_MDC_CONC_HALOTH_EXP = "MDC_CONC_HALOTH_EXP"

rosetta.MDC_CONC_HALOTH_EXP = rosetta_MDC_CONC_HALOTH_EXP

rosetta_MDC_CONC_HALOTH_EXP_SETTING = "MDC_CONC_HALOTH_EXP_SETTING"

rosetta.MDC_CONC_HALOTH_EXP_SETTING = rosetta_MDC_CONC_HALOTH_EXP_SETTING

rosetta_MDC_CONC_HALOTH_FG_SETTING = "MDC_CONC_HALOTH_FG_SETTING"

rosetta.MDC_CONC_HALOTH_FG_SETTING = rosetta_MDC_CONC_HALOTH_FG_SETTING

rosetta_MDC_CONC_HALOTH_INSP = "MDC_CONC_HALOTH_INSP"

rosetta.MDC_CONC_HALOTH_INSP = rosetta_MDC_CONC_HALOTH_INSP

rosetta_MDC_CONC_HALOTH_INSP_SETTING = "MDC_CONC_HALOTH_INSP_SETTING"

rosetta.MDC_CONC_HALOTH_INSP_SETTING = rosetta_MDC_CONC_HALOTH_INSP_SETTING

rosetta_MDC_CONC_HALOTH_SETTING = "MDC_CONC_HALOTH_SETTING"

rosetta.MDC_CONC_HALOTH_SETTING = rosetta_MDC_CONC_HALOTH_SETTING

rosetta_MDC_CONC_HB_ART = "MDC_CONC_HB_ART"

rosetta.MDC_CONC_HB_ART = rosetta_MDC_CONC_HB_ART

rosetta_MDC_CONC_HB_O2_ART = "MDC_CONC_HB_O2_ART"

rosetta.MDC_CONC_HB_O2_ART = rosetta_MDC_CONC_HB_O2_ART

rosetta_MDC_CONC_HB_O2_VEN = "MDC_CONC_HB_O2_VEN"

rosetta.MDC_CONC_HB_O2_VEN = rosetta_MDC_CONC_HB_O2_VEN

rosetta_MDC_CONC_HCO3_ART = "MDC_CONC_HCO3_ART"

rosetta.MDC_CONC_HCO3_ART = rosetta_MDC_CONC_HCO3_ART

rosetta_MDC_CONC_HCO3_GEN = "MDC_CONC_HCO3_GEN"

rosetta.MDC_CONC_HCO3_GEN = rosetta_MDC_CONC_HCO3_GEN

rosetta_MDC_CONC_HCT_ART = "MDC_CONC_HCT_ART"

rosetta.MDC_CONC_HCT_ART = rosetta_MDC_CONC_HCT_ART

rosetta_MDC_CONC_HCT_GEN = "MDC_CONC_HCT_GEN"

rosetta.MDC_CONC_HCT_GEN = rosetta_MDC_CONC_HCT_GEN

rosetta_MDC_CONC_HE = "MDC_CONC_HE"

rosetta.MDC_CONC_HE = rosetta_MDC_CONC_HE

rosetta_MDC_CONC_HE_BREATH = "MDC_CONC_HE_BREATH"

rosetta.MDC_CONC_HE_BREATH = rosetta_MDC_CONC_HE_BREATH

rosetta_MDC_CONC_HE_ET = "MDC_CONC_HE_ET"

rosetta.MDC_CONC_HE_ET = rosetta_MDC_CONC_HE_ET

rosetta_MDC_CONC_HE_EXP = "MDC_CONC_HE_EXP"

rosetta.MDC_CONC_HE_EXP = rosetta_MDC_CONC_HE_EXP

rosetta_MDC_CONC_HE_INSP = "MDC_CONC_HE_INSP"

rosetta.MDC_CONC_HE_INSP = rosetta_MDC_CONC_HE_INSP

rosetta_MDC_CONC_ISOFL = "MDC_CONC_ISOFL"

rosetta.MDC_CONC_ISOFL = rosetta_MDC_CONC_ISOFL

rosetta_MDC_CONC_ISOFL_BREATH = "MDC_CONC_ISOFL_BREATH"

rosetta.MDC_CONC_ISOFL_BREATH = rosetta_MDC_CONC_ISOFL_BREATH

rosetta_MDC_CONC_ISOFL_ET = "MDC_CONC_ISOFL_ET"

rosetta.MDC_CONC_ISOFL_ET = rosetta_MDC_CONC_ISOFL_ET

rosetta_MDC_CONC_ISOFL_ET_SETTING = "MDC_CONC_ISOFL_ET_SETTING"

rosetta.MDC_CONC_ISOFL_ET_SETTING = rosetta_MDC_CONC_ISOFL_ET_SETTING

rosetta_MDC_CONC_ISOFL_EXP = "MDC_CONC_ISOFL_EXP"

rosetta.MDC_CONC_ISOFL_EXP = rosetta_MDC_CONC_ISOFL_EXP

rosetta_MDC_CONC_ISOFL_EXP_SETTING = "MDC_CONC_ISOFL_EXP_SETTING"

rosetta.MDC_CONC_ISOFL_EXP_SETTING = rosetta_MDC_CONC_ISOFL_EXP_SETTING

rosetta_MDC_CONC_ISOFL_FG_SETTING = "MDC_CONC_ISOFL_FG_SETTING"

rosetta.MDC_CONC_ISOFL_FG_SETTING = rosetta_MDC_CONC_ISOFL_FG_SETTING

rosetta_MDC_CONC_ISOFL_INSP = "MDC_CONC_ISOFL_INSP"

rosetta.MDC_CONC_ISOFL_INSP = rosetta_MDC_CONC_ISOFL_INSP

rosetta_MDC_CONC_ISOFL_INSP_SETTING = "MDC_CONC_ISOFL_INSP_SETTING"

rosetta.MDC_CONC_ISOFL_INSP_SETTING = rosetta_MDC_CONC_ISOFL_INSP_SETTING

rosetta_MDC_CONC_ISOFL_SETTING = "MDC_CONC_ISOFL_SETTING"

rosetta.MDC_CONC_ISOFL_SETTING = rosetta_MDC_CONC_ISOFL_SETTING

rosetta_MDC_CONC_K_GEN = "MDC_CONC_K_GEN"

rosetta.MDC_CONC_K_GEN = rosetta_MDC_CONC_K_GEN

rosetta_MDC_CONC_MAC = "MDC_CONC_MAC"

rosetta.MDC_CONC_MAC = rosetta_MDC_CONC_MAC

rosetta_MDC_CONC_MAC_SUM = "MDC_CONC_MAC_SUM"

rosetta.MDC_CONC_MAC_SUM = rosetta_MDC_CONC_MAC_SUM

rosetta_MDC_CONC_MAC_SUM_AGE_CORR = "MDC_CONC_MAC_SUM_AGE_CORR"

rosetta.MDC_CONC_MAC_SUM_AGE_CORR = rosetta_MDC_CONC_MAC_SUM_AGE_CORR

rosetta_MDC_CONC_N2 = "MDC_CONC_N2"

rosetta.MDC_CONC_N2 = rosetta_MDC_CONC_N2

rosetta_MDC_CONC_N2O = "MDC_CONC_N2O"

rosetta.MDC_CONC_N2O = rosetta_MDC_CONC_N2O

rosetta_MDC_CONC_N2O_BREATH = "MDC_CONC_N2O_BREATH"

rosetta.MDC_CONC_N2O_BREATH = rosetta_MDC_CONC_N2O_BREATH

rosetta_MDC_CONC_N2O_ET = "MDC_CONC_N2O_ET"

rosetta.MDC_CONC_N2O_ET = rosetta_MDC_CONC_N2O_ET

rosetta_MDC_CONC_N2O_ET_SETTING = "MDC_CONC_N2O_ET_SETTING"

rosetta.MDC_CONC_N2O_ET_SETTING = rosetta_MDC_CONC_N2O_ET_SETTING

rosetta_MDC_CONC_N2O_EXP = "MDC_CONC_N2O_EXP"

rosetta.MDC_CONC_N2O_EXP = rosetta_MDC_CONC_N2O_EXP

rosetta_MDC_CONC_N2O_EXP_SETTING = "MDC_CONC_N2O_EXP_SETTING"

rosetta.MDC_CONC_N2O_EXP_SETTING = rosetta_MDC_CONC_N2O_EXP_SETTING

rosetta_MDC_CONC_N2O_FG_SETTING = "MDC_CONC_N2O_FG_SETTING"

rosetta.MDC_CONC_N2O_FG_SETTING = rosetta_MDC_CONC_N2O_FG_SETTING

rosetta_MDC_CONC_N2O_INSP = "MDC_CONC_N2O_INSP"

rosetta.MDC_CONC_N2O_INSP = rosetta_MDC_CONC_N2O_INSP

rosetta_MDC_CONC_N2O_INSP_SETTING = "MDC_CONC_N2O_INSP_SETTING"

rosetta.MDC_CONC_N2O_INSP_SETTING = rosetta_MDC_CONC_N2O_INSP_SETTING

rosetta_MDC_CONC_N2O_SETTING = "MDC_CONC_N2O_SETTING"

rosetta.MDC_CONC_N2O_SETTING = rosetta_MDC_CONC_N2O_SETTING

rosetta_MDC_CONC_N2_BREATH = "MDC_CONC_N2_BREATH"

rosetta.MDC_CONC_N2_BREATH = rosetta_MDC_CONC_N2_BREATH

rosetta_MDC_CONC_N2_ET = "MDC_CONC_N2_ET"

rosetta.MDC_CONC_N2_ET = rosetta_MDC_CONC_N2_ET

rosetta_MDC_CONC_N2_EXP = "MDC_CONC_N2_EXP"

rosetta.MDC_CONC_N2_EXP = rosetta_MDC_CONC_N2_EXP

rosetta_MDC_CONC_N2_INSP = "MDC_CONC_N2_INSP"

rosetta.MDC_CONC_N2_INSP = rosetta_MDC_CONC_N2_INSP

rosetta_MDC_CONC_NA_GEN = "MDC_CONC_NA_GEN"

rosetta.MDC_CONC_NA_GEN = rosetta_MDC_CONC_NA_GEN

rosetta_MDC_CONC_NA_SERUM = "MDC_CONC_NA_SERUM"

rosetta.MDC_CONC_NA_SERUM = rosetta_MDC_CONC_NA_SERUM

rosetta_MDC_CONC_NA_URINE = "MDC_CONC_NA_URINE"

rosetta.MDC_CONC_NA_URINE = rosetta_MDC_CONC_NA_URINE

rosetta_MDC_CONC_NO2 = "MDC_CONC_NO2"

rosetta.MDC_CONC_NO2 = rosetta_MDC_CONC_NO2

rosetta_MDC_CONC_NO2_BREATH = "MDC_CONC_NO2_BREATH"

rosetta.MDC_CONC_NO2_BREATH = rosetta_MDC_CONC_NO2_BREATH

rosetta_MDC_CONC_NO2_ET = "MDC_CONC_NO2_ET"

rosetta.MDC_CONC_NO2_ET = rosetta_MDC_CONC_NO2_ET

rosetta_MDC_CONC_NO2_EXP = "MDC_CONC_NO2_EXP"

rosetta.MDC_CONC_NO2_EXP = rosetta_MDC_CONC_NO2_EXP

rosetta_MDC_CONC_NO2_INSP = "MDC_CONC_NO2_INSP"

rosetta.MDC_CONC_NO2_INSP = rosetta_MDC_CONC_NO2_INSP

rosetta_MDC_CONC_O2 = "MDC_CONC_O2"

rosetta.MDC_CONC_O2 = rosetta_MDC_CONC_O2

rosetta_MDC_CONC_O2_BREATH = "MDC_CONC_O2_BREATH"

rosetta.MDC_CONC_O2_BREATH = rosetta_MDC_CONC_O2_BREATH

rosetta_MDC_CONC_O2_ET = "MDC_CONC_O2_ET"

rosetta.MDC_CONC_O2_ET = rosetta_MDC_CONC_O2_ET

rosetta_MDC_CONC_O2_ET_SETTING = "MDC_CONC_O2_ET_SETTING"

rosetta.MDC_CONC_O2_ET_SETTING = rosetta_MDC_CONC_O2_ET_SETTING

rosetta_MDC_CONC_O2_EXP = "MDC_CONC_O2_EXP"

rosetta.MDC_CONC_O2_EXP = rosetta_MDC_CONC_O2_EXP

rosetta_MDC_CONC_O2_EXP_SETTING = "MDC_CONC_O2_EXP_SETTING"

rosetta.MDC_CONC_O2_EXP_SETTING = rosetta_MDC_CONC_O2_EXP_SETTING

rosetta_MDC_CONC_O2_FG_SETTING = "MDC_CONC_O2_FG_SETTING"

rosetta.MDC_CONC_O2_FG_SETTING = rosetta_MDC_CONC_O2_FG_SETTING

rosetta_MDC_CONC_O2_INSP = "MDC_CONC_O2_INSP"

rosetta.MDC_CONC_O2_INSP = rosetta_MDC_CONC_O2_INSP

rosetta_MDC_CONC_O2_INSP_SETTING = "MDC_CONC_O2_INSP_SETTING"

rosetta.MDC_CONC_O2_INSP_SETTING = rosetta_MDC_CONC_O2_INSP_SETTING

rosetta_MDC_CONC_O2_MICROENV = "MDC_CONC_O2_MICROENV"

rosetta.MDC_CONC_O2_MICROENV = rosetta_MDC_CONC_O2_MICROENV

rosetta_MDC_CONC_O2_MICROENV_SETTING = "MDC_CONC_O2_MICROENV_SETTING"

rosetta.MDC_CONC_O2_MICROENV_SETTING = rosetta_MDC_CONC_O2_MICROENV_SETTING

rosetta_MDC_CONC_O2_SETTING = "MDC_CONC_O2_SETTING"

rosetta.MDC_CONC_O2_SETTING = rosetta_MDC_CONC_O2_SETTING

rosetta_MDC_CONC_PCO2_ART = "MDC_CONC_PCO2_ART"

rosetta.MDC_CONC_PCO2_ART = rosetta_MDC_CONC_PCO2_ART

rosetta_MDC_CONC_PCO2_ART_PULM = "MDC_CONC_PCO2_ART_PULM"

rosetta.MDC_CONC_PCO2_ART_PULM = rosetta_MDC_CONC_PCO2_ART_PULM

rosetta_MDC_CONC_PCO2_GASTRIC_ART_DIFF = "MDC_CONC_PCO2_GASTRIC_ART_DIFF"

rosetta.MDC_CONC_PCO2_GASTRIC_ART_DIFF = rosetta_MDC_CONC_PCO2_GASTRIC_ART_DIFF

rosetta_MDC_CONC_PCO2_GASTRIC_ET_DIFF = "MDC_CONC_PCO2_GASTRIC_ET_DIFF"

rosetta.MDC_CONC_PCO2_GASTRIC_ET_DIFF = rosetta_MDC_CONC_PCO2_GASTRIC_ET_DIFF

rosetta_MDC_CONC_PCO2_GASTRIC_MUCOSAL = "MDC_CONC_PCO2_GASTRIC_MUCOSAL"

rosetta.MDC_CONC_PCO2_GASTRIC_MUCOSAL = rosetta_MDC_CONC_PCO2_GASTRIC_MUCOSAL

rosetta_MDC_CONC_PCO2_GEN = "MDC_CONC_PCO2_GEN"

rosetta.MDC_CONC_PCO2_GEN = rosetta_MDC_CONC_PCO2_GEN

rosetta_MDC_CONC_PCO2_VEN = "MDC_CONC_PCO2_VEN"

rosetta.MDC_CONC_PCO2_VEN = rosetta_MDC_CONC_PCO2_VEN

rosetta_MDC_CONC_PH_ART = "MDC_CONC_PH_ART"

rosetta.MDC_CONC_PH_ART = rosetta_MDC_CONC_PH_ART

rosetta_MDC_CONC_PH_GEN = "MDC_CONC_PH_GEN"

rosetta.MDC_CONC_PH_GEN = rosetta_MDC_CONC_PH_GEN

rosetta_MDC_CONC_PH_INTRAMUCOSAL = "MDC_CONC_PH_INTRAMUCOSAL"

rosetta.MDC_CONC_PH_INTRAMUCOSAL = rosetta_MDC_CONC_PH_INTRAMUCOSAL

rosetta_MDC_CONC_PH_VEN = "MDC_CONC_PH_VEN"

rosetta.MDC_CONC_PH_VEN = rosetta_MDC_CONC_PH_VEN

rosetta_MDC_CONC_PO2_ART = "MDC_CONC_PO2_ART"

rosetta.MDC_CONC_PO2_ART = rosetta_MDC_CONC_PO2_ART

rosetta_MDC_CONC_PO2_ART_VEN_DIFF = "MDC_CONC_PO2_ART_VEN_DIFF"

rosetta.MDC_CONC_PO2_ART_VEN_DIFF = rosetta_MDC_CONC_PO2_ART_VEN_DIFF

rosetta_MDC_CONC_PO2_GEN = "MDC_CONC_PO2_GEN"

rosetta.MDC_CONC_PO2_GEN = rosetta_MDC_CONC_PO2_GEN

rosetta_MDC_CONC_PO2_VEN = "MDC_CONC_PO2_VEN"

rosetta.MDC_CONC_PO2_VEN = rosetta_MDC_CONC_PO2_VEN

rosetta_MDC_CONC_SEVOFL = "MDC_CONC_SEVOFL"

rosetta.MDC_CONC_SEVOFL = rosetta_MDC_CONC_SEVOFL

rosetta_MDC_CONC_SEVOFL_BREATH = "MDC_CONC_SEVOFL_BREATH"

rosetta.MDC_CONC_SEVOFL_BREATH = rosetta_MDC_CONC_SEVOFL_BREATH

rosetta_MDC_CONC_SEVOFL_ET = "MDC_CONC_SEVOFL_ET"

rosetta.MDC_CONC_SEVOFL_ET = rosetta_MDC_CONC_SEVOFL_ET

rosetta_MDC_CONC_SEVOFL_ET_SETTING = "MDC_CONC_SEVOFL_ET_SETTING"

rosetta.MDC_CONC_SEVOFL_ET_SETTING = rosetta_MDC_CONC_SEVOFL_ET_SETTING

rosetta_MDC_CONC_SEVOFL_EXP = "MDC_CONC_SEVOFL_EXP"

rosetta.MDC_CONC_SEVOFL_EXP = rosetta_MDC_CONC_SEVOFL_EXP

rosetta_MDC_CONC_SEVOFL_EXP_SETTING = "MDC_CONC_SEVOFL_EXP_SETTING"

rosetta.MDC_CONC_SEVOFL_EXP_SETTING = rosetta_MDC_CONC_SEVOFL_EXP_SETTING

rosetta_MDC_CONC_SEVOFL_FG_SETTING = "MDC_CONC_SEVOFL_FG_SETTING"

rosetta.MDC_CONC_SEVOFL_FG_SETTING = rosetta_MDC_CONC_SEVOFL_FG_SETTING

rosetta_MDC_CONC_SEVOFL_INSP = "MDC_CONC_SEVOFL_INSP"

rosetta.MDC_CONC_SEVOFL_INSP = rosetta_MDC_CONC_SEVOFL_INSP

rosetta_MDC_CONC_SEVOFL_INSP_SETTING = "MDC_CONC_SEVOFL_INSP_SETTING"

rosetta.MDC_CONC_SEVOFL_INSP_SETTING = rosetta_MDC_CONC_SEVOFL_INSP_SETTING

rosetta_MDC_CONC_SEVOFL_SETTING = "MDC_CONC_SEVOFL_SETTING"

rosetta.MDC_CONC_SEVOFL_SETTING = rosetta_MDC_CONC_SEVOFL_SETTING

rosetta_MDC_CONC_UREA_ART = "MDC_CONC_UREA_ART"

rosetta.MDC_CONC_UREA_ART = rosetta_MDC_CONC_UREA_ART

rosetta_MDC_DESAT = "MDC_DESAT"

rosetta.MDC_DESAT = rosetta_MDC_DESAT

rosetta_MDC_DEV_PUMP_INFUS_CHAN_CLINICIAN_DOSE = "MDC_DEV_PUMP_INFUS_CHAN_CLINICIAN_DOSE"

rosetta.MDC_DEV_PUMP_INFUS_CHAN_CLINICIAN_DOSE = rosetta_MDC_DEV_PUMP_INFUS_CHAN_CLINICIAN_DOSE

rosetta_MDC_DEV_PUMP_INFUS_CHAN_DELIVERY = "MDC_DEV_PUMP_INFUS_CHAN_DELIVERY"

rosetta.MDC_DEV_PUMP_INFUS_CHAN_DELIVERY = rosetta_MDC_DEV_PUMP_INFUS_CHAN_DELIVERY

rosetta_MDC_DEV_PUMP_INFUS_CHAN_LOADING_DOSE = "MDC_DEV_PUMP_INFUS_CHAN_LOADING_DOSE"

rosetta.MDC_DEV_PUMP_INFUS_CHAN_LOADING_DOSE = rosetta_MDC_DEV_PUMP_INFUS_CHAN_LOADING_DOSE

rosetta_MDC_DEV_PUMP_INFUS_CHAN_PRIMARY = "MDC_DEV_PUMP_INFUS_CHAN_PRIMARY"

rosetta.MDC_DEV_PUMP_INFUS_CHAN_PRIMARY = rosetta_MDC_DEV_PUMP_INFUS_CHAN_PRIMARY

rosetta_MDC_DEV_PUMP_INFUS_CHAN_SECONDARY = "MDC_DEV_PUMP_INFUS_CHAN_SECONDARY"

rosetta.MDC_DEV_PUMP_INFUS_CHAN_SECONDARY = rosetta_MDC_DEV_PUMP_INFUS_CHAN_SECONDARY

rosetta_MDC_DEV_PUMP_INFUS_LVP = "MDC_DEV_PUMP_INFUS_LVP"

rosetta.MDC_DEV_PUMP_INFUS_LVP = rosetta_MDC_DEV_PUMP_INFUS_LVP

rosetta_MDC_DEV_PUMP_INFUS_LVP_MDS = "MDC_DEV_PUMP_INFUS_LVP_MDS"

rosetta.MDC_DEV_PUMP_INFUS_LVP_MDS = rosetta_MDC_DEV_PUMP_INFUS_LVP_MDS

rosetta_MDC_DEV_PUMP_INFUS_LVP_VMD = "MDC_DEV_PUMP_INFUS_LVP_VMD"

rosetta.MDC_DEV_PUMP_INFUS_LVP_VMD = rosetta_MDC_DEV_PUMP_INFUS_LVP_VMD

rosetta_MDC_DEV_PUMP_INFUS_PCA = "MDC_DEV_PUMP_INFUS_PCA"

rosetta.MDC_DEV_PUMP_INFUS_PCA = rosetta_MDC_DEV_PUMP_INFUS_PCA

rosetta_MDC_DEV_PUMP_INFUS_PCA_CHAN = "MDC_DEV_PUMP_INFUS_PCA_CHAN"

rosetta.MDC_DEV_PUMP_INFUS_PCA_CHAN = rosetta_MDC_DEV_PUMP_INFUS_PCA_CHAN

rosetta_MDC_DEV_PUMP_INFUS_PCA_MDS = "MDC_DEV_PUMP_INFUS_PCA_MDS"

rosetta.MDC_DEV_PUMP_INFUS_PCA_MDS = rosetta_MDC_DEV_PUMP_INFUS_PCA_MDS

rosetta_MDC_DEV_PUMP_INFUS_PCA_SYRINGE = "MDC_DEV_PUMP_INFUS_PCA_SYRINGE"

rosetta.MDC_DEV_PUMP_INFUS_PCA_SYRINGE = rosetta_MDC_DEV_PUMP_INFUS_PCA_SYRINGE

rosetta_MDC_DEV_PUMP_INFUS_PCA_SYRINGE_MDS = "MDC_DEV_PUMP_INFUS_PCA_SYRINGE_MDS"

rosetta.MDC_DEV_PUMP_INFUS_PCA_SYRINGE_MDS = rosetta_MDC_DEV_PUMP_INFUS_PCA_SYRINGE_MDS

rosetta_MDC_DEV_PUMP_INFUS_PCA_SYRINGE_VMD = "MDC_DEV_PUMP_INFUS_PCA_SYRINGE_VMD"

rosetta.MDC_DEV_PUMP_INFUS_PCA_SYRINGE_VMD = rosetta_MDC_DEV_PUMP_INFUS_PCA_SYRINGE_VMD

rosetta_MDC_DEV_PUMP_INFUS_PCA_VMD = "MDC_DEV_PUMP_INFUS_PCA_VMD"

rosetta.MDC_DEV_PUMP_INFUS_PCA_VMD = rosetta_MDC_DEV_PUMP_INFUS_PCA_VMD

rosetta_MDC_DEV_PUMP_INFUS_SYRINGE = "MDC_DEV_PUMP_INFUS_SYRINGE"

rosetta.MDC_DEV_PUMP_INFUS_SYRINGE = rosetta_MDC_DEV_PUMP_INFUS_SYRINGE

rosetta_MDC_DEV_PUMP_INFUS_SYRINGE_CHAN = "MDC_DEV_PUMP_INFUS_SYRINGE_CHAN"

rosetta.MDC_DEV_PUMP_INFUS_SYRINGE_CHAN = rosetta_MDC_DEV_PUMP_INFUS_SYRINGE_CHAN

rosetta_MDC_DEV_PUMP_INFUS_SYRINGE_MDS = "MDC_DEV_PUMP_INFUS_SYRINGE_MDS"

rosetta.MDC_DEV_PUMP_INFUS_SYRINGE_MDS = rosetta_MDC_DEV_PUMP_INFUS_SYRINGE_MDS

rosetta_MDC_DEV_PUMP_INFUS_SYRINGE_VMD = "MDC_DEV_PUMP_INFUS_SYRINGE_VMD"

rosetta.MDC_DEV_PUMP_INFUS_SYRINGE_VMD = rosetta_MDC_DEV_PUMP_INFUS_SYRINGE_VMD

rosetta_MDC_DOSE_DRUG_DELIV = "MDC_DOSE_DRUG_DELIV"

rosetta.MDC_DOSE_DRUG_DELIV = rosetta_MDC_DOSE_DRUG_DELIV

rosetta_MDC_DOSE_DRUG_DELIV_SEGMENT = "MDC_DOSE_DRUG_DELIV_SEGMENT"

rosetta.MDC_DOSE_DRUG_DELIV_SEGMENT = rosetta_MDC_DOSE_DRUG_DELIV_SEGMENT

rosetta_MDC_DOSE_DRUG_DELIV_TOTAL = "MDC_DOSE_DRUG_DELIV_TOTAL"

rosetta.MDC_DOSE_DRUG_DELIV_TOTAL = rosetta_MDC_DOSE_DRUG_DELIV_TOTAL

rosetta_MDC_DOSE_DRUG_TBI = "MDC_DOSE_DRUG_TBI"

rosetta.MDC_DOSE_DRUG_TBI = rosetta_MDC_DOSE_DRUG_TBI

rosetta_MDC_DOSE_DRUG_TBI_REMAIN = "MDC_DOSE_DRUG_TBI_REMAIN"

rosetta.MDC_DOSE_DRUG_TBI_REMAIN = rosetta_MDC_DOSE_DRUG_TBI_REMAIN

rosetta_MDC_DOSE_PCA_LIMIT = "MDC_DOSE_PCA_LIMIT"

rosetta.MDC_DOSE_PCA_LIMIT = rosetta_MDC_DOSE_PCA_LIMIT

rosetta_MDC_DRUG_ID = "MDC_DRUG_ID"

rosetta.MDC_DRUG_ID = rosetta_MDC_DRUG_ID

rosetta_MDC_DRUG_NAME_LABEL = "MDC_DRUG_NAME_LABEL"

rosetta.MDC_DRUG_NAME_LABEL = rosetta_MDC_DRUG_NAME_LABEL

rosetta_MDC_DRUG_NAME_TYPE = "MDC_DRUG_NAME_TYPE"

rosetta.MDC_DRUG_NAME_TYPE = rosetta_MDC_DRUG_NAME_TYPE

rosetta_MDC_ECG_AMPL_ST = "MDC_ECG_AMPL_ST"

rosetta.MDC_ECG_AMPL_ST = rosetta_MDC_ECG_AMPL_ST

rosetta_MDC_ECG_AMPL_ST_AI = "MDC_ECG_AMPL_ST_AI"

rosetta.MDC_ECG_AMPL_ST_AI = rosetta_MDC_ECG_AMPL_ST_AI

rosetta_MDC_ECG_AMPL_ST_AS = "MDC_ECG_AMPL_ST_AS"

rosetta.MDC_ECG_AMPL_ST_AS = rosetta_MDC_ECG_AMPL_ST_AS

rosetta_MDC_ECG_AMPL_ST_AVF = "MDC_ECG_AMPL_ST_AVF"

rosetta.MDC_ECG_AMPL_ST_AVF = rosetta_MDC_ECG_AMPL_ST_AVF

rosetta_MDC_ECG_AMPL_ST_AVL = "MDC_ECG_AMPL_ST_AVL"

rosetta.MDC_ECG_AMPL_ST_AVL = rosetta_MDC_ECG_AMPL_ST_AVL

rosetta_MDC_ECG_AMPL_ST_AVR = "MDC_ECG_AMPL_ST_AVR"

rosetta.MDC_ECG_AMPL_ST_AVR = rosetta_MDC_ECG_AMPL_ST_AVR

rosetta_MDC_ECG_AMPL_ST_dV1 = "MDC_ECG_AMPL_ST_dV1"

rosetta.MDC_ECG_AMPL_ST_dV1 = rosetta_MDC_ECG_AMPL_ST_dV1

rosetta_MDC_ECG_AMPL_ST_dV2 = "MDC_ECG_AMPL_ST_dV2"

rosetta.MDC_ECG_AMPL_ST_dV2 = rosetta_MDC_ECG_AMPL_ST_dV2

rosetta_MDC_ECG_AMPL_ST_dV3 = "MDC_ECG_AMPL_ST_dV3"

rosetta.MDC_ECG_AMPL_ST_dV3 = rosetta_MDC_ECG_AMPL_ST_dV3

rosetta_MDC_ECG_AMPL_ST_dV4 = "MDC_ECG_AMPL_ST_dV4"

rosetta.MDC_ECG_AMPL_ST_dV4 = rosetta_MDC_ECG_AMPL_ST_dV4

rosetta_MDC_ECG_AMPL_ST_dV5 = "MDC_ECG_AMPL_ST_dV5"

rosetta.MDC_ECG_AMPL_ST_dV5 = rosetta_MDC_ECG_AMPL_ST_dV5

rosetta_MDC_ECG_AMPL_ST_dV6 = "MDC_ECG_AMPL_ST_dV6"

rosetta.MDC_ECG_AMPL_ST_dV6 = rosetta_MDC_ECG_AMPL_ST_dV6

rosetta_MDC_ECG_AMPL_ST_ES = "MDC_ECG_AMPL_ST_ES"

rosetta.MDC_ECG_AMPL_ST_ES = rosetta_MDC_ECG_AMPL_ST_ES

rosetta_MDC_ECG_AMPL_ST_I = "MDC_ECG_AMPL_ST_I"

rosetta.MDC_ECG_AMPL_ST_I = rosetta_MDC_ECG_AMPL_ST_I

rosetta_MDC_ECG_AMPL_ST_II = "MDC_ECG_AMPL_ST_II"

rosetta.MDC_ECG_AMPL_ST_II = rosetta_MDC_ECG_AMPL_ST_II

rosetta_MDC_ECG_AMPL_ST_III = "MDC_ECG_AMPL_ST_III"

rosetta.MDC_ECG_AMPL_ST_III = rosetta_MDC_ECG_AMPL_ST_III

rosetta_MDC_ECG_AMPL_ST_MCL = "MDC_ECG_AMPL_ST_MCL"

rosetta.MDC_ECG_AMPL_ST_MCL = rosetta_MDC_ECG_AMPL_ST_MCL

rosetta_MDC_ECG_AMPL_ST_MCL1 = "MDC_ECG_AMPL_ST_MCL1"

rosetta.MDC_ECG_AMPL_ST_MCL1 = rosetta_MDC_ECG_AMPL_ST_MCL1

rosetta_MDC_ECG_AMPL_ST_MCL6 = "MDC_ECG_AMPL_ST_MCL6"

rosetta.MDC_ECG_AMPL_ST_MCL6 = rosetta_MDC_ECG_AMPL_ST_MCL6

rosetta_MDC_ECG_AMPL_ST_V = "MDC_ECG_AMPL_ST_V"

rosetta.MDC_ECG_AMPL_ST_V = rosetta_MDC_ECG_AMPL_ST_V

rosetta_MDC_ECG_AMPL_ST_V1 = "MDC_ECG_AMPL_ST_V1"

rosetta.MDC_ECG_AMPL_ST_V1 = rosetta_MDC_ECG_AMPL_ST_V1

rosetta_MDC_ECG_AMPL_ST_V2 = "MDC_ECG_AMPL_ST_V2"

rosetta.MDC_ECG_AMPL_ST_V2 = rosetta_MDC_ECG_AMPL_ST_V2

rosetta_MDC_ECG_AMPL_ST_V3 = "MDC_ECG_AMPL_ST_V3"

rosetta.MDC_ECG_AMPL_ST_V3 = rosetta_MDC_ECG_AMPL_ST_V3

rosetta_MDC_ECG_AMPL_ST_V4 = "MDC_ECG_AMPL_ST_V4"

rosetta.MDC_ECG_AMPL_ST_V4 = rosetta_MDC_ECG_AMPL_ST_V4

rosetta_MDC_ECG_AMPL_ST_V5 = "MDC_ECG_AMPL_ST_V5"

rosetta.MDC_ECG_AMPL_ST_V5 = rosetta_MDC_ECG_AMPL_ST_V5

rosetta_MDC_ECG_AMPL_ST_V6 = "MDC_ECG_AMPL_ST_V6"

rosetta.MDC_ECG_AMPL_ST_V6 = rosetta_MDC_ECG_AMPL_ST_V6

rosetta_MDC_ECG_ARRHY = "MDC_ECG_ARRHY"

rosetta.MDC_ECG_ARRHY = rosetta_MDC_ECG_ARRHY

rosetta_MDC_ECG_CARD_BEAT_RATE = "MDC_ECG_CARD_BEAT_RATE"

rosetta.MDC_ECG_CARD_BEAT_RATE = rosetta_MDC_ECG_CARD_BEAT_RATE

rosetta_MDC_ECG_CARD_BEAT_RATE_BTB = "MDC_ECG_CARD_BEAT_RATE_BTB"

rosetta.MDC_ECG_CARD_BEAT_RATE_BTB = rosetta_MDC_ECG_CARD_BEAT_RATE_BTB

rosetta_MDC_ECG_HEART_RATE = "MDC_ECG_HEART_RATE"

rosetta.MDC_ECG_HEART_RATE = rosetta_MDC_ECG_HEART_RATE

rosetta_MDC_ECG_PACED_BEAT_RATE = "MDC_ECG_PACED_BEAT_RATE"

rosetta.MDC_ECG_PACED_BEAT_RATE = rosetta_MDC_ECG_PACED_BEAT_RATE

rosetta_MDC_ECG_STAT_ECT = "MDC_ECG_STAT_ECT"

rosetta.MDC_ECG_STAT_ECT = rosetta_MDC_ECG_STAT_ECT

rosetta_MDC_ECG_STAT_RHY = "MDC_ECG_STAT_RHY"

rosetta.MDC_ECG_STAT_RHY = rosetta_MDC_ECG_STAT_RHY

rosetta_MDC_ECG_TIME_PD_QTc = "MDC_ECG_TIME_PD_QTc"

rosetta.MDC_ECG_TIME_PD_QTc = rosetta_MDC_ECG_TIME_PD_QTc

rosetta_MDC_ECG_TIME_PD_QT_GL = "MDC_ECG_TIME_PD_QT_GL"

rosetta.MDC_ECG_TIME_PD_QT_GL = rosetta_MDC_ECG_TIME_PD_QT_GL

rosetta_MDC_ECG_TIME_PD_RR_GL = "MDC_ECG_TIME_PD_RR_GL"

rosetta.MDC_ECG_TIME_PD_RR_GL = rosetta_MDC_ECG_TIME_PD_RR_GL

rosetta_MDC_ECG_V_P_C_CNT = "MDC_ECG_V_P_C_CNT"

rosetta.MDC_ECG_V_P_C_CNT = rosetta_MDC_ECG_V_P_C_CNT

rosetta_MDC_ECG_V_P_C_RATE = "MDC_ECG_V_P_C_RATE"

rosetta.MDC_ECG_V_P_C_RATE = rosetta_MDC_ECG_V_P_C_RATE

rosetta_MDC_EEG_BISPECTRAL_INDEX = "MDC_EEG_BISPECTRAL_INDEX"

rosetta.MDC_EEG_BISPECTRAL_INDEX = rosetta_MDC_EEG_BISPECTRAL_INDEX

rosetta_MDC_EEG_ELEC_POTL_CRTX = "MDC_EEG_ELEC_POTL_CRTX"

rosetta.MDC_EEG_ELEC_POTL_CRTX = rosetta_MDC_EEG_ELEC_POTL_CRTX

rosetta_MDC_EEG_ENTROPY_RESPONSE = "MDC_EEG_ENTROPY_RESPONSE"

rosetta.MDC_EEG_ENTROPY_RESPONSE = rosetta_MDC_EEG_ENTROPY_RESPONSE

rosetta_MDC_EEG_ENTROPY_STATE = "MDC_EEG_ENTROPY_STATE"

rosetta.MDC_EEG_ENTROPY_STATE = rosetta_MDC_EEG_ENTROPY_STATE

rosetta_MDC_EEG_FREQ_PWR_SPEC_CRTX_DOM_MEAN = "MDC_EEG_FREQ_PWR_SPEC_CRTX_DOM_MEAN"

rosetta.MDC_EEG_FREQ_PWR_SPEC_CRTX_DOM_MEAN = rosetta_MDC_EEG_FREQ_PWR_SPEC_CRTX_DOM_MEAN

rosetta_MDC_EEG_FREQ_PWR_SPEC_CRTX_MEDIAN = "MDC_EEG_FREQ_PWR_SPEC_CRTX_MEDIAN"

rosetta.MDC_EEG_FREQ_PWR_SPEC_CRTX_MEDIAN = rosetta_MDC_EEG_FREQ_PWR_SPEC_CRTX_MEDIAN

rosetta_MDC_EEG_FREQ_PWR_SPEC_CRTX_PEAK = "MDC_EEG_FREQ_PWR_SPEC_CRTX_PEAK"

rosetta.MDC_EEG_FREQ_PWR_SPEC_CRTX_PEAK = rosetta_MDC_EEG_FREQ_PWR_SPEC_CRTX_PEAK

rosetta_MDC_EEG_FREQ_PWR_SPEC_CRTX_SPECTRAL_EDGE = "MDC_EEG_FREQ_PWR_SPEC_CRTX_SPECTRAL_EDGE"

rosetta.MDC_EEG_FREQ_PWR_SPEC_CRTX_SPECTRAL_EDGE = rosetta_MDC_EEG_FREQ_PWR_SPEC_CRTX_SPECTRAL_EDGE

rosetta_MDC_EEG_NUM_SEIZ = "MDC_EEG_NUM_SEIZ"

rosetta.MDC_EEG_NUM_SEIZ = rosetta_MDC_EEG_NUM_SEIZ

rosetta_MDC_EEG_NUM_SPK = "MDC_EEG_NUM_SPK"

rosetta.MDC_EEG_NUM_SPK = rosetta_MDC_EEG_NUM_SPK

rosetta_MDC_EEG_PAROX_CRTX_BURST_SUPPRN = "MDC_EEG_PAROX_CRTX_BURST_SUPPRN"

rosetta.MDC_EEG_PAROX_CRTX_BURST_SUPPRN = rosetta_MDC_EEG_PAROX_CRTX_BURST_SUPPRN

rosetta_MDC_EEG_PWR_SPEC_ALPHA_REL = "MDC_EEG_PWR_SPEC_ALPHA_REL"

rosetta.MDC_EEG_PWR_SPEC_ALPHA_REL = rosetta_MDC_EEG_PWR_SPEC_ALPHA_REL

rosetta_MDC_EEG_PWR_SPEC_BETA_REL = "MDC_EEG_PWR_SPEC_BETA_REL"

rosetta.MDC_EEG_PWR_SPEC_BETA_REL = rosetta_MDC_EEG_PWR_SPEC_BETA_REL

rosetta_MDC_EEG_PWR_SPEC_CSA = "MDC_EEG_PWR_SPEC_CSA"

rosetta.MDC_EEG_PWR_SPEC_CSA = rosetta_MDC_EEG_PWR_SPEC_CSA

rosetta_MDC_EEG_PWR_SPEC_DELTA_REL = "MDC_EEG_PWR_SPEC_DELTA_REL"

rosetta.MDC_EEG_PWR_SPEC_DELTA_REL = rosetta_MDC_EEG_PWR_SPEC_DELTA_REL

rosetta_MDC_EEG_PWR_SPEC_THETA_REL = "MDC_EEG_PWR_SPEC_THETA_REL"

rosetta.MDC_EEG_PWR_SPEC_THETA_REL = rosetta_MDC_EEG_PWR_SPEC_THETA_REL

rosetta_MDC_EEG_PWR_SPEC_TOT = "MDC_EEG_PWR_SPEC_TOT"

rosetta.MDC_EEG_PWR_SPEC_TOT = rosetta_MDC_EEG_PWR_SPEC_TOT

rosetta_MDC_EEG_SIGNAL_QUALITY_INDEX = "MDC_EEG_SIGNAL_QUALITY_INDEX"

rosetta.MDC_EEG_SIGNAL_QUALITY_INDEX = rosetta_MDC_EEG_SIGNAL_QUALITY_INDEX

rosetta_MDC_EEG_SNAP_INDEX = "MDC_EEG_SNAP_INDEX"

rosetta.MDC_EEG_SNAP_INDEX = rosetta_MDC_EEG_SNAP_INDEX

rosetta_MDC_EMG_ELEC_POTL_MUSCL = "MDC_EMG_ELEC_POTL_MUSCL"

rosetta.MDC_EMG_ELEC_POTL_MUSCL = rosetta_MDC_EMG_ELEC_POTL_MUSCL

rosetta_MDC_EVT_PATIENT_CHANGE = "MDC_EVT_PATIENT_CHANGE"

rosetta.MDC_EVT_PATIENT_CHANGE = rosetta_MDC_EVT_PATIENT_CHANGE

rosetta_MDC_EVT_PATIENT_ID_CHANGE = "MDC_EVT_PATIENT_ID_CHANGE"

rosetta.MDC_EVT_PATIENT_ID_CHANGE = rosetta_MDC_EVT_PATIENT_ID_CHANGE

rosetta_MDC_EVT_PATIENT_WEIGHT_CHANGE = "MDC_EVT_PATIENT_WEIGHT_CHANGE"

rosetta.MDC_EVT_PATIENT_WEIGHT_CHANGE = rosetta_MDC_EVT_PATIENT_WEIGHT_CHANGE

rosetta_MDC_EVT_PUMP_AUTO_PROG_CLEARED = "MDC_EVT_PUMP_AUTO_PROG_CLEARED"

rosetta.MDC_EVT_PUMP_AUTO_PROG_CLEARED = rosetta_MDC_EVT_PUMP_AUTO_PROG_CLEARED

rosetta_MDC_EVT_PUMP_DELIV_COMP = "MDC_EVT_PUMP_DELIV_COMP"

rosetta.MDC_EVT_PUMP_DELIV_COMP = rosetta_MDC_EVT_PUMP_DELIV_COMP

rosetta_MDC_EVT_PUMP_DELIV_START = "MDC_EVT_PUMP_DELIV_START"

rosetta.MDC_EVT_PUMP_DELIV_START = rosetta_MDC_EVT_PUMP_DELIV_START

rosetta_MDC_EVT_PUMP_DELIV_STOP = "MDC_EVT_PUMP_DELIV_STOP"

rosetta.MDC_EVT_PUMP_DELIV_STOP = rosetta_MDC_EVT_PUMP_DELIV_STOP

rosetta_MDC_EVT_PUMP_PROG_CLEARED = "MDC_EVT_PUMP_PROG_CLEARED"

rosetta.MDC_EVT_PUMP_PROG_CLEARED = rosetta_MDC_EVT_PUMP_PROG_CLEARED

rosetta_MDC_FLOW_AIR_FG = "MDC_FLOW_AIR_FG"

rosetta.MDC_FLOW_AIR_FG = rosetta_MDC_FLOW_AIR_FG

rosetta_MDC_FLOW_AWAY = "MDC_FLOW_AWAY"

rosetta.MDC_FLOW_AWAY = rosetta_MDC_FLOW_AWAY

rosetta_MDC_FLOW_AWAY_EXP = "MDC_FLOW_AWAY_EXP"

rosetta.MDC_FLOW_AWAY_EXP = rosetta_MDC_FLOW_AWAY_EXP

rosetta_MDC_FLOW_AWAY_EXP_MAX = "MDC_FLOW_AWAY_EXP_MAX"

rosetta.MDC_FLOW_AWAY_EXP_MAX = rosetta_MDC_FLOW_AWAY_EXP_MAX

rosetta_MDC_FLOW_AWAY_INSP_MAX = "MDC_FLOW_AWAY_INSP_MAX"

rosetta.MDC_FLOW_AWAY_INSP_MAX = rosetta_MDC_FLOW_AWAY_INSP_MAX

rosetta_MDC_FLOW_BLD_PULM_CAP = "MDC_FLOW_BLD_PULM_CAP"

rosetta.MDC_FLOW_BLD_PULM_CAP = rosetta_MDC_FLOW_BLD_PULM_CAP

rosetta_MDC_FLOW_CO2_PROD_RESP = "MDC_FLOW_CO2_PROD_RESP"

rosetta.MDC_FLOW_CO2_PROD_RESP = rosetta_MDC_FLOW_CO2_PROD_RESP

rosetta_MDC_FLOW_DRUG_DELIV = "MDC_FLOW_DRUG_DELIV"

rosetta.MDC_FLOW_DRUG_DELIV = rosetta_MDC_FLOW_DRUG_DELIV

rosetta_MDC_FLOW_FLUID_PUMP = "MDC_FLOW_FLUID_PUMP"

rosetta.MDC_FLOW_FLUID_PUMP = rosetta_MDC_FLOW_FLUID_PUMP

rosetta_MDC_FLOW_N2O_FG = "MDC_FLOW_N2O_FG"

rosetta.MDC_FLOW_N2O_FG = rosetta_MDC_FLOW_N2O_FG

rosetta_MDC_FLOW_O2_CONSUMP = "MDC_FLOW_O2_CONSUMP"

rosetta.MDC_FLOW_O2_CONSUMP = rosetta_MDC_FLOW_O2_CONSUMP

rosetta_MDC_FLOW_O2_FG = "MDC_FLOW_O2_FG"

rosetta.MDC_FLOW_O2_FG = rosetta_MDC_FLOW_O2_FG

rosetta_MDC_GRAD_PRESS_BLD_AORT_POS_MAX = "MDC_GRAD_PRESS_BLD_AORT_POS_MAX"

rosetta.MDC_GRAD_PRESS_BLD_AORT_POS_MAX = rosetta_MDC_GRAD_PRESS_BLD_AORT_POS_MAX

rosetta_MDC_IMPED_TTHOR = "MDC_IMPED_TTHOR"

rosetta.MDC_IMPED_TTHOR = rosetta_MDC_IMPED_TTHOR

rosetta_MDC_INFUS_DOSE_DELIV = "MDC_INFUS_DOSE_DELIV"

rosetta.MDC_INFUS_DOSE_DELIV = rosetta_MDC_INFUS_DOSE_DELIV

rosetta_MDC_LEN_BODY_ACTUAL = "MDC_LEN_BODY_ACTUAL"

rosetta.MDC_LEN_BODY_ACTUAL = rosetta_MDC_LEN_BODY_ACTUAL

rosetta_MDC_MASS_BODY_ACTUAL = "MDC_MASS_BODY_ACTUAL"

rosetta.MDC_MASS_BODY_ACTUAL = rosetta_MDC_MASS_BODY_ACTUAL

rosetta_MDC_MASS_DRUG_DELIV = "MDC_MASS_DRUG_DELIV"

rosetta.MDC_MASS_DRUG_DELIV = rosetta_MDC_MASS_DRUG_DELIV

rosetta_MDC_MASS_DRUG_REMAIN_CONTAINER = "MDC_MASS_DRUG_REMAIN_CONTAINER"

rosetta.MDC_MASS_DRUG_REMAIN_CONTAINER = rosetta_MDC_MASS_DRUG_REMAIN_CONTAINER

rosetta_MDC_MICROENV_AIR_CURTAIN_STATE = "MDC_MICROENV_AIR_CURTAIN_STATE"

rosetta.MDC_MICROENV_AIR_CURTAIN_STATE = rosetta_MDC_MICROENV_AIR_CURTAIN_STATE

rosetta_MDC_MICROENV_BED_STATE = "MDC_MICROENV_BED_STATE"

rosetta.MDC_MICROENV_BED_STATE = rosetta_MDC_MICROENV_BED_STATE

rosetta_MDC_MICROENV_FAN_SPEED = "MDC_MICROENV_FAN_SPEED"

rosetta.MDC_MICROENV_FAN_SPEED = rosetta_MDC_MICROENV_FAN_SPEED

rosetta_MDC_MICROENV_HEATER_TYPE = "MDC_MICROENV_HEATER_TYPE"

rosetta.MDC_MICROENV_HEATER_TYPE = rosetta_MDC_MICROENV_HEATER_TYPE

rosetta_MDC_MICROENV_TYPE = "MDC_MICROENV_TYPE"

rosetta.MDC_MICROENV_TYPE = rosetta_MDC_MICROENV_TYPE

rosetta_MDC_NUM_PATIENT_DOSES_ATTEMPTED_TOTAL = "MDC_NUM_PATIENT_DOSES_ATTEMPTED_TOTAL"

rosetta.MDC_NUM_PATIENT_DOSES_ATTEMPTED_TOTAL = rosetta_MDC_NUM_PATIENT_DOSES_ATTEMPTED_TOTAL

rosetta_MDC_NUM_PATIENT_DOSES_GIVEN_TOTAL = "MDC_NUM_PATIENT_DOSES_GIVEN_TOTAL"

rosetta.MDC_NUM_PATIENT_DOSES_GIVEN_TOTAL = rosetta_MDC_NUM_PATIENT_DOSES_GIVEN_TOTAL

rosetta_MDC_O2_EXTRACTION_RATIO = "MDC_O2_EXTRACTION_RATIO"

rosetta.MDC_O2_EXTRACTION_RATIO = rosetta_MDC_O2_EXTRACTION_RATIO

rosetta_MDC_O2_OXYGENATION_RATIO = "MDC_O2_OXYGENATION_RATIO"

rosetta.MDC_O2_OXYGENATION_RATIO = rosetta_MDC_O2_OXYGENATION_RATIO

rosetta_MDC_O2_TCUT = "MDC_O2_TCUT"

rosetta.MDC_O2_TCUT = rosetta_MDC_O2_TCUT

rosetta_MDC_OUTPUT_CARD = "MDC_OUTPUT_CARD"

rosetta.MDC_OUTPUT_CARD = rosetta_MDC_OUTPUT_CARD

rosetta_MDC_OUTPUT_CARDIAC_FICK = "MDC_OUTPUT_CARDIAC_FICK"

rosetta.MDC_OUTPUT_CARDIAC_FICK = rosetta_MDC_OUTPUT_CARDIAC_FICK

rosetta_MDC_OUTPUT_CARD_CTS = "MDC_OUTPUT_CARD_CTS"

rosetta.MDC_OUTPUT_CARD_CTS = rosetta_MDC_OUTPUT_CARD_CTS

rosetta_MDC_OUTPUT_CARD_INDEX = "MDC_OUTPUT_CARD_INDEX"

rosetta.MDC_OUTPUT_CARD_INDEX = rosetta_MDC_OUTPUT_CARD_INDEX

rosetta_MDC_OUTPUT_CARD_NONCTS = "MDC_OUTPUT_CARD_NONCTS"

rosetta.MDC_OUTPUT_CARD_NONCTS = rosetta_MDC_OUTPUT_CARD_NONCTS

rosetta_MDC_POWER_TCUT = "MDC_POWER_TCUT"

rosetta.MDC_POWER_TCUT = rosetta_MDC_POWER_TCUT

rosetta_MDC_PRESS_AIR_AMBIENT = "MDC_PRESS_AIR_AMBIENT"

rosetta.MDC_PRESS_AIR_AMBIENT = rosetta_MDC_PRESS_AIR_AMBIENT

rosetta_MDC_PRESS_AWAY = "MDC_PRESS_AWAY"

rosetta.MDC_PRESS_AWAY = rosetta_MDC_PRESS_AWAY

rosetta_MDC_PRESS_AWAY_CTS_POS = "MDC_PRESS_AWAY_CTS_POS"

rosetta.MDC_PRESS_AWAY_CTS_POS = rosetta_MDC_PRESS_AWAY_CTS_POS

rosetta_MDC_PRESS_AWAY_END_EXP_POS = "MDC_PRESS_AWAY_END_EXP_POS"

rosetta.MDC_PRESS_AWAY_END_EXP_POS = rosetta_MDC_PRESS_AWAY_END_EXP_POS

rosetta_MDC_PRESS_AWAY_END_EXP_POS_INTRINSIC = "MDC_PRESS_AWAY_END_EXP_POS_INTRINSIC"

rosetta.MDC_PRESS_AWAY_END_EXP_POS_INTRINSIC = rosetta_MDC_PRESS_AWAY_END_EXP_POS_INTRINSIC

rosetta_MDC_PRESS_AWAY_END_EXP_POS_STATIC_EXTRINSIC = "MDC_PRESS_AWAY_END_EXP_POS_STATIC_EXTRINSIC"

rosetta.MDC_PRESS_AWAY_END_EXP_POS_STATIC_EXTRINSIC = rosetta_MDC_PRESS_AWAY_END_EXP_POS_STATIC_EXTRINSIC

rosetta_MDC_PRESS_AWAY_END_EXP_POS_STATIC_INTRINSIC = "MDC_PRESS_AWAY_END_EXP_POS_STATIC_INTRINSIC"

rosetta.MDC_PRESS_AWAY_END_EXP_POS_STATIC_INTRINSIC = rosetta_MDC_PRESS_AWAY_END_EXP_POS_STATIC_INTRINSIC

rosetta_MDC_PRESS_AWAY_END_EXP_POS_STATIC_TOTAL = "MDC_PRESS_AWAY_END_EXP_POS_STATIC_TOTAL"

rosetta.MDC_PRESS_AWAY_END_EXP_POS_STATIC_TOTAL = rosetta_MDC_PRESS_AWAY_END_EXP_POS_STATIC_TOTAL

rosetta_MDC_PRESS_AWAY_INSP = "MDC_PRESS_AWAY_INSP"

rosetta.MDC_PRESS_AWAY_INSP = rosetta_MDC_PRESS_AWAY_INSP

rosetta_MDC_PRESS_AWAY_INSP_MAX = "MDC_PRESS_AWAY_INSP_MAX"

rosetta.MDC_PRESS_AWAY_INSP_MAX = rosetta_MDC_PRESS_AWAY_INSP_MAX

rosetta_MDC_PRESS_AWAY_INSP_MEAN = "MDC_PRESS_AWAY_INSP_MEAN"

rosetta.MDC_PRESS_AWAY_INSP_MEAN = rosetta_MDC_PRESS_AWAY_INSP_MEAN

rosetta_MDC_PRESS_AWAY_INSP_PEAK = "MDC_PRESS_AWAY_INSP_PEAK"

rosetta.MDC_PRESS_AWAY_INSP_PEAK = rosetta_MDC_PRESS_AWAY_INSP_PEAK

rosetta_MDC_PRESS_AWAY_MIN = "MDC_PRESS_AWAY_MIN"

rosetta.MDC_PRESS_AWAY_MIN = rosetta_MDC_PRESS_AWAY_MIN

rosetta_MDC_PRESS_AWAY_NEG_MAX = "MDC_PRESS_AWAY_NEG_MAX"

rosetta.MDC_PRESS_AWAY_NEG_MAX = rosetta_MDC_PRESS_AWAY_NEG_MAX

rosetta_MDC_PRESS_BAROMETRIC = "MDC_PRESS_BAROMETRIC"

rosetta.MDC_PRESS_BAROMETRIC = rosetta_MDC_PRESS_BAROMETRIC

rosetta_MDC_PRESS_BLD = "MDC_PRESS_BLD"

rosetta.MDC_PRESS_BLD = rosetta_MDC_PRESS_BLD

rosetta_MDC_PRESS_BLD_AORT = "MDC_PRESS_BLD_AORT"

rosetta.MDC_PRESS_BLD_AORT = rosetta_MDC_PRESS_BLD_AORT

rosetta_MDC_PRESS_BLD_AORT_DIA = "MDC_PRESS_BLD_AORT_DIA"

rosetta.MDC_PRESS_BLD_AORT_DIA = rosetta_MDC_PRESS_BLD_AORT_DIA

rosetta_MDC_PRESS_BLD_AORT_MEAN = "MDC_PRESS_BLD_AORT_MEAN"

rosetta.MDC_PRESS_BLD_AORT_MEAN = rosetta_MDC_PRESS_BLD_AORT_MEAN

rosetta_MDC_PRESS_BLD_AORT_SYS = "MDC_PRESS_BLD_AORT_SYS"

rosetta.MDC_PRESS_BLD_AORT_SYS = rosetta_MDC_PRESS_BLD_AORT_SYS

rosetta_MDC_PRESS_BLD_ART = "MDC_PRESS_BLD_ART"

rosetta.MDC_PRESS_BLD_ART = rosetta_MDC_PRESS_BLD_ART

rosetta_MDC_PRESS_BLD_ART_ABP = "MDC_PRESS_BLD_ART_ABP"

rosetta.MDC_PRESS_BLD_ART_ABP = rosetta_MDC_PRESS_BLD_ART_ABP

rosetta_MDC_PRESS_BLD_ART_ABP_DIA = "MDC_PRESS_BLD_ART_ABP_DIA"

rosetta.MDC_PRESS_BLD_ART_ABP_DIA = rosetta_MDC_PRESS_BLD_ART_ABP_DIA

rosetta_MDC_PRESS_BLD_ART_ABP_MEAN = "MDC_PRESS_BLD_ART_ABP_MEAN"

rosetta.MDC_PRESS_BLD_ART_ABP_MEAN = rosetta_MDC_PRESS_BLD_ART_ABP_MEAN

rosetta_MDC_PRESS_BLD_ART_ABP_SYS = "MDC_PRESS_BLD_ART_ABP_SYS"

rosetta.MDC_PRESS_BLD_ART_ABP_SYS = rosetta_MDC_PRESS_BLD_ART_ABP_SYS

rosetta_MDC_PRESS_BLD_ART_DIA = "MDC_PRESS_BLD_ART_DIA"

rosetta.MDC_PRESS_BLD_ART_DIA = rosetta_MDC_PRESS_BLD_ART_DIA

rosetta_MDC_PRESS_BLD_ART_FEMORAL = "MDC_PRESS_BLD_ART_FEMORAL"

rosetta.MDC_PRESS_BLD_ART_FEMORAL = rosetta_MDC_PRESS_BLD_ART_FEMORAL

rosetta_MDC_PRESS_BLD_ART_FEMORAL_DIA = "MDC_PRESS_BLD_ART_FEMORAL_DIA"

rosetta.MDC_PRESS_BLD_ART_FEMORAL_DIA = rosetta_MDC_PRESS_BLD_ART_FEMORAL_DIA

rosetta_MDC_PRESS_BLD_ART_FEMORAL_MEAN = "MDC_PRESS_BLD_ART_FEMORAL_MEAN"

rosetta.MDC_PRESS_BLD_ART_FEMORAL_MEAN = rosetta_MDC_PRESS_BLD_ART_FEMORAL_MEAN

rosetta_MDC_PRESS_BLD_ART_FEMORAL_SYS = "MDC_PRESS_BLD_ART_FEMORAL_SYS"

rosetta.MDC_PRESS_BLD_ART_FEMORAL_SYS = rosetta_MDC_PRESS_BLD_ART_FEMORAL_SYS

rosetta_MDC_PRESS_BLD_ART_MEAN = "MDC_PRESS_BLD_ART_MEAN"

rosetta.MDC_PRESS_BLD_ART_MEAN = rosetta_MDC_PRESS_BLD_ART_MEAN

rosetta_MDC_PRESS_BLD_ART_PULM = "MDC_PRESS_BLD_ART_PULM"

rosetta.MDC_PRESS_BLD_ART_PULM = rosetta_MDC_PRESS_BLD_ART_PULM

rosetta_MDC_PRESS_BLD_ART_PULM_DIA = "MDC_PRESS_BLD_ART_PULM_DIA"

rosetta.MDC_PRESS_BLD_ART_PULM_DIA = rosetta_MDC_PRESS_BLD_ART_PULM_DIA

rosetta_MDC_PRESS_BLD_ART_PULM_MEAN = "MDC_PRESS_BLD_ART_PULM_MEAN"

rosetta.MDC_PRESS_BLD_ART_PULM_MEAN = rosetta_MDC_PRESS_BLD_ART_PULM_MEAN

rosetta_MDC_PRESS_BLD_ART_PULM_OCCL = "MDC_PRESS_BLD_ART_PULM_OCCL"

rosetta.MDC_PRESS_BLD_ART_PULM_OCCL = rosetta_MDC_PRESS_BLD_ART_PULM_OCCL

rosetta_MDC_PRESS_BLD_ART_PULM_SYS = "MDC_PRESS_BLD_ART_PULM_SYS"

rosetta.MDC_PRESS_BLD_ART_PULM_SYS = rosetta_MDC_PRESS_BLD_ART_PULM_SYS

rosetta_MDC_PRESS_BLD_ART_PULM_WEDGE = "MDC_PRESS_BLD_ART_PULM_WEDGE"

rosetta.MDC_PRESS_BLD_ART_PULM_WEDGE = rosetta_MDC_PRESS_BLD_ART_PULM_WEDGE

rosetta_MDC_PRESS_BLD_ART_SYS = "MDC_PRESS_BLD_ART_SYS"

rosetta.MDC_PRESS_BLD_ART_SYS = rosetta_MDC_PRESS_BLD_ART_SYS

rosetta_MDC_PRESS_BLD_ART_UMB = "MDC_PRESS_BLD_ART_UMB"

rosetta.MDC_PRESS_BLD_ART_UMB = rosetta_MDC_PRESS_BLD_ART_UMB

rosetta_MDC_PRESS_BLD_ART_UMB_DIA = "MDC_PRESS_BLD_ART_UMB_DIA"

rosetta.MDC_PRESS_BLD_ART_UMB_DIA = rosetta_MDC_PRESS_BLD_ART_UMB_DIA

rosetta_MDC_PRESS_BLD_ART_UMB_MEAN = "MDC_PRESS_BLD_ART_UMB_MEAN"

rosetta.MDC_PRESS_BLD_ART_UMB_MEAN = rosetta_MDC_PRESS_BLD_ART_UMB_MEAN

rosetta_MDC_PRESS_BLD_ART_UMB_SYS = "MDC_PRESS_BLD_ART_UMB_SYS"

rosetta.MDC_PRESS_BLD_ART_UMB_SYS = rosetta_MDC_PRESS_BLD_ART_UMB_SYS

rosetta_MDC_PRESS_BLD_ATR_LEFT = "MDC_PRESS_BLD_ATR_LEFT"

rosetta.MDC_PRESS_BLD_ATR_LEFT = rosetta_MDC_PRESS_BLD_ATR_LEFT

rosetta_MDC_PRESS_BLD_ATR_LEFT_DIA = "MDC_PRESS_BLD_ATR_LEFT_DIA"

rosetta.MDC_PRESS_BLD_ATR_LEFT_DIA = rosetta_MDC_PRESS_BLD_ATR_LEFT_DIA

rosetta_MDC_PRESS_BLD_ATR_LEFT_MEAN = "MDC_PRESS_BLD_ATR_LEFT_MEAN"

rosetta.MDC_PRESS_BLD_ATR_LEFT_MEAN = rosetta_MDC_PRESS_BLD_ATR_LEFT_MEAN

rosetta_MDC_PRESS_BLD_ATR_LEFT_SYS = "MDC_PRESS_BLD_ATR_LEFT_SYS"

rosetta.MDC_PRESS_BLD_ATR_LEFT_SYS = rosetta_MDC_PRESS_BLD_ATR_LEFT_SYS

rosetta_MDC_PRESS_BLD_ATR_RIGHT = "MDC_PRESS_BLD_ATR_RIGHT"

rosetta.MDC_PRESS_BLD_ATR_RIGHT = rosetta_MDC_PRESS_BLD_ATR_RIGHT

rosetta_MDC_PRESS_BLD_ATR_RIGHT_DIA = "MDC_PRESS_BLD_ATR_RIGHT_DIA"

rosetta.MDC_PRESS_BLD_ATR_RIGHT_DIA = rosetta_MDC_PRESS_BLD_ATR_RIGHT_DIA

rosetta_MDC_PRESS_BLD_ATR_RIGHT_MEAN = "MDC_PRESS_BLD_ATR_RIGHT_MEAN"

rosetta.MDC_PRESS_BLD_ATR_RIGHT_MEAN = rosetta_MDC_PRESS_BLD_ATR_RIGHT_MEAN

rosetta_MDC_PRESS_BLD_ATR_RIGHT_SYS = "MDC_PRESS_BLD_ATR_RIGHT_SYS"

rosetta.MDC_PRESS_BLD_ATR_RIGHT_SYS = rosetta_MDC_PRESS_BLD_ATR_RIGHT_SYS

rosetta_MDC_PRESS_BLD_DIA = "MDC_PRESS_BLD_DIA"

rosetta.MDC_PRESS_BLD_DIA = rosetta_MDC_PRESS_BLD_DIA

rosetta_MDC_PRESS_BLD_MEAN = "MDC_PRESS_BLD_MEAN"

rosetta.MDC_PRESS_BLD_MEAN = rosetta_MDC_PRESS_BLD_MEAN

rosetta_MDC_PRESS_BLD_NONINV = "MDC_PRESS_BLD_NONINV"

rosetta.MDC_PRESS_BLD_NONINV = rosetta_MDC_PRESS_BLD_NONINV

rosetta_MDC_PRESS_BLD_NONINV_DIA = "MDC_PRESS_BLD_NONINV_DIA"

rosetta.MDC_PRESS_BLD_NONINV_DIA = rosetta_MDC_PRESS_BLD_NONINV_DIA

rosetta_MDC_PRESS_BLD_NONINV_DIA_CTS = "MDC_PRESS_BLD_NONINV_DIA_CTS"

rosetta.MDC_PRESS_BLD_NONINV_DIA_CTS = rosetta_MDC_PRESS_BLD_NONINV_DIA_CTS

rosetta_MDC_PRESS_BLD_NONINV_MEAN = "MDC_PRESS_BLD_NONINV_MEAN"

rosetta.MDC_PRESS_BLD_NONINV_MEAN = rosetta_MDC_PRESS_BLD_NONINV_MEAN

rosetta_MDC_PRESS_BLD_NONINV_MEAN_CTS = "MDC_PRESS_BLD_NONINV_MEAN_CTS"

rosetta.MDC_PRESS_BLD_NONINV_MEAN_CTS = rosetta_MDC_PRESS_BLD_NONINV_MEAN_CTS

rosetta_MDC_PRESS_BLD_NONINV_SYS = "MDC_PRESS_BLD_NONINV_SYS"

rosetta.MDC_PRESS_BLD_NONINV_SYS = rosetta_MDC_PRESS_BLD_NONINV_SYS

rosetta_MDC_PRESS_BLD_NONINV_SYS_CTS = "MDC_PRESS_BLD_NONINV_SYS_CTS"

rosetta.MDC_PRESS_BLD_NONINV_SYS_CTS = rosetta_MDC_PRESS_BLD_NONINV_SYS_CTS

rosetta_MDC_PRESS_BLD_PULM_CAP = "MDC_PRESS_BLD_PULM_CAP"

rosetta.MDC_PRESS_BLD_PULM_CAP = rosetta_MDC_PRESS_BLD_PULM_CAP

rosetta_MDC_PRESS_BLD_PULM_CAP_DIA = "MDC_PRESS_BLD_PULM_CAP_DIA"

rosetta.MDC_PRESS_BLD_PULM_CAP_DIA = rosetta_MDC_PRESS_BLD_PULM_CAP_DIA

rosetta_MDC_PRESS_BLD_PULM_CAP_MEAN = "MDC_PRESS_BLD_PULM_CAP_MEAN"

rosetta.MDC_PRESS_BLD_PULM_CAP_MEAN = rosetta_MDC_PRESS_BLD_PULM_CAP_MEAN

rosetta_MDC_PRESS_BLD_PULM_CAP_SYS = "MDC_PRESS_BLD_PULM_CAP_SYS"

rosetta.MDC_PRESS_BLD_PULM_CAP_SYS = rosetta_MDC_PRESS_BLD_PULM_CAP_SYS

rosetta_MDC_PRESS_BLD_SYS = "MDC_PRESS_BLD_SYS"

rosetta.MDC_PRESS_BLD_SYS = rosetta_MDC_PRESS_BLD_SYS

rosetta_MDC_PRESS_BLD_VENT_LEFT_DIA = "MDC_PRESS_BLD_VENT_LEFT_DIA"

rosetta.MDC_PRESS_BLD_VENT_LEFT_DIA = rosetta_MDC_PRESS_BLD_VENT_LEFT_DIA

rosetta_MDC_PRESS_BLD_VENT_LEFT_MEAN = "MDC_PRESS_BLD_VENT_LEFT_MEAN"

rosetta.MDC_PRESS_BLD_VENT_LEFT_MEAN = rosetta_MDC_PRESS_BLD_VENT_LEFT_MEAN

rosetta_MDC_PRESS_BLD_VENT_LEFT_SYS = "MDC_PRESS_BLD_VENT_LEFT_SYS"

rosetta.MDC_PRESS_BLD_VENT_LEFT_SYS = rosetta_MDC_PRESS_BLD_VENT_LEFT_SYS

rosetta_MDC_PRESS_BLD_VENT_RIGHT_DIA = "MDC_PRESS_BLD_VENT_RIGHT_DIA"

rosetta.MDC_PRESS_BLD_VENT_RIGHT_DIA = rosetta_MDC_PRESS_BLD_VENT_RIGHT_DIA

rosetta_MDC_PRESS_BLD_VENT_RIGHT_MEAN = "MDC_PRESS_BLD_VENT_RIGHT_MEAN"

rosetta.MDC_PRESS_BLD_VENT_RIGHT_MEAN = rosetta_MDC_PRESS_BLD_VENT_RIGHT_MEAN

rosetta_MDC_PRESS_BLD_VENT_RIGHT_SYS = "MDC_PRESS_BLD_VENT_RIGHT_SYS"

rosetta.MDC_PRESS_BLD_VENT_RIGHT_SYS = rosetta_MDC_PRESS_BLD_VENT_RIGHT_SYS

rosetta_MDC_PRESS_BLD_VEN_CENT = "MDC_PRESS_BLD_VEN_CENT"

rosetta.MDC_PRESS_BLD_VEN_CENT = rosetta_MDC_PRESS_BLD_VEN_CENT

rosetta_MDC_PRESS_BLD_VEN_CENT_DIA = "MDC_PRESS_BLD_VEN_CENT_DIA"

rosetta.MDC_PRESS_BLD_VEN_CENT_DIA = rosetta_MDC_PRESS_BLD_VEN_CENT_DIA

rosetta_MDC_PRESS_BLD_VEN_CENT_MEAN = "MDC_PRESS_BLD_VEN_CENT_MEAN"

rosetta.MDC_PRESS_BLD_VEN_CENT_MEAN = rosetta_MDC_PRESS_BLD_VEN_CENT_MEAN

rosetta_MDC_PRESS_BLD_VEN_CENT_SYS = "MDC_PRESS_BLD_VEN_CENT_SYS"

rosetta.MDC_PRESS_BLD_VEN_CENT_SYS = rosetta_MDC_PRESS_BLD_VEN_CENT_SYS

rosetta_MDC_PRESS_BLD_VEN_UMB = "MDC_PRESS_BLD_VEN_UMB"

rosetta.MDC_PRESS_BLD_VEN_UMB = rosetta_MDC_PRESS_BLD_VEN_UMB

rosetta_MDC_PRESS_BLD_VEN_UMB_DIA = "MDC_PRESS_BLD_VEN_UMB_DIA"

rosetta.MDC_PRESS_BLD_VEN_UMB_DIA = rosetta_MDC_PRESS_BLD_VEN_UMB_DIA

rosetta_MDC_PRESS_BLD_VEN_UMB_MEAN = "MDC_PRESS_BLD_VEN_UMB_MEAN"

rosetta.MDC_PRESS_BLD_VEN_UMB_MEAN = rosetta_MDC_PRESS_BLD_VEN_UMB_MEAN

rosetta_MDC_PRESS_BLD_VEN_UMB_SYS = "MDC_PRESS_BLD_VEN_UMB_SYS"

rosetta.MDC_PRESS_BLD_VEN_UMB_SYS = rosetta_MDC_PRESS_BLD_VEN_UMB_SYS

rosetta_MDC_PRESS_CEREB_PERF = "MDC_PRESS_CEREB_PERF"

rosetta.MDC_PRESS_CEREB_PERF = rosetta_MDC_PRESS_CEREB_PERF

rosetta_MDC_PRESS_CUFF = "MDC_PRESS_CUFF"

rosetta.MDC_PRESS_CUFF = rosetta_MDC_PRESS_CUFF

rosetta_MDC_PRESS_CUFF_DIA = "MDC_PRESS_CUFF_DIA"

rosetta.MDC_PRESS_CUFF_DIA = rosetta_MDC_PRESS_CUFF_DIA

rosetta_MDC_PRESS_CUFF_MEAN = "MDC_PRESS_CUFF_MEAN"

rosetta.MDC_PRESS_CUFF_MEAN = rosetta_MDC_PRESS_CUFF_MEAN

rosetta_MDC_PRESS_CUFF_SYS = "MDC_PRESS_CUFF_SYS"

rosetta.MDC_PRESS_CUFF_SYS = rosetta_MDC_PRESS_CUFF_SYS

rosetta_MDC_PRESS_ESOPH = "MDC_PRESS_ESOPH"

rosetta.MDC_PRESS_ESOPH = rosetta_MDC_PRESS_ESOPH

rosetta_MDC_PRESS_GI = "MDC_PRESS_GI"

rosetta.MDC_PRESS_GI = rosetta_MDC_PRESS_GI

rosetta_MDC_PRESS_INTRA_CRAN = "MDC_PRESS_INTRA_CRAN"

rosetta.MDC_PRESS_INTRA_CRAN = rosetta_MDC_PRESS_INTRA_CRAN

rosetta_MDC_PRESS_INTRA_CRAN_DIA = "MDC_PRESS_INTRA_CRAN_DIA"

rosetta.MDC_PRESS_INTRA_CRAN_DIA = rosetta_MDC_PRESS_INTRA_CRAN_DIA

rosetta_MDC_PRESS_INTRA_CRAN_MEAN = "MDC_PRESS_INTRA_CRAN_MEAN"

rosetta.MDC_PRESS_INTRA_CRAN_MEAN = rosetta_MDC_PRESS_INTRA_CRAN_MEAN

rosetta_MDC_PRESS_INTRA_CRAN_SYS = "MDC_PRESS_INTRA_CRAN_SYS"

rosetta.MDC_PRESS_INTRA_CRAN_SYS = rosetta_MDC_PRESS_INTRA_CRAN_SYS

rosetta_MDC_PRESS_RESP_PAUSE = "MDC_PRESS_RESP_PAUSE"

rosetta.MDC_PRESS_RESP_PAUSE = rosetta_MDC_PRESS_RESP_PAUSE

rosetta_MDC_PRESS_RESP_PLAT = "MDC_PRESS_RESP_PLAT"

rosetta.MDC_PRESS_RESP_PLAT = rosetta_MDC_PRESS_RESP_PLAT

rosetta_MDC_PRESS_RESP_PLAT_DYNAMIC = "MDC_PRESS_RESP_PLAT_DYNAMIC"

rosetta.MDC_PRESS_RESP_PLAT_DYNAMIC = rosetta_MDC_PRESS_RESP_PLAT_DYNAMIC

rosetta_MDC_PRESS_RESP_PLAT_STATIC = "MDC_PRESS_RESP_PLAT_STATIC"

rosetta.MDC_PRESS_RESP_PLAT_STATIC = rosetta_MDC_PRESS_RESP_PLAT_STATIC

rosetta_MDC_PRES_AWAY_END_EXP_POS = "MDC_PRES_AWAY_END_EXP_POS"

rosetta.MDC_PRES_AWAY_END_EXP_POS = rosetta_MDC_PRES_AWAY_END_EXP_POS

rosetta_MDC_PULS_OXIM_PERF_REL = "MDC_PULS_OXIM_PERF_REL"

rosetta.MDC_PULS_OXIM_PERF_REL = rosetta_MDC_PULS_OXIM_PERF_REL

rosetta_MDC_PULS_OXIM_PLETH = "MDC_PULS_OXIM_PLETH"

rosetta.MDC_PULS_OXIM_PLETH = rosetta_MDC_PULS_OXIM_PLETH

rosetta_MDC_PULS_OXIM_PULS_RATE = "MDC_PULS_OXIM_PULS_RATE"

rosetta.MDC_PULS_OXIM_PULS_RATE = rosetta_MDC_PULS_OXIM_PULS_RATE

rosetta_MDC_PULS_OXIM_SAT_O2 = "MDC_PULS_OXIM_SAT_O2"

rosetta.MDC_PULS_OXIM_SAT_O2 = rosetta_MDC_PULS_OXIM_SAT_O2

rosetta_MDC_PULS_OXIM_SAT_O2_ART_LEFT = "MDC_PULS_OXIM_SAT_O2_ART_LEFT"

rosetta.MDC_PULS_OXIM_SAT_O2_ART_LEFT = rosetta_MDC_PULS_OXIM_SAT_O2_ART_LEFT

rosetta_MDC_PULS_OXIM_SAT_O2_ART_RIGHT = "MDC_PULS_OXIM_SAT_O2_ART_RIGHT"

rosetta.MDC_PULS_OXIM_SAT_O2_ART_RIGHT = rosetta_MDC_PULS_OXIM_SAT_O2_ART_RIGHT

rosetta_MDC_PULS_OXIM_SAT_O2_DIFF = "MDC_PULS_OXIM_SAT_O2_DIFF"

rosetta.MDC_PULS_OXIM_SAT_O2_DIFF = rosetta_MDC_PULS_OXIM_SAT_O2_DIFF

rosetta_MDC_PULS_RATE = "MDC_PULS_RATE"

rosetta.MDC_PULS_RATE = rosetta_MDC_PULS_RATE

rosetta_MDC_PULS_RATE_NON_INV = "MDC_PULS_RATE_NON_INV"

rosetta.MDC_PULS_RATE_NON_INV = rosetta_MDC_PULS_RATE_NON_INV

rosetta_MDC_PUMP_DRUG_LIBRARY_CARE_AREA = "MDC_PUMP_DRUG_LIBRARY_CARE_AREA"

rosetta.MDC_PUMP_DRUG_LIBRARY_CARE_AREA = rosetta_MDC_PUMP_DRUG_LIBRARY_CARE_AREA

rosetta_MDC_PUMP_DRUG_LIBRARY_VERSION = "MDC_PUMP_DRUG_LIBRARY_VERSION"

rosetta.MDC_PUMP_DRUG_LIBRARY_VERSION = rosetta_MDC_PUMP_DRUG_LIBRARY_VERSION

rosetta_MDC_PUMP_INFUSING_STATUS = "MDC_PUMP_INFUSING_STATUS"

rosetta.MDC_PUMP_INFUSING_STATUS = rosetta_MDC_PUMP_INFUSING_STATUS

rosetta_MDC_PUMP_MODE = "MDC_PUMP_MODE"

rosetta.MDC_PUMP_MODE = rosetta_MDC_PUMP_MODE

rosetta_MDC_PUMP_MODE_CONCURRENT_CHAN_LABEL = "MDC_PUMP_MODE_CONCURRENT_CHAN_LABEL"

rosetta.MDC_PUMP_MODE_CONCURRENT_CHAN_LABEL = rosetta_MDC_PUMP_MODE_CONCURRENT_CHAN_LABEL

rosetta_MDC_PUMP_MODE_CURRENT = "MDC_PUMP_MODE_CURRENT"

rosetta.MDC_PUMP_MODE_CURRENT = rosetta_MDC_PUMP_MODE_CURRENT

rosetta_MDC_PUMP_MODE_SET = "MDC_PUMP_MODE_SET"

rosetta.MDC_PUMP_MODE_SET = rosetta_MDC_PUMP_MODE_SET

rosetta_MDC_PUMP_NOT_INFUSING_REASON = "MDC_PUMP_NOT_INFUSING_REASON"

rosetta.MDC_PUMP_NOT_INFUSING_REASON = rosetta_MDC_PUMP_NOT_INFUSING_REASON

rosetta_MDC_PUMP_STAT = "MDC_PUMP_STAT"

rosetta.MDC_PUMP_STAT = rosetta_MDC_PUMP_STAT

rosetta_MDC_QUO_RESP = "MDC_QUO_RESP"

rosetta.MDC_QUO_RESP = rosetta_MDC_QUO_RESP

rosetta_MDC_RATE_DOSE = "MDC_RATE_DOSE"

rosetta.MDC_RATE_DOSE = rosetta_MDC_RATE_DOSE

rosetta_MDC_RATE_PCA_MAX_DOSES_PER_HOUR = "MDC_RATE_PCA_MAX_DOSES_PER_HOUR"

rosetta.MDC_RATE_PCA_MAX_DOSES_PER_HOUR = rosetta_MDC_RATE_PCA_MAX_DOSES_PER_HOUR

rosetta_MDC_RATIO_AWAY_DEADSP_TIDAL = "MDC_RATIO_AWAY_DEADSP_TIDAL"

rosetta.MDC_RATIO_AWAY_DEADSP_TIDAL = rosetta_MDC_RATIO_AWAY_DEADSP_TIDAL

rosetta_MDC_RATIO_IE = "MDC_RATIO_IE"

rosetta.MDC_RATIO_IE = rosetta_MDC_RATIO_IE

rosetta_MDC_RATIO_INSP = "MDC_RATIO_INSP"

rosetta.MDC_RATIO_INSP = rosetta_MDC_RATIO_INSP

rosetta_MDC_REL_HUMIDITY_MICROENV = "MDC_REL_HUMIDITY_MICROENV"

rosetta.MDC_REL_HUMIDITY_MICROENV = rosetta_MDC_REL_HUMIDITY_MICROENV

rosetta_MDC_REL_HUMIDITY_MICROENV_SETTING = "MDC_REL_HUMIDITY_MICROENV_SETTING"

rosetta.MDC_REL_HUMIDITY_MICROENV_SETTING = rosetta_MDC_REL_HUMIDITY_MICROENV_SETTING

rosetta_MDC_RESP = "MDC_RESP"

rosetta.MDC_RESP = rosetta_MDC_RESP

rosetta_MDC_RESP_EXPENDED_ENERGY = "MDC_RESP_EXPENDED_ENERGY"

rosetta.MDC_RESP_EXPENDED_ENERGY = rosetta_MDC_RESP_EXPENDED_ENERGY

rosetta_MDC_RESP_RATE = "MDC_RESP_RATE"

rosetta.MDC_RESP_RATE = rosetta_MDC_RESP_RATE

rosetta_MDC_RESP_RATE_SPONT = "MDC_RESP_RATE_SPONT"

rosetta.MDC_RESP_RATE_SPONT = rosetta_MDC_RESP_RATE_SPONT

rosetta_MDC_RESPMDC_RESP_RATE = "MDC_RESPMDC_RESP_RATE"

rosetta.MDC_RESPMDC_RESP_RATE = rosetta_MDC_RESPMDC_RESP_RATE

rosetta_MDC_RES_AWAY = "MDC_RES_AWAY"

rosetta.MDC_RES_AWAY = rosetta_MDC_RES_AWAY

rosetta_MDC_RES_AWAY_EXP = "MDC_RES_AWAY_EXP"

rosetta.MDC_RES_AWAY_EXP = rosetta_MDC_RES_AWAY_EXP

rosetta_MDC_RES_AWAY_INSP = "MDC_RES_AWAY_INSP"

rosetta.MDC_RES_AWAY_INSP = rosetta_MDC_RES_AWAY_INSP

rosetta_MDC_RES_VASC = "MDC_RES_VASC"

rosetta.MDC_RES_VASC = rosetta_MDC_RES_VASC

rosetta_MDC_RES_VASC_PULM = "MDC_RES_VASC_PULM"

rosetta.MDC_RES_VASC_PULM = rosetta_MDC_RES_VASC_PULM

rosetta_MDC_RES_VASC_PULM_INDEX = "MDC_RES_VASC_PULM_INDEX"

rosetta.MDC_RES_VASC_PULM_INDEX = rosetta_MDC_RES_VASC_PULM_INDEX

rosetta_MDC_RES_VASC_SYS = "MDC_RES_VASC_SYS"

rosetta.MDC_RES_VASC_SYS = rosetta_MDC_RES_VASC_SYS

rosetta_MDC_RES_VASC_SYS_INDEX = "MDC_RES_VASC_SYS_INDEX"

rosetta.MDC_RES_VASC_SYS_INDEX = rosetta_MDC_RES_VASC_SYS_INDEX

rosetta_MDC_SAT_DIFF_O2_ART_ALV = "MDC_SAT_DIFF_O2_ART_ALV"

rosetta.MDC_SAT_DIFF_O2_ART_ALV = rosetta_MDC_SAT_DIFF_O2_ART_ALV

rosetta_MDC_SAT_O2_ART = "MDC_SAT_O2_ART"

rosetta.MDC_SAT_O2_ART = rosetta_MDC_SAT_O2_ART

rosetta_MDC_SAT_O2_CONSUMP = "MDC_SAT_O2_CONSUMP"

rosetta.MDC_SAT_O2_CONSUMP = rosetta_MDC_SAT_O2_CONSUMP

rosetta_MDC_SAT_O2_CONSUMP_INDEX = "MDC_SAT_O2_CONSUMP_INDEX"

rosetta.MDC_SAT_O2_CONSUMP_INDEX = rosetta_MDC_SAT_O2_CONSUMP_INDEX

rosetta_MDC_SAT_O2_DELIV_INDEX = "MDC_SAT_O2_DELIV_INDEX"

rosetta.MDC_SAT_O2_DELIV_INDEX = rosetta_MDC_SAT_O2_DELIV_INDEX

rosetta_MDC_SAT_O2_VEN = "MDC_SAT_O2_VEN"

rosetta.MDC_SAT_O2_VEN = rosetta_MDC_SAT_O2_VEN

rosetta_MDC_SCORE_EYE_SUBSC_GLAS_COMA = "MDC_SCORE_EYE_SUBSC_GLAS_COMA"

rosetta.MDC_SCORE_EYE_SUBSC_GLAS_COMA = rosetta_MDC_SCORE_EYE_SUBSC_GLAS_COMA

rosetta_MDC_SCORE_GLAS_COMA = "MDC_SCORE_GLAS_COMA"

rosetta.MDC_SCORE_GLAS_COMA = rosetta_MDC_SCORE_GLAS_COMA

rosetta_MDC_SCORE_MOTOR_SUBSC_GLAS_COMA = "MDC_SCORE_MOTOR_SUBSC_GLAS_COMA"

rosetta.MDC_SCORE_MOTOR_SUBSC_GLAS_COMA = rosetta_MDC_SCORE_MOTOR_SUBSC_GLAS_COMA

rosetta_MDC_SCORE_SUBSC_VERBAL_GLAS_COMA = "MDC_SCORE_SUBSC_VERBAL_GLAS_COMA"

rosetta.MDC_SCORE_SUBSC_VERBAL_GLAS_COMA = rosetta_MDC_SCORE_SUBSC_VERBAL_GLAS_COMA

rosetta_MDC_SYRINGE_MANUFACTURER = "MDC_SYRINGE_MANUFACTURER"

rosetta.MDC_SYRINGE_MANUFACTURER = rosetta_MDC_SYRINGE_MANUFACTURER

rosetta_MDC_SYSTOLIC_TIME_RATIO = "MDC_SYSTOLIC_TIME_RATIO"

rosetta.MDC_SYSTOLIC_TIME_RATIO = rosetta_MDC_SYSTOLIC_TIME_RATIO

rosetta_MDC_TEMP = "MDC_TEMP"

rosetta.MDC_TEMP = rosetta_MDC_TEMP

rosetta_MDC_TEMP_ART = "MDC_TEMP_ART"

rosetta.MDC_TEMP_ART = rosetta_MDC_TEMP_ART

rosetta_MDC_TEMP_AWAY = "MDC_TEMP_AWAY"

rosetta.MDC_TEMP_AWAY = rosetta_MDC_TEMP_AWAY

rosetta_MDC_TEMP_AXIL = "MDC_TEMP_AXIL"

rosetta.MDC_TEMP_AXIL = rosetta_MDC_TEMP_AXIL

rosetta_MDC_TEMP_BLD = "MDC_TEMP_BLD"

rosetta.MDC_TEMP_BLD = rosetta_MDC_TEMP_BLD

rosetta_MDC_TEMP_BODY = "MDC_TEMP_BODY"

rosetta.MDC_TEMP_BODY = rosetta_MDC_TEMP_BODY

rosetta_MDC_TEMP_CORE = "MDC_TEMP_CORE"

rosetta.MDC_TEMP_CORE = rosetta_MDC_TEMP_CORE

rosetta_MDC_TEMP_DIFF = "MDC_TEMP_DIFF"

rosetta.MDC_TEMP_DIFF = rosetta_MDC_TEMP_DIFF

rosetta_MDC_TEMP_EAR = "MDC_TEMP_EAR"

rosetta.MDC_TEMP_EAR = rosetta_MDC_TEMP_EAR

rosetta_MDC_TEMP_ESOPH = "MDC_TEMP_ESOPH"

rosetta.MDC_TEMP_ESOPH = rosetta_MDC_TEMP_ESOPH

rosetta_MDC_TEMP_FINGER = "MDC_TEMP_FINGER"

rosetta.MDC_TEMP_FINGER = rosetta_MDC_TEMP_FINGER

rosetta_MDC_TEMP_FOLEY = "MDC_TEMP_FOLEY"

rosetta.MDC_TEMP_FOLEY = rosetta_MDC_TEMP_FOLEY

rosetta_MDC_TEMP_INJ = "MDC_TEMP_INJ"

rosetta.MDC_TEMP_INJ = rosetta_MDC_TEMP_INJ

rosetta_MDC_TEMP_MICROENV = "MDC_TEMP_MICROENV"

rosetta.MDC_TEMP_MICROENV = rosetta_MDC_TEMP_MICROENV

rosetta_MDC_TEMP_MICROENV_SETTING = "MDC_TEMP_MICROENV_SETTING"

rosetta.MDC_TEMP_MICROENV_SETTING = rosetta_MDC_TEMP_MICROENV_SETTING

rosetta_MDC_TEMP_MYO = "MDC_TEMP_MYO"

rosetta.MDC_TEMP_MYO = rosetta_MDC_TEMP_MYO

rosetta_MDC_TEMP_NASAL = "MDC_TEMP_NASAL"

rosetta.MDC_TEMP_NASAL = rosetta_MDC_TEMP_NASAL

rosetta_MDC_TEMP_NASOPH = "MDC_TEMP_NASOPH"

rosetta.MDC_TEMP_NASOPH = rosetta_MDC_TEMP_NASOPH

rosetta_MDC_TEMP_ORAL = "MDC_TEMP_ORAL"

rosetta.MDC_TEMP_ORAL = rosetta_MDC_TEMP_ORAL

rosetta_MDC_TEMP_RECT = "MDC_TEMP_RECT"

rosetta.MDC_TEMP_RECT = rosetta_MDC_TEMP_RECT

rosetta_MDC_TEMP_ROOM = "MDC_TEMP_ROOM"

rosetta.MDC_TEMP_ROOM = rosetta_MDC_TEMP_ROOM

rosetta_MDC_TEMP_SKIN = "MDC_TEMP_SKIN"

rosetta.MDC_TEMP_SKIN = rosetta_MDC_TEMP_SKIN

rosetta_MDC_TEMP_SKIN_SETTING = "MDC_TEMP_SKIN_SETTING"

rosetta.MDC_TEMP_SKIN_SETTING = rosetta_MDC_TEMP_SKIN_SETTING

rosetta_MDC_TEMP_TCUT = "MDC_TEMP_TCUT"

rosetta.MDC_TEMP_TCUT = rosetta_MDC_TEMP_TCUT

rosetta_MDC_TEMP_TOE = "MDC_TEMP_TOE"

rosetta.MDC_TEMP_TOE = rosetta_MDC_TEMP_TOE

rosetta_MDC_TEMP_TYMP = "MDC_TEMP_TYMP"

rosetta.MDC_TEMP_TYMP = rosetta_MDC_TEMP_TYMP

rosetta_MDC_TEMP_VEN = "MDC_TEMP_VEN"

rosetta.MDC_TEMP_VEN = rosetta_MDC_TEMP_VEN

rosetta_MDC_THORACIC_FLUID_CONTENT = "MDC_THORACIC_FLUID_CONTENT"

rosetta.MDC_THORACIC_FLUID_CONTENT = rosetta_MDC_THORACIC_FLUID_CONTENT

rosetta_MDC_TIME_PCA_LOCKOUT = "MDC_TIME_PCA_LOCKOUT"

rosetta.MDC_TIME_PCA_LOCKOUT = rosetta_MDC_TIME_PCA_LOCKOUT

rosetta_MDC_TIME_PD_APNEA = "MDC_TIME_PD_APNEA"

rosetta.MDC_TIME_PD_APNEA = rosetta_MDC_TIME_PD_APNEA

rosetta_MDC_TIME_PD_DOSE_START_INTERVAL = "MDC_TIME_PD_DOSE_START_INTERVAL"

rosetta.MDC_TIME_PD_DOSE_START_INTERVAL = rosetta_MDC_TIME_PD_DOSE_START_INTERVAL

rosetta_MDC_TIME_PD_EXP = "MDC_TIME_PD_EXP"

rosetta.MDC_TIME_PD_EXP = rosetta_MDC_TIME_PD_EXP

rosetta_MDC_TIME_PD_INSP = "MDC_TIME_PD_INSP"

rosetta.MDC_TIME_PD_INSP = rosetta_MDC_TIME_PD_INSP

rosetta_MDC_TIME_PD_PCA_DOSE_LIMIT = "MDC_TIME_PD_PCA_DOSE_LIMIT"

rosetta.MDC_TIME_PD_PCA_DOSE_LIMIT = rosetta_MDC_TIME_PD_PCA_DOSE_LIMIT

rosetta_MDC_TIME_PD_PROG = "MDC_TIME_PD_PROG"

rosetta.MDC_TIME_PD_PROG = rosetta_MDC_TIME_PD_PROG

rosetta_MDC_TIME_PD_PUPIL_REACT_LEFT = "MDC_TIME_PD_PUPIL_REACT_LEFT"

rosetta.MDC_TIME_PD_PUPIL_REACT_LEFT = rosetta_MDC_TIME_PD_PUPIL_REACT_LEFT

rosetta_MDC_TIME_PD_PUPIL_REACT_RIGHT = "MDC_TIME_PD_PUPIL_REACT_RIGHT"

rosetta.MDC_TIME_PD_PUPIL_REACT_RIGHT = rosetta_MDC_TIME_PD_PUPIL_REACT_RIGHT

rosetta_MDC_TIME_PD_REMAIN = "MDC_TIME_PD_REMAIN"

rosetta.MDC_TIME_PD_REMAIN = rosetta_MDC_TIME_PD_REMAIN

rosetta_MDC_TIME_PD_REMAIN_CONTAINER = "MDC_TIME_PD_REMAIN_CONTAINER"

rosetta.MDC_TIME_PD_REMAIN_CONTAINER = rosetta_MDC_TIME_PD_REMAIN_CONTAINER

rosetta_MDC_TIME_PD_VENT_L_AORT_PRE_EJCT = "MDC_TIME_PD_VENT_L_AORT_PRE_EJCT"

rosetta.MDC_TIME_PD_VENT_L_AORT_PRE_EJCT = rosetta_MDC_TIME_PD_VENT_L_AORT_PRE_EJCT

rosetta_MDC_TIME_PD_VENT_L_AORT_VALV = "MDC_TIME_PD_VENT_L_AORT_VALV"

rosetta.MDC_TIME_PD_VENT_L_AORT_VALV = rosetta_MDC_TIME_PD_VENT_L_AORT_VALV

rosetta_MDC_TRANSMISSION = "MDC_TRANSMISSION"

rosetta.MDC_TRANSMISSION = rosetta_MDC_TRANSMISSION

rosetta_MDC_TRANSMISSION_INFRARED = "MDC_TRANSMISSION_INFRARED"

rosetta.MDC_TRANSMISSION_INFRARED = rosetta_MDC_TRANSMISSION_INFRARED

rosetta_MDC_TRANSMISSION_RED = "MDC_TRANSMISSION_RED"

rosetta.MDC_TRANSMISSION_RED = rosetta_MDC_TRANSMISSION_RED

rosetta_MDC_TTHOR_RESP_RATE = "MDC_TTHOR_RESP_RATE"

rosetta.MDC_TTHOR_RESP_RATE = rosetta_MDC_TTHOR_RESP_RATE

rosetta_MDC_VELOCITY_INDEX = "MDC_VELOCITY_INDEX"

rosetta.MDC_VELOCITY_INDEX = rosetta_MDC_VELOCITY_INDEX

rosetta_MDC_VENT_AWAY_CO2 = "MDC_VENT_AWAY_CO2"

rosetta.MDC_VENT_AWAY_CO2 = rosetta_MDC_VENT_AWAY_CO2

rosetta_MDC_VENT_AWAY_CO2_EXP = "MDC_VENT_AWAY_CO2_EXP"

rosetta.MDC_VENT_AWAY_CO2_EXP = rosetta_MDC_VENT_AWAY_CO2_EXP

rosetta_MDC_VENT_AWAY_CO2_INSP = "MDC_VENT_AWAY_CO2_INSP"

rosetta.MDC_VENT_AWAY_CO2_INSP = rosetta_MDC_VENT_AWAY_CO2_INSP

rosetta_MDC_VENT_AWAY_DESFL = "MDC_VENT_AWAY_DESFL"

rosetta.MDC_VENT_AWAY_DESFL = rosetta_MDC_VENT_AWAY_DESFL

rosetta_MDC_VENT_AWAY_ENFL = "MDC_VENT_AWAY_ENFL"

rosetta.MDC_VENT_AWAY_ENFL = rosetta_MDC_VENT_AWAY_ENFL

rosetta_MDC_VENT_AWAY_HALOTH = "MDC_VENT_AWAY_HALOTH"

rosetta.MDC_VENT_AWAY_HALOTH = rosetta_MDC_VENT_AWAY_HALOTH

rosetta_MDC_VENT_AWAY_ISOFL = "MDC_VENT_AWAY_ISOFL"

rosetta.MDC_VENT_AWAY_ISOFL = rosetta_MDC_VENT_AWAY_ISOFL

rosetta_MDC_VENT_AWAY_N2O = "MDC_VENT_AWAY_N2O"

rosetta.MDC_VENT_AWAY_N2O = rosetta_MDC_VENT_AWAY_N2O

rosetta_MDC_VENT_AWAY_O2 = "MDC_VENT_AWAY_O2"

rosetta.MDC_VENT_AWAY_O2 = rosetta_MDC_VENT_AWAY_O2

rosetta_MDC_VENT_AWAY_O2_EXP = "MDC_VENT_AWAY_O2_EXP"

rosetta.MDC_VENT_AWAY_O2_EXP = rosetta_MDC_VENT_AWAY_O2_EXP

rosetta_MDC_VENT_AWAY_O2_INSP = "MDC_VENT_AWAY_O2_INSP"

rosetta.MDC_VENT_AWAY_O2_INSP = rosetta_MDC_VENT_AWAY_O2_INSP

rosetta_MDC_VENT_AWAY_SEVOFL = "MDC_VENT_AWAY_SEVOFL"

rosetta.MDC_VENT_AWAY_SEVOFL = rosetta_MDC_VENT_AWAY_SEVOFL

rosetta_MDC_VENT_CO2_RESP_RATE = "MDC_VENT_CO2_RESP_RATE"

rosetta.MDC_VENT_CO2_RESP_RATE = rosetta_MDC_VENT_CO2_RESP_RATE

rosetta_MDC_VENT_CONC_AWAY_O2_DELTA = "MDC_VENT_CONC_AWAY_O2_DELTA"

rosetta.MDC_VENT_CONC_AWAY_O2_DELTA = rosetta_MDC_VENT_CONC_AWAY_O2_DELTA

rosetta_MDC_VENT_CONC_AWAY_O2_INSP = "MDC_VENT_CONC_AWAY_O2_INSP"

rosetta.MDC_VENT_CONC_AWAY_O2_INSP = rosetta_MDC_VENT_CONC_AWAY_O2_INSP

rosetta_MDC_VENT_CONC_DESFL_INSP = "MDC_VENT_CONC_DESFL_INSP"

rosetta.MDC_VENT_CONC_DESFL_INSP = rosetta_MDC_VENT_CONC_DESFL_INSP

rosetta_MDC_VENT_CONC_ENFL_INSP = "MDC_VENT_CONC_ENFL_INSP"

rosetta.MDC_VENT_CONC_ENFL_INSP = rosetta_MDC_VENT_CONC_ENFL_INSP

rosetta_MDC_VENT_CONC_HALOTH_INSP = "MDC_VENT_CONC_HALOTH_INSP"

rosetta.MDC_VENT_CONC_HALOTH_INSP = rosetta_MDC_VENT_CONC_HALOTH_INSP

rosetta_MDC_VENT_CONC_ISOFL_INSP = "MDC_VENT_CONC_ISOFL_INSP"

rosetta.MDC_VENT_CONC_ISOFL_INSP = rosetta_MDC_VENT_CONC_ISOFL_INSP

rosetta_MDC_VENT_CONC_SEVOFL_INSP = "MDC_VENT_CONC_SEVOFL_INSP"

rosetta.MDC_VENT_CONC_SEVOFL_INSP = rosetta_MDC_VENT_CONC_SEVOFL_INSP

rosetta_MDC_VENT_DESFL_EXP = "MDC_VENT_DESFL_EXP"

rosetta.MDC_VENT_DESFL_EXP = rosetta_MDC_VENT_DESFL_EXP

rosetta_MDC_VENT_DESFL_INSP = "MDC_VENT_DESFL_INSP"

rosetta.MDC_VENT_DESFL_INSP = rosetta_MDC_VENT_DESFL_INSP

rosetta_MDC_VENT_ENFL_EXP = "MDC_VENT_ENFL_EXP"

rosetta.MDC_VENT_ENFL_EXP = rosetta_MDC_VENT_ENFL_EXP

rosetta_MDC_VENT_ENFL_INSP = "MDC_VENT_ENFL_INSP"

rosetta.MDC_VENT_ENFL_INSP = rosetta_MDC_VENT_ENFL_INSP

rosetta_MDC_VENT_FLOW = "MDC_VENT_FLOW"

rosetta.MDC_VENT_FLOW = rosetta_MDC_VENT_FLOW

rosetta_MDC_VENT_FLOW_EXP = "MDC_VENT_FLOW_EXP"

rosetta.MDC_VENT_FLOW_EXP = rosetta_MDC_VENT_FLOW_EXP

rosetta_MDC_VENT_FLOW_EXP_MAX = "MDC_VENT_FLOW_EXP_MAX"

rosetta.MDC_VENT_FLOW_EXP_MAX = rosetta_MDC_VENT_FLOW_EXP_MAX

rosetta_MDC_VENT_FLOW_INSP = "MDC_VENT_FLOW_INSP"

rosetta.MDC_VENT_FLOW_INSP = rosetta_MDC_VENT_FLOW_INSP

rosetta_MDC_VENT_FLOW_INSP_MAX = "MDC_VENT_FLOW_INSP_MAX"

rosetta.MDC_VENT_FLOW_INSP_MAX = rosetta_MDC_VENT_FLOW_INSP_MAX

rosetta_MDC_VENT_FLOW_RATIO_PERF_ALV_INDEX = "MDC_VENT_FLOW_RATIO_PERF_ALV_INDEX"

rosetta.MDC_VENT_FLOW_RATIO_PERF_ALV_INDEX = rosetta_MDC_VENT_FLOW_RATIO_PERF_ALV_INDEX

rosetta_MDC_VENT_HALOTH_EXP = "MDC_VENT_HALOTH_EXP"

rosetta.MDC_VENT_HALOTH_EXP = rosetta_MDC_VENT_HALOTH_EXP

rosetta_MDC_VENT_HALOTH_INSP = "MDC_VENT_HALOTH_INSP"

rosetta.MDC_VENT_HALOTH_INSP = rosetta_MDC_VENT_HALOTH_INSP

rosetta_MDC_VENT_ISOFL_EXP = "MDC_VENT_ISOFL_EXP"

rosetta.MDC_VENT_ISOFL_EXP = rosetta_MDC_VENT_ISOFL_EXP

rosetta_MDC_VENT_ISOFL_INSP = "MDC_VENT_ISOFL_INSP"

rosetta.MDC_VENT_ISOFL_INSP = rosetta_MDC_VENT_ISOFL_INSP

rosetta_MDC_VENT_N2O_EXP = "MDC_VENT_N2O_EXP"

rosetta.MDC_VENT_N2O_EXP = rosetta_MDC_VENT_N2O_EXP

rosetta_MDC_VENT_N2O_INSP = "MDC_VENT_N2O_INSP"

rosetta.MDC_VENT_N2O_INSP = rosetta_MDC_VENT_N2O_INSP

rosetta_MDC_VENT_PRESS_AWAY = "MDC_VENT_PRESS_AWAY"

rosetta.MDC_VENT_PRESS_AWAY = rosetta_MDC_VENT_PRESS_AWAY

rosetta_MDC_VENT_PRESS_AWAY_END_EXP_POS = "MDC_VENT_PRESS_AWAY_END_EXP_POS"

rosetta.MDC_VENT_PRESS_AWAY_END_EXP_POS = rosetta_MDC_VENT_PRESS_AWAY_END_EXP_POS

rosetta_MDC_VENT_PRESS_MAX = "MDC_VENT_PRESS_MAX"

rosetta.MDC_VENT_PRESS_MAX = rosetta_MDC_VENT_PRESS_MAX

rosetta_MDC_VENT_PRESS_OCCL = "MDC_VENT_PRESS_OCCL"

rosetta.MDC_VENT_PRESS_OCCL = rosetta_MDC_VENT_PRESS_OCCL

rosetta_MDC_VENT_RESP_RATE = "MDC_VENT_RESP_RATE"

rosetta.MDC_VENT_RESP_RATE = rosetta_MDC_VENT_RESP_RATE

rosetta_MDC_VENT_SEVOFL_EXP = "MDC_VENT_SEVOFL_EXP"

rosetta.MDC_VENT_SEVOFL_EXP = rosetta_MDC_VENT_SEVOFL_EXP

rosetta_MDC_VENT_SEVOFL_INSP = "MDC_VENT_SEVOFL_INSP"

rosetta.MDC_VENT_SEVOFL_INSP = rosetta_MDC_VENT_SEVOFL_INSP

rosetta_MDC_VENT_VOL_AWAY_DEADSP = "MDC_VENT_VOL_AWAY_DEADSP"

rosetta.MDC_VENT_VOL_AWAY_DEADSP = rosetta_MDC_VENT_VOL_AWAY_DEADSP

rosetta_MDC_VENT_VOL_AWAY_DEADSP_REL = "MDC_VENT_VOL_AWAY_DEADSP_REL"

rosetta.MDC_VENT_VOL_AWAY_DEADSP_REL = rosetta_MDC_VENT_VOL_AWAY_DEADSP_REL

rosetta_MDC_VENT_VOL_LEAK = "MDC_VENT_VOL_LEAK"

rosetta.MDC_VENT_VOL_LEAK = rosetta_MDC_VENT_VOL_LEAK

rosetta_MDC_VENT_VOL_LUNG_ALV = "MDC_VENT_VOL_LUNG_ALV"

rosetta.MDC_VENT_VOL_LUNG_ALV = rosetta_MDC_VENT_VOL_LUNG_ALV

rosetta_MDC_VENT_VOL_LUNG_TRAPD = "MDC_VENT_VOL_LUNG_TRAPD"

rosetta.MDC_VENT_VOL_LUNG_TRAPD = rosetta_MDC_VENT_VOL_LUNG_TRAPD

rosetta_MDC_VENT_VOL_MINUTE_AWAY = "MDC_VENT_VOL_MINUTE_AWAY"

rosetta.MDC_VENT_VOL_MINUTE_AWAY = rosetta_MDC_VENT_VOL_MINUTE_AWAY

rosetta_MDC_VENT_VOL_MINUTE_AWAY_INSP = "MDC_VENT_VOL_MINUTE_AWAY_INSP"

rosetta.MDC_VENT_VOL_MINUTE_AWAY_INSP = rosetta_MDC_VENT_VOL_MINUTE_AWAY_INSP

rosetta_MDC_VENT_VOL_MINUTE_EXP = "MDC_VENT_VOL_MINUTE_EXP"

rosetta.MDC_VENT_VOL_MINUTE_EXP = rosetta_MDC_VENT_VOL_MINUTE_EXP

rosetta_MDC_VENT_VOL_TIDAL = "MDC_VENT_VOL_TIDAL"

rosetta.MDC_VENT_VOL_TIDAL = rosetta_MDC_VENT_VOL_TIDAL

rosetta_MDC_VENT_VOL_TIDAL_EXP = "MDC_VENT_VOL_TIDAL_EXP"

rosetta.MDC_VENT_VOL_TIDAL_EXP = rosetta_MDC_VENT_VOL_TIDAL_EXP

rosetta_MDC_VENT_VOL_TIDAL_INSP = "MDC_VENT_VOL_TIDAL_INSP"

rosetta.MDC_VENT_VOL_TIDAL_INSP = rosetta_MDC_VENT_VOL_TIDAL_INSP

rosetta_MDC_VOL_AWAY_DEADSP = "MDC_VOL_AWAY_DEADSP"

rosetta.MDC_VOL_AWAY_DEADSP = rosetta_MDC_VOL_AWAY_DEADSP

rosetta_MDC_VOL_AWAY_TIDAL = "MDC_VOL_AWAY_TIDAL"

rosetta.MDC_VOL_AWAY_TIDAL = rosetta_MDC_VOL_AWAY_TIDAL

rosetta_MDC_VOL_AWAY_TIDAL_EXP = "MDC_VOL_AWAY_TIDAL_EXP"

rosetta.MDC_VOL_AWAY_TIDAL_EXP = rosetta_MDC_VOL_AWAY_TIDAL_EXP

rosetta_MDC_VOL_BLD_STROKE = "MDC_VOL_BLD_STROKE"

rosetta.MDC_VOL_BLD_STROKE = rosetta_MDC_VOL_BLD_STROKE

rosetta_MDC_VOL_BLD_STROKE_INDEX = "MDC_VOL_BLD_STROKE_INDEX"

rosetta.MDC_VOL_BLD_STROKE_INDEX = rosetta_MDC_VOL_BLD_STROKE_INDEX

rosetta_MDC_VOL_DELIV_AIR_CASE = "MDC_VOL_DELIV_AIR_CASE"

rosetta.MDC_VOL_DELIV_AIR_CASE = rosetta_MDC_VOL_DELIV_AIR_CASE

rosetta_MDC_VOL_DELIV_AIR_LIQUID_CASE = "MDC_VOL_DELIV_AIR_LIQUID_CASE"

rosetta.MDC_VOL_DELIV_AIR_LIQUID_CASE = rosetta_MDC_VOL_DELIV_AIR_LIQUID_CASE

rosetta_MDC_VOL_DELIV_AIR_TOTAL = "MDC_VOL_DELIV_AIR_TOTAL"

rosetta.MDC_VOL_DELIV_AIR_TOTAL = rosetta_MDC_VOL_DELIV_AIR_TOTAL

rosetta_MDC_VOL_DELIV_CO2_CASE = "MDC_VOL_DELIV_CO2_CASE"

rosetta.MDC_VOL_DELIV_CO2_CASE = rosetta_MDC_VOL_DELIV_CO2_CASE

rosetta_MDC_VOL_DELIV_CO2_TOTAL = "MDC_VOL_DELIV_CO2_TOTAL"

rosetta.MDC_VOL_DELIV_CO2_TOTAL = rosetta_MDC_VOL_DELIV_CO2_TOTAL

rosetta_MDC_VOL_DELIV_DESFL_LIQUID_CASE = "MDC_VOL_DELIV_DESFL_LIQUID_CASE"

rosetta.MDC_VOL_DELIV_DESFL_LIQUID_CASE = rosetta_MDC_VOL_DELIV_DESFL_LIQUID_CASE

rosetta_MDC_VOL_DELIV_DESFL_LIQUID_TOTAL = "MDC_VOL_DELIV_DESFL_LIQUID_TOTAL"

rosetta.MDC_VOL_DELIV_DESFL_LIQUID_TOTAL = rosetta_MDC_VOL_DELIV_DESFL_LIQUID_TOTAL

rosetta_MDC_VOL_DELIV_ENFL_LIQUID_CASE = "MDC_VOL_DELIV_ENFL_LIQUID_CASE"

rosetta.MDC_VOL_DELIV_ENFL_LIQUID_CASE = rosetta_MDC_VOL_DELIV_ENFL_LIQUID_CASE

rosetta_MDC_VOL_DELIV_ENFL_LIQUID_TOTAL = "MDC_VOL_DELIV_ENFL_LIQUID_TOTAL"

rosetta.MDC_VOL_DELIV_ENFL_LIQUID_TOTAL = rosetta_MDC_VOL_DELIV_ENFL_LIQUID_TOTAL

rosetta_MDC_VOL_DELIV_HALOTH_LIQUID_CASE = "MDC_VOL_DELIV_HALOTH_LIQUID_CASE"

rosetta.MDC_VOL_DELIV_HALOTH_LIQUID_CASE = rosetta_MDC_VOL_DELIV_HALOTH_LIQUID_CASE

rosetta_MDC_VOL_DELIV_HALOTH_LIQUID_TOTAL = "MDC_VOL_DELIV_HALOTH_LIQUID_TOTAL"

rosetta.MDC_VOL_DELIV_HALOTH_LIQUID_TOTAL = rosetta_MDC_VOL_DELIV_HALOTH_LIQUID_TOTAL

rosetta_MDC_VOL_DELIV_ISOFL_LIQUID_CASE = "MDC_VOL_DELIV_ISOFL_LIQUID_CASE"

rosetta.MDC_VOL_DELIV_ISOFL_LIQUID_CASE = rosetta_MDC_VOL_DELIV_ISOFL_LIQUID_CASE

rosetta_MDC_VOL_DELIV_ISOFL_LIQUID_TOTAL = "MDC_VOL_DELIV_ISOFL_LIQUID_TOTAL"

rosetta.MDC_VOL_DELIV_ISOFL_LIQUID_TOTAL = rosetta_MDC_VOL_DELIV_ISOFL_LIQUID_TOTAL

rosetta_MDC_VOL_DELIV_N2O_CASE = "MDC_VOL_DELIV_N2O_CASE"

rosetta.MDC_VOL_DELIV_N2O_CASE = rosetta_MDC_VOL_DELIV_N2O_CASE

rosetta_MDC_VOL_DELIV_N2O_TOTAL = "MDC_VOL_DELIV_N2O_TOTAL"

rosetta.MDC_VOL_DELIV_N2O_TOTAL = rosetta_MDC_VOL_DELIV_N2O_TOTAL

rosetta_MDC_VOL_DELIV_O2_CASE = "MDC_VOL_DELIV_O2_CASE"

rosetta.MDC_VOL_DELIV_O2_CASE = rosetta_MDC_VOL_DELIV_O2_CASE

rosetta_MDC_VOL_DELIV_O2_LIQUID_CASE = "MDC_VOL_DELIV_O2_LIQUID_CASE"

rosetta.MDC_VOL_DELIV_O2_LIQUID_CASE = rosetta_MDC_VOL_DELIV_O2_LIQUID_CASE

rosetta_MDC_VOL_DELIV_O2_TOTAL = "MDC_VOL_DELIV_O2_TOTAL"

rosetta.MDC_VOL_DELIV_O2_TOTAL = rosetta_MDC_VOL_DELIV_O2_TOTAL

rosetta_MDC_VOL_DELIV_SEVOFL_LIQUID_CASE = "MDC_VOL_DELIV_SEVOFL_LIQUID_CASE"

rosetta.MDC_VOL_DELIV_SEVOFL_LIQUID_CASE = rosetta_MDC_VOL_DELIV_SEVOFL_LIQUID_CASE

rosetta_MDC_VOL_DELIV_SEVOFL_LIQUID_TOTAL = "MDC_VOL_DELIV_SEVOFL_LIQUID_TOTAL"

rosetta.MDC_VOL_DELIV_SEVOFL_LIQUID_TOTAL = rosetta_MDC_VOL_DELIV_SEVOFL_LIQUID_TOTAL

rosetta_MDC_VOL_FLUID_CONTAINER_START = "MDC_VOL_FLUID_CONTAINER_START"

rosetta.MDC_VOL_FLUID_CONTAINER_START = rosetta_MDC_VOL_FLUID_CONTAINER_START

rosetta_MDC_VOL_FLUID_DELIV = "MDC_VOL_FLUID_DELIV"

rosetta.MDC_VOL_FLUID_DELIV = rosetta_MDC_VOL_FLUID_DELIV

rosetta_MDC_VOL_FLUID_DELIV_SEGMENT = "MDC_VOL_FLUID_DELIV_SEGMENT"

rosetta.MDC_VOL_FLUID_DELIV_SEGMENT = rosetta_MDC_VOL_FLUID_DELIV_SEGMENT

rosetta_MDC_VOL_FLUID_DELIV_TOTAL = "MDC_VOL_FLUID_DELIV_TOTAL"

rosetta.MDC_VOL_FLUID_DELIV_TOTAL = rosetta_MDC_VOL_FLUID_DELIV_TOTAL

rosetta_MDC_VOL_FLUID_DELIV_TOTAL_SET = "MDC_VOL_FLUID_DELIV_TOTAL_SET"

rosetta.MDC_VOL_FLUID_DELIV_TOTAL_SET = rosetta_MDC_VOL_FLUID_DELIV_TOTAL_SET

rosetta_MDC_VOL_FLUID_TBI = "MDC_VOL_FLUID_TBI"

rosetta.MDC_VOL_FLUID_TBI = rosetta_MDC_VOL_FLUID_TBI

rosetta_MDC_VOL_FLUID_TBI_REMAIN = "MDC_VOL_FLUID_TBI_REMAIN"

rosetta.MDC_VOL_FLUID_TBI_REMAIN = rosetta_MDC_VOL_FLUID_TBI_REMAIN

rosetta_MDC_VOL_MINUTE_AWAY = "MDC_VOL_MINUTE_AWAY"

rosetta.MDC_VOL_MINUTE_AWAY = rosetta_MDC_VOL_MINUTE_AWAY

rosetta_MDC_VOL_MINUTE_AWAY_EXP = "MDC_VOL_MINUTE_AWAY_EXP"

rosetta.MDC_VOL_MINUTE_AWAY_EXP = rosetta_MDC_VOL_MINUTE_AWAY_EXP

rosetta_MDC_VOL_MINUTE_AWAY_INSP = "MDC_VOL_MINUTE_AWAY_INSP"

rosetta.MDC_VOL_MINUTE_AWAY_INSP = rosetta_MDC_VOL_MINUTE_AWAY_INSP

rosetta_MDC_VOL_PCA_DOSE_LIMIT = "MDC_VOL_PCA_DOSE_LIMIT"

rosetta.MDC_VOL_PCA_DOSE_LIMIT = rosetta_MDC_VOL_PCA_DOSE_LIMIT

rosetta_MDC_VOL_REMAIN_CONTAINER = "MDC_VOL_REMAIN_CONTAINER"

rosetta.MDC_VOL_REMAIN_CONTAINER = rosetta_MDC_VOL_REMAIN_CONTAINER

rosetta_MDC_VOL_SYRINGE_ACTUAL = "MDC_VOL_SYRINGE_ACTUAL"

rosetta.MDC_VOL_SYRINGE_ACTUAL = rosetta_MDC_VOL_SYRINGE_ACTUAL

rosetta_MDC_VOL_URINE_COL = "MDC_VOL_URINE_COL"

rosetta.MDC_VOL_URINE_COL = rosetta_MDC_VOL_URINE_COL

rosetta_MDC_VOL_VENT_L_END_DIA = "MDC_VOL_VENT_L_END_DIA"

rosetta.MDC_VOL_VENT_L_END_DIA = rosetta_MDC_VOL_VENT_L_END_DIA

rosetta_MDC_VOL_VENT_L_END_SYS = "MDC_VOL_VENT_L_END_SYS"

rosetta.MDC_VOL_VENT_L_END_SYS = rosetta_MDC_VOL_VENT_L_END_SYS

rosetta_MDC_WK_CARD_LEFT = "MDC_WK_CARD_LEFT"

rosetta.MDC_WK_CARD_LEFT = rosetta_MDC_WK_CARD_LEFT

rosetta_MDC_WK_CARD_RIGHT = "MDC_WK_CARD_RIGHT"

rosetta.MDC_WK_CARD_RIGHT = rosetta_MDC_WK_CARD_RIGHT

rosetta_MDC_WK_LV_STROKE = "MDC_WK_LV_STROKE"

rosetta.MDC_WK_LV_STROKE = rosetta_MDC_WK_LV_STROKE

rosetta_MDC_WK_LV_STROKE_INDEX = "MDC_WK_LV_STROKE_INDEX"

rosetta.MDC_WK_LV_STROKE_INDEX = rosetta_MDC_WK_LV_STROKE_INDEX

rosetta_MDC_WK_LV_WORK_INDEX = "MDC_WK_LV_WORK_INDEX"

rosetta.MDC_WK_LV_WORK_INDEX = rosetta_MDC_WK_LV_WORK_INDEX

rosetta_MDC_WK_RV_STROKE_INDEX = "MDC_WK_RV_STROKE_INDEX"

rosetta.MDC_WK_RV_STROKE_INDEX = rosetta_MDC_WK_RV_STROKE_INDEX

rosetta_MDC_WORK_OF_BREATHING_SPON_PATIENT = "MDC_WORK_OF_BREATHING_SPON_PATIENT"

rosetta.MDC_WORK_OF_BREATHING_SPON_PATIENT = rosetta_MDC_WORK_OF_BREATHING_SPON_PATIENT

rosetta_MDC_WORK_OF_BREATHING_SPON_VENT = "MDC_WORK_OF_BREATHING_SPON_VENT"

rosetta.MDC_WORK_OF_BREATHING_SPON_VENT = rosetta_MDC_WORK_OF_BREATHING_SPON_VENT

rosetta_MDC_WORK_OF_BREATHING_VENT = "MDC_WORK_OF_BREATHING_VENT"

rosetta.MDC_WORK_OF_BREATHING_VENT = rosetta_MDC_WORK_OF_BREATHING_VENT
