
# WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.

# This file was generated from units.idl
# using RTI Code Generator (rtiddsgen) version 4.3.0.
# The rtiddsgen tool is part of the RTI Connext DDS distribution.
# For more information, type 'rtiddsgen -help' at a command shell
# or consult the Code Generator User's Manual.

from dataclasses import field
from typing import Union, Sequence, Optional
import rti.idl as idl
from enum import IntEnum
import sys
import os


rosetta = idl.get_module("rosetta")

rosetta_DIM_MILLI_L = "DIM_MILLI_L"

rosetta.DIM_MILLI_L = rosetta_DIM_MILLI_L

rosetta_MDC_DIM_ANG_DEG = "MDC_DIM_ANG_DEG"

rosetta.MDC_DIM_ANG_DEG = rosetta_MDC_DIM_ANG_DEG

rosetta_MDC_DIM_ANG_RAD = "MDC_DIM_ANG_RAD"

rosetta.MDC_DIM_ANG_RAD = rosetta_MDC_DIM_ANG_RAD

rosetta_MDC_DIM_BEAT = "MDC_DIM_BEAT"

rosetta.MDC_DIM_BEAT = rosetta_MDC_DIM_BEAT

rosetta_MDC_DIM_BEAT_PER_MIN = "MDC_DIM_BEAT_PER_MIN"

rosetta.MDC_DIM_BEAT_PER_MIN = rosetta_MDC_DIM_BEAT_PER_MIN

rosetta_MDC_DIM_BEAT_PER_MIN_PER_X_L = "MDC_DIM_BEAT_PER_MIN_PER_X_L"

rosetta.MDC_DIM_BEAT_PER_MIN_PER_X_L = rosetta_MDC_DIM_BEAT_PER_MIN_PER_X_L

rosetta_MDC_DIM_BIT = "MDC_DIM_BIT"

rosetta.MDC_DIM_BIT = rosetta_MDC_DIM_BIT

rosetta_MDC_DIM_BOOLEAN = "MDC_DIM_BOOLEAN"

rosetta.MDC_DIM_BOOLEAN = rosetta_MDC_DIM_BOOLEAN

rosetta_MDC_DIM_BREATH = "MDC_DIM_BREATH"

rosetta.MDC_DIM_BREATH = rosetta_MDC_DIM_BREATH

rosetta_MDC_DIM_BREATHS_PER_MIN_PER_L = "MDC_DIM_BREATHS_PER_MIN_PER_L"

rosetta.MDC_DIM_BREATHS_PER_MIN_PER_L = rosetta_MDC_DIM_BREATHS_PER_MIN_PER_L

rosetta_MDC_DIM_BYTE = "MDC_DIM_BYTE"

rosetta.MDC_DIM_BYTE = rosetta_MDC_DIM_BYTE

rosetta_MDC_DIM_CELL = "MDC_DIM_CELL"

rosetta.MDC_DIM_CELL = rosetta_MDC_DIM_CELL

rosetta_MDC_DIM_CENTI_M = "MDC_DIM_CENTI_M"

rosetta.MDC_DIM_CENTI_M = rosetta_MDC_DIM_CENTI_M

rosetta_MDC_DIM_CM_H2O = "MDC_DIM_CM_H2O"

rosetta.MDC_DIM_CM_H2O = rosetta_MDC_DIM_CM_H2O

rosetta_MDC_DIM_CM_H2O_PER_L = "MDC_DIM_CM_H2O_PER_L"

rosetta.MDC_DIM_CM_H2O_PER_L = rosetta_MDC_DIM_CM_H2O_PER_L

rosetta_MDC_DIM_CM_H2O_PER_L_PER_SEC = "MDC_DIM_CM_H2O_PER_L_PER_SEC"

rosetta.MDC_DIM_CM_H2O_PER_L_PER_SEC = rosetta_MDC_DIM_CM_H2O_PER_L_PER_SEC

rosetta_MDC_DIM_CM_H2O_PER_PERCENT = "MDC_DIM_CM_H2O_PER_PERCENT"

rosetta.MDC_DIM_CM_H2O_PER_PERCENT = rosetta_MDC_DIM_CM_H2O_PER_PERCENT

rosetta_MDC_DIM_COUGH = "MDC_DIM_COUGH"

rosetta.MDC_DIM_COUGH = rosetta_MDC_DIM_COUGH

rosetta_MDC_DIM_CUBIC_X_L_PER_KG = "MDC_DIM_CUBIC_X_L_PER_KG"

rosetta.MDC_DIM_CUBIC_X_L_PER_KG = rosetta_MDC_DIM_CUBIC_X_L_PER_KG

rosetta_MDC_DIM_CUBIC_X_M = "MDC_DIM_CUBIC_X_M"

rosetta.MDC_DIM_CUBIC_X_M = rosetta_MDC_DIM_CUBIC_X_M

rosetta_MDC_DIM_CUBIC_X_M_PER_CM_CUBE = "MDC_DIM_CUBIC_X_M_PER_CM_CUBE"

rosetta.MDC_DIM_CUBIC_X_M_PER_CM_CUBE = rosetta_MDC_DIM_CUBIC_X_M_PER_CM_CUBE

rosetta_MDC_DIM_CUBIC_X_M_PER_DAY = "MDC_DIM_CUBIC_X_M_PER_DAY"

rosetta.MDC_DIM_CUBIC_X_M_PER_DAY = rosetta_MDC_DIM_CUBIC_X_M_PER_DAY

rosetta_MDC_DIM_CUBIC_X_M_PER_HR = "MDC_DIM_CUBIC_X_M_PER_HR"

rosetta.MDC_DIM_CUBIC_X_M_PER_HR = rosetta_MDC_DIM_CUBIC_X_M_PER_HR

rosetta_MDC_DIM_CUBIC_X_M_PER_M_CUBE = "MDC_DIM_CUBIC_X_M_PER_M_CUBE"

rosetta.MDC_DIM_CUBIC_X_M_PER_M_CUBE = rosetta_MDC_DIM_CUBIC_X_M_PER_M_CUBE

rosetta_MDC_DIM_CUBIC_X_M_PER_MIN = "MDC_DIM_CUBIC_X_M_PER_MIN"

rosetta.MDC_DIM_CUBIC_X_M_PER_MIN = rosetta_MDC_DIM_CUBIC_X_M_PER_MIN

rosetta_MDC_DIM_CUBIC_X_M_PER_SEC = "MDC_DIM_CUBIC_X_M_PER_SEC"

rosetta.MDC_DIM_CUBIC_X_M_PER_SEC = rosetta_MDC_DIM_CUBIC_X_M_PER_SEC

rosetta_MDC_DIM_DATE = "MDC_DIM_DATE"

rosetta.MDC_DIM_DATE = rosetta_MDC_DIM_DATE

rosetta_MDC_DIM_DAY = "MDC_DIM_DAY"

rosetta.MDC_DIM_DAY = rosetta_MDC_DIM_DAY

rosetta_MDC_DIM_DECI_BEL = "MDC_DIM_DECI_BEL"

rosetta.MDC_DIM_DECI_BEL = rosetta_MDC_DIM_DECI_BEL

rosetta_MDC_DIM_DECIBEL = "MDC_DIM_DECIBEL"

rosetta.MDC_DIM_DECIBEL = rosetta_MDC_DIM_DECIBEL

rosetta_MDC_DIM_DECIBEL_DECA_NV = "MDC_DIM_DECIBEL_DECA_NV"

rosetta.MDC_DIM_DECIBEL_DECA_NV = rosetta_MDC_DIM_DECIBEL_DECA_NV

rosetta_MDC_DIM_DECIBEL_X_MV = "MDC_DIM_DECIBEL_X_MV"

rosetta.MDC_DIM_DECIBEL_X_MV = rosetta_MDC_DIM_DECIBEL_X_MV

rosetta_MDC_DIM_DECIBEL_X_NV = "MDC_DIM_DECIBEL_X_NV"

rosetta.MDC_DIM_DECIBEL_X_NV = rosetta_MDC_DIM_DECIBEL_X_NV

rosetta_MDC_DIM_DECIBEL_X_UV = "MDC_DIM_DECIBEL_X_UV"

rosetta.MDC_DIM_DECIBEL_X_UV = rosetta_MDC_DIM_DECIBEL_X_UV

rosetta_MDC_DIM_DECIBEL_X_V = "MDC_DIM_DECIBEL_X_V"

rosetta.MDC_DIM_DECIBEL_X_V = rosetta_MDC_DIM_DECIBEL_X_V

rosetta_MDC_DIM_DEGC = "MDC_DIM_DEGC"

rosetta.MDC_DIM_DEGC = rosetta_MDC_DIM_DEGC

rosetta_MDC_DIM_DIMLESS = "MDC_DIM_DIMLESS"

rosetta.MDC_DIM_DIMLESS = rosetta_MDC_DIM_DIMLESS

rosetta_MDC_DIM_DROP = "MDC_DIM_DROP"

rosetta.MDC_DIM_DROP = rosetta_MDC_DIM_DROP

rosetta_MDC_DIM_DROPS_PER_MILLI_L = "MDC_DIM_DROPS_PER_MILLI_L"

rosetta.MDC_DIM_DROPS_PER_MILLI_L = rosetta_MDC_DIM_DROPS_PER_MILLI_L

rosetta_MDC_DIM_DROPS_PER_X_L = "MDC_DIM_DROPS_PER_X_L"

rosetta.MDC_DIM_DROPS_PER_X_L = rosetta_MDC_DIM_DROPS_PER_X_L

rosetta_MDC_DIM_DYNE_SEC_M_SQ_PER_CM_5 = "MDC_DIM_DYNE_SEC_M_SQ_PER_CM_5"

rosetta.MDC_DIM_DYNE_SEC_M_SQ_PER_CM_5 = rosetta_MDC_DIM_DYNE_SEC_M_SQ_PER_CM_5

rosetta_MDC_DIM_DYNE_SEC_PER_CM_5 = "MDC_DIM_DYNE_SEC_PER_CM_5"

rosetta.MDC_DIM_DYNE_SEC_PER_CM_5 = rosetta_MDC_DIM_DYNE_SEC_PER_CM_5

rosetta_MDC_DIM_DYNE_SEC_PER_CM5 = "MDC_DIM_DYNE_SEC_PER_CM5"

rosetta.MDC_DIM_DYNE_SEC_PER_CM5 = rosetta_MDC_DIM_DYNE_SEC_PER_CM5

rosetta_MDC_DIM_DYNE_SEC_PER_M_SQ_PER_CM_5 = "MDC_DIM_DYNE_SEC_PER_M_SQ_PER_CM_5"

rosetta.MDC_DIM_DYNE_SEC_PER_M_SQ_PER_CM_5 = rosetta_MDC_DIM_DYNE_SEC_PER_M_SQ_PER_CM_5

rosetta_MDC_DIM_EVOLT = "MDC_DIM_EVOLT"

rosetta.MDC_DIM_EVOLT = rosetta_MDC_DIM_EVOLT

rosetta_MDC_DIM_FAHR = "MDC_DIM_FAHR"

rosetta.MDC_DIM_FAHR = rosetta_MDC_DIM_FAHR

rosetta_MDC_DIM_G = "MDC_DIM_G"

rosetta.MDC_DIM_G = rosetta_MDC_DIM_G

rosetta_MDC_DIM_G_FORCE_M = "MDC_DIM_G_FORCE_M"

rosetta.MDC_DIM_G_FORCE_M = rosetta_MDC_DIM_G_FORCE_M

rosetta_MDC_DIM_G_M = "MDC_DIM_G_M"

rosetta.MDC_DIM_G_M = rosetta_MDC_DIM_G_M

rosetta_MDC_DIM_G_PER_DL = "MDC_DIM_G_PER_DL"

rosetta.MDC_DIM_G_PER_DL = rosetta_MDC_DIM_G_PER_DL

rosetta_MDC_DIM_G_PER_L = "MDC_DIM_G_PER_L"

rosetta.MDC_DIM_G_PER_L = rosetta_MDC_DIM_G_PER_L

rosetta_MDC_DIM_G_PER_ML = "MDC_DIM_G_PER_ML"

rosetta.MDC_DIM_G_PER_ML = rosetta_MDC_DIM_G_PER_ML

rosetta_MDC_DIM_HECTO_PASCAL = "MDC_DIM_HECTO_PASCAL"

rosetta.MDC_DIM_HECTO_PASCAL = rosetta_MDC_DIM_HECTO_PASCAL

rosetta_MDC_DIM_HR = "MDC_DIM_HR"

rosetta.MDC_DIM_HR = rosetta_MDC_DIM_HR

rosetta_MDC_DIM_HZ = "MDC_DIM_HZ"

rosetta.MDC_DIM_HZ = rosetta_MDC_DIM_HZ

rosetta_MDC_DIM_INCH = "MDC_DIM_INCH"

rosetta.MDC_DIM_INCH = rosetta_MDC_DIM_INCH

rosetta_MDC_DIM_INTL_UNIT_PER_ML = "MDC_DIM_INTL_UNIT_PER_ML"

rosetta.MDC_DIM_INTL_UNIT_PER_ML = rosetta_MDC_DIM_INTL_UNIT_PER_ML

rosetta_MDC_DIM_JOULES_PER_L = "MDC_DIM_JOULES_PER_L"

rosetta.MDC_DIM_JOULES_PER_L = rosetta_MDC_DIM_JOULES_PER_L

rosetta_MDC_DIM_KELVIN = "MDC_DIM_KELVIN"

rosetta.MDC_DIM_KELVIN = rosetta_MDC_DIM_KELVIN

rosetta_MDC_DIM_KELVIN_PER_X_WATT = "MDC_DIM_KELVIN_PER_X_WATT"

rosetta.MDC_DIM_KELVIN_PER_X_WATT = rosetta_MDC_DIM_KELVIN_PER_X_WATT

rosetta_MDC_DIM_KG_PER_M_SQ = "MDC_DIM_KG_PER_M_SQ#"

rosetta.MDC_DIM_KG_PER_M_SQ = rosetta_MDC_DIM_KG_PER_M_SQ

rosetta_MDC_DIM_KILO_CAL = "MDC_DIM_KILO_CAL"

rosetta.MDC_DIM_KILO_CAL = rosetta_MDC_DIM_KILO_CAL

rosetta_MDC_DIM_KILO_CAL_PER_DAY = "MDC_DIM_KILO_CAL_PER_DAY"

rosetta.MDC_DIM_KILO_CAL_PER_DAY = rosetta_MDC_DIM_KILO_CAL_PER_DAY

rosetta_MDC_DIM_KILO_G = "MDC_DIM_KILO_G"

rosetta.MDC_DIM_KILO_G = rosetta_MDC_DIM_KILO_G

rosetta_MDC_DIM_KILO_G_FORCE_M = "MDC_DIM_KILO_G_FORCE_M"

rosetta.MDC_DIM_KILO_G_FORCE_M = rosetta_MDC_DIM_KILO_G_FORCE_M

rosetta_MDC_DIM_KILO_G_FORCE_M_PER_L = "MDC_DIM_KILO_G_FORCE_M_PER_L"

rosetta.MDC_DIM_KILO_G_FORCE_M_PER_L = rosetta_MDC_DIM_KILO_G_FORCE_M_PER_L

rosetta_MDC_DIM_KILO_G_FORCE_M_PER_M_SQ = "MDC_DIM_KILO_G_FORCE_M_PER_M_SQ"

rosetta.MDC_DIM_KILO_G_FORCE_M_PER_M_SQ = rosetta_MDC_DIM_KILO_G_FORCE_M_PER_M_SQ

rosetta_MDC_DIM_KILO_G_PER_M_SQ = "MDC_DIM_KILO_G_PER_M_SQ"

rosetta.MDC_DIM_KILO_G_PER_M_SQ = rosetta_MDC_DIM_KILO_G_PER_M_SQ

rosetta_MDC_DIM_KILO_PASCAL = "MDC_DIM_KILO_PASCAL"

rosetta.MDC_DIM_KILO_PASCAL = rosetta_MDC_DIM_KILO_PASCAL

rosetta_MDC_DIM_L = "MDC_DIM_L"

rosetta.MDC_DIM_L = rosetta_MDC_DIM_L

rosetta_MDC_DIM_L_PER_MIN = "MDC_DIM_L_PER_MIN"

rosetta.MDC_DIM_L_PER_MIN = rosetta_MDC_DIM_L_PER_MIN

rosetta_MDC_DIM_L_PER_MIN_PER_M_SQ = "MDC_DIM_L_PER_MIN_PER_M_SQ"

rosetta.MDC_DIM_L_PER_MIN_PER_M_SQ = rosetta_MDC_DIM_L_PER_MIN_PER_M_SQ

rosetta_MDC_DIM_LB = "MDC_DIM_LB"

rosetta.MDC_DIM_LB = rosetta_MDC_DIM_LB

rosetta_MDC_DIM_MEGA_INTL_UNIT = "MDC_DIM_MEGA_INTL_UNIT"

rosetta.MDC_DIM_MEGA_INTL_UNIT = rosetta_MDC_DIM_MEGA_INTL_UNIT

rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_DAY = "MDC_DIM_MEGA_INTL_UNIT_PER_DAY"

rosetta.MDC_DIM_MEGA_INTL_UNIT_PER_DAY = rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_DAY

rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_HR = "MDC_DIM_MEGA_INTL_UNIT_PER_HR"

rosetta.MDC_DIM_MEGA_INTL_UNIT_PER_HR = rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_HR

rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_KG = "MDC_DIM_MEGA_INTL_UNIT_PER_KG"

rosetta.MDC_DIM_MEGA_INTL_UNIT_PER_KG = rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_KG

rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_DAY = "MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_DAY"

rosetta.MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_DAY = rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_DAY

rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_HR = "MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_HR"

rosetta.MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_HR = rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_HR

rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_MIN = "MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_MIN"

rosetta.MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_MIN = rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_MIN

rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_SEC = "MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_SEC"

rosetta.MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_SEC = rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_SEC

rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ = "MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ"

rosetta.MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ = rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ

rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_DAY = "MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_DAY"

rosetta.MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_DAY = rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_DAY

rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_HR = "MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_HR"

rosetta.MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_HR = rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_HR

rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_MIN = "MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_MIN"

rosetta.MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_MIN = rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_MIN

rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_SEC = "MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_SEC"

rosetta.MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_SEC = rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_M_SQ_PER_SEC

rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_MIN = "MDC_DIM_MEGA_INTL_UNIT_PER_MIN"

rosetta.MDC_DIM_MEGA_INTL_UNIT_PER_MIN = rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_MIN

rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_ML = "MDC_DIM_MEGA_INTL_UNIT_PER_ML"

rosetta.MDC_DIM_MEGA_INTL_UNIT_PER_ML = rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_ML

rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_SEC = "MDC_DIM_MEGA_INTL_UNIT_PER_SEC"

rosetta.MDC_DIM_MEGA_INTL_UNIT_PER_SEC = rosetta_MDC_DIM_MEGA_INTL_UNIT_PER_SEC

rosetta_MDC_DIM_MICRO_G = "MDC_DIM_MICRO_G"

rosetta.MDC_DIM_MICRO_G = rosetta_MDC_DIM_MICRO_G

rosetta_MDC_DIM_MICRO_G_PER_DAY = "MDC_DIM_MICRO_G_PER_DAY"

rosetta.MDC_DIM_MICRO_G_PER_DAY = rosetta_MDC_DIM_MICRO_G_PER_DAY

rosetta_MDC_DIM_MICRO_G_PER_HR = "MDC_DIM_MICRO_G_PER_HR"

rosetta.MDC_DIM_MICRO_G_PER_HR = rosetta_MDC_DIM_MICRO_G_PER_HR

rosetta_MDC_DIM_MICRO_G_PER_KG = "MDC_DIM_MICRO_G_PER_KG"

rosetta.MDC_DIM_MICRO_G_PER_KG = rosetta_MDC_DIM_MICRO_G_PER_KG

rosetta_MDC_DIM_MICRO_G_PER_KG_PER_DAY = "MDC_DIM_MICRO_G_PER_KG_PER_DAY"

rosetta.MDC_DIM_MICRO_G_PER_KG_PER_DAY = rosetta_MDC_DIM_MICRO_G_PER_KG_PER_DAY

rosetta_MDC_DIM_MICRO_G_PER_KG_PER_HR = "MDC_DIM_MICRO_G_PER_KG_PER_HR"

rosetta.MDC_DIM_MICRO_G_PER_KG_PER_HR = rosetta_MDC_DIM_MICRO_G_PER_KG_PER_HR

rosetta_MDC_DIM_MICRO_G_PER_KG_PER_MIN = "MDC_DIM_MICRO_G_PER_KG_PER_MIN"

rosetta.MDC_DIM_MICRO_G_PER_KG_PER_MIN = rosetta_MDC_DIM_MICRO_G_PER_KG_PER_MIN

rosetta_MDC_DIM_MICRO_G_PER_LB_PER_HR = "MDC_DIM_MICRO_G_PER_LB_PER_HR"

rosetta.MDC_DIM_MICRO_G_PER_LB_PER_HR = rosetta_MDC_DIM_MICRO_G_PER_LB_PER_HR

rosetta_MDC_DIM_MICRO_G_PER_LB_PER_MIN = "MDC_DIM_MICRO_G_PER_LB_PER_MIN"

rosetta.MDC_DIM_MICRO_G_PER_LB_PER_MIN = rosetta_MDC_DIM_MICRO_G_PER_LB_PER_MIN

rosetta_MDC_DIM_MICRO_G_PER_M_SQ = "MDC_DIM_MICRO_G_PER_M_SQ"

rosetta.MDC_DIM_MICRO_G_PER_M_SQ = rosetta_MDC_DIM_MICRO_G_PER_M_SQ

rosetta_MDC_DIM_MICRO_G_PER_M_SQ_PER_DAY = "MDC_DIM_MICRO_G_PER_M_SQ_PER_DAY"

rosetta.MDC_DIM_MICRO_G_PER_M_SQ_PER_DAY = rosetta_MDC_DIM_MICRO_G_PER_M_SQ_PER_DAY

rosetta_MDC_DIM_MICRO_G_PER_M_SQ_PER_HR = "MDC_DIM_MICRO_G_PER_M_SQ_PER_HR"

rosetta.MDC_DIM_MICRO_G_PER_M_SQ_PER_HR = rosetta_MDC_DIM_MICRO_G_PER_M_SQ_PER_HR

rosetta_MDC_DIM_MICRO_G_PER_M_SQ_PER_MIN = "MDC_DIM_MICRO_G_PER_M_SQ_PER_MIN"

rosetta.MDC_DIM_MICRO_G_PER_M_SQ_PER_MIN = rosetta_MDC_DIM_MICRO_G_PER_M_SQ_PER_MIN

rosetta_MDC_DIM_MICRO_G_PER_MIN = "MDC_DIM_MICRO_G_PER_MIN"

rosetta.MDC_DIM_MICRO_G_PER_MIN = rosetta_MDC_DIM_MICRO_G_PER_MIN

rosetta_MDC_DIM_MICRO_G_PER_ML = "MDC_DIM_MICRO_G_PER_ML"

rosetta.MDC_DIM_MICRO_G_PER_ML = rosetta_MDC_DIM_MICRO_G_PER_ML

rosetta_MDC_DIM_MICRO_INTL_UNIT_PER_KG = "MDC_DIM_MICRO_INTL_UNIT_PER_KG"

rosetta.MDC_DIM_MICRO_INTL_UNIT_PER_KG = rosetta_MDC_DIM_MICRO_INTL_UNIT_PER_KG

rosetta_MDC_DIM_MICRO_INTL_UNIT_PER_M_SQ = "MDC_DIM_MICRO_INTL_UNIT_PER_M_SQ"

rosetta.MDC_DIM_MICRO_INTL_UNIT_PER_M_SQ = rosetta_MDC_DIM_MICRO_INTL_UNIT_PER_M_SQ

rosetta_MDC_DIM_MICRO_L = "MDC_DIM_MICRO_L"

rosetta.MDC_DIM_MICRO_L = rosetta_MDC_DIM_MICRO_L

rosetta_MDC_DIM_MICRO_L_PER_MIN = "MDC_DIM_MICRO_L_PER_MIN"

rosetta.MDC_DIM_MICRO_L_PER_MIN = rosetta_MDC_DIM_MICRO_L_PER_MIN

rosetta_MDC_DIM_MICRO_M = "MDC_DIM_MICRO_M"

rosetta.MDC_DIM_MICRO_M = rosetta_MDC_DIM_MICRO_M

rosetta_MDC_DIM_MICRO_SEC = "MDC_DIM_MICRO_SEC"

rosetta.MDC_DIM_MICRO_SEC = rosetta_MDC_DIM_MICRO_SEC

rosetta_MDC_DIM_MICRO_VOLT = "MDC_DIM_MICRO_VOLT"

rosetta.MDC_DIM_MICRO_VOLT = rosetta_MDC_DIM_MICRO_VOLT

rosetta_MDC_DIM_MICRO_VOLT_PER_SEC = "MDC_DIM_MICRO_VOLT_PER_SEC"

rosetta.MDC_DIM_MICRO_VOLT_PER_SEC = rosetta_MDC_DIM_MICRO_VOLT_PER_SEC

rosetta_MDC_DIM_MICRO_WATT = "MDC_DIM_MICRO_WATT"

rosetta.MDC_DIM_MICRO_WATT = rosetta_MDC_DIM_MICRO_WATT

rosetta_MDC_DIM_MILLI_EQUIV = "MDC_DIM_MILLI_EQUIV"

rosetta.MDC_DIM_MILLI_EQUIV = rosetta_MDC_DIM_MILLI_EQUIV

rosetta_MDC_DIM_MILLI_EQUIV_PER_DAY = "MDC_DIM_MILLI_EQUIV_PER_DAY"

rosetta.MDC_DIM_MILLI_EQUIV_PER_DAY = rosetta_MDC_DIM_MILLI_EQUIV_PER_DAY

rosetta_MDC_DIM_MILLI_EQUIV_PER_HR = "MDC_DIM_MILLI_EQUIV_PER_HR"

rosetta.MDC_DIM_MILLI_EQUIV_PER_HR = rosetta_MDC_DIM_MILLI_EQUIV_PER_HR

rosetta_MDC_DIM_MILLI_EQUIV_PER_KG = "MDC_DIM_MILLI_EQUIV_PER_KG"

rosetta.MDC_DIM_MILLI_EQUIV_PER_KG = rosetta_MDC_DIM_MILLI_EQUIV_PER_KG

rosetta_MDC_DIM_MILLI_EQUIV_PER_KG_PER_DAY = "MDC_DIM_MILLI_EQUIV_PER_KG_PER_DAY"

rosetta.MDC_DIM_MILLI_EQUIV_PER_KG_PER_DAY = rosetta_MDC_DIM_MILLI_EQUIV_PER_KG_PER_DAY

rosetta_MDC_DIM_MILLI_EQUIV_PER_KG_PER_HR = "MDC_DIM_MILLI_EQUIV_PER_KG_PER_HR"

rosetta.MDC_DIM_MILLI_EQUIV_PER_KG_PER_HR = rosetta_MDC_DIM_MILLI_EQUIV_PER_KG_PER_HR

rosetta_MDC_DIM_MILLI_EQUIV_PER_KG_PER_MIN = "MDC_DIM_MILLI_EQUIV_PER_KG_PER_MIN"

rosetta.MDC_DIM_MILLI_EQUIV_PER_KG_PER_MIN = rosetta_MDC_DIM_MILLI_EQUIV_PER_KG_PER_MIN

rosetta_MDC_DIM_MILLI_EQUIV_PER_L = "MDC_DIM_MILLI_EQUIV_PER_L"

rosetta.MDC_DIM_MILLI_EQUIV_PER_L = rosetta_MDC_DIM_MILLI_EQUIV_PER_L

rosetta_MDC_DIM_MILLI_EQUIV_PER_LB_PER_HR = "MDC_DIM_MILLI_EQUIV_PER_LB_PER_HR"

rosetta.MDC_DIM_MILLI_EQUIV_PER_LB_PER_HR = rosetta_MDC_DIM_MILLI_EQUIV_PER_LB_PER_HR

rosetta_MDC_DIM_MILLI_EQUIV_PER_LB_PER_MIN = "MDC_DIM_MILLI_EQUIV_PER_LB_PER_MIN"

rosetta.MDC_DIM_MILLI_EQUIV_PER_LB_PER_MIN = rosetta_MDC_DIM_MILLI_EQUIV_PER_LB_PER_MIN

rosetta_MDC_DIM_MILLI_EQUIV_PER_M_SQ = "MDC_DIM_MILLI_EQUIV_PER_M_SQ"

rosetta.MDC_DIM_MILLI_EQUIV_PER_M_SQ = rosetta_MDC_DIM_MILLI_EQUIV_PER_M_SQ

rosetta_MDC_DIM_MILLI_EQUIV_PER_M_SQ_PER_DAY = "MDC_DIM_MILLI_EQUIV_PER_M_SQ_PER_DAY"

rosetta.MDC_DIM_MILLI_EQUIV_PER_M_SQ_PER_DAY = rosetta_MDC_DIM_MILLI_EQUIV_PER_M_SQ_PER_DAY

rosetta_MDC_DIM_MILLI_EQUIV_PER_M_SQ_PER_HR = "MDC_DIM_MILLI_EQUIV_PER_M_SQ_PER_HR"

rosetta.MDC_DIM_MILLI_EQUIV_PER_M_SQ_PER_HR = rosetta_MDC_DIM_MILLI_EQUIV_PER_M_SQ_PER_HR

rosetta_MDC_DIM_MILLI_EQUIV_PER_M_SQ_PER_MIN = "MDC_DIM_MILLI_EQUIV_PER_M_SQ_PER_MIN"

rosetta.MDC_DIM_MILLI_EQUIV_PER_M_SQ_PER_MIN = rosetta_MDC_DIM_MILLI_EQUIV_PER_M_SQ_PER_MIN

rosetta_MDC_DIM_MILLI_EQUIV_PER_MIN = "MDC_DIM_MILLI_EQUIV_PER_MIN"

rosetta.MDC_DIM_MILLI_EQUIV_PER_MIN = rosetta_MDC_DIM_MILLI_EQUIV_PER_MIN

rosetta_MDC_DIM_MILLI_EQUIV_PER_ML = "MDC_DIM_MILLI_EQUIV_PER_ML"

rosetta.MDC_DIM_MILLI_EQUIV_PER_ML = rosetta_MDC_DIM_MILLI_EQUIV_PER_ML

rosetta_MDC_DIM_MILLI_G = "MDC_DIM_MILLI_G"

rosetta.MDC_DIM_MILLI_G = rosetta_MDC_DIM_MILLI_G

rosetta_MDC_DIM_MILLI_G_PER_DAY = "MDC_DIM_MILLI_G_PER_DAY"

rosetta.MDC_DIM_MILLI_G_PER_DAY = rosetta_MDC_DIM_MILLI_G_PER_DAY

rosetta_MDC_DIM_MILLI_G_PER_DL = "MDC_DIM_MILLI_G_PER_DL"

rosetta.MDC_DIM_MILLI_G_PER_DL = rosetta_MDC_DIM_MILLI_G_PER_DL

rosetta_MDC_DIM_MILLI_G_PER_HR = "MDC_DIM_MILLI_G_PER_HR"

rosetta.MDC_DIM_MILLI_G_PER_HR = rosetta_MDC_DIM_MILLI_G_PER_HR

rosetta_MDC_DIM_MILLI_G_PER_KG = "MDC_DIM_MILLI_G_PER_KG"

rosetta.MDC_DIM_MILLI_G_PER_KG = rosetta_MDC_DIM_MILLI_G_PER_KG

rosetta_MDC_DIM_MILLI_G_PER_KG_PER_DAY = "MDC_DIM_MILLI_G_PER_KG_PER_DAY"

rosetta.MDC_DIM_MILLI_G_PER_KG_PER_DAY = rosetta_MDC_DIM_MILLI_G_PER_KG_PER_DAY

rosetta_MDC_DIM_MILLI_G_PER_KG_PER_HR = "MDC_DIM_MILLI_G_PER_KG_PER_HR"

rosetta.MDC_DIM_MILLI_G_PER_KG_PER_HR = rosetta_MDC_DIM_MILLI_G_PER_KG_PER_HR

rosetta_MDC_DIM_MILLI_G_PER_KG_PER_MIN = "MDC_DIM_MILLI_G_PER_KG_PER_MIN"

rosetta.MDC_DIM_MILLI_G_PER_KG_PER_MIN = rosetta_MDC_DIM_MILLI_G_PER_KG_PER_MIN

rosetta_MDC_DIM_MILLI_G_PER_LB_PER_HR = "MDC_DIM_MILLI_G_PER_LB_PER_HR"

rosetta.MDC_DIM_MILLI_G_PER_LB_PER_HR = rosetta_MDC_DIM_MILLI_G_PER_LB_PER_HR

rosetta_MDC_DIM_MILLI_G_PER_LB_PER_MIN = "MDC_DIM_MILLI_G_PER_LB_PER_MIN"

rosetta.MDC_DIM_MILLI_G_PER_LB_PER_MIN = rosetta_MDC_DIM_MILLI_G_PER_LB_PER_MIN

rosetta_MDC_DIM_MILLI_G_PER_M_SQ = "MDC_DIM_MILLI_G_PER_M_SQ"

rosetta.MDC_DIM_MILLI_G_PER_M_SQ = rosetta_MDC_DIM_MILLI_G_PER_M_SQ

rosetta_MDC_DIM_MILLI_G_PER_M_SQ_PER_DAY = "MDC_DIM_MILLI_G_PER_M_SQ_PER_DAY"

rosetta.MDC_DIM_MILLI_G_PER_M_SQ_PER_DAY = rosetta_MDC_DIM_MILLI_G_PER_M_SQ_PER_DAY

rosetta_MDC_DIM_MILLI_G_PER_M_SQ_PER_HR = "MDC_DIM_MILLI_G_PER_M_SQ_PER_HR"

rosetta.MDC_DIM_MILLI_G_PER_M_SQ_PER_HR = rosetta_MDC_DIM_MILLI_G_PER_M_SQ_PER_HR

rosetta_MDC_DIM_MILLI_G_PER_M_SQ_PER_MIN = "MDC_DIM_MILLI_G_PER_M_SQ_PER_MIN"

rosetta.MDC_DIM_MILLI_G_PER_M_SQ_PER_MIN = rosetta_MDC_DIM_MILLI_G_PER_M_SQ_PER_MIN

rosetta_MDC_DIM_MILLI_G_PER_MIN = "MDC_DIM_MILLI_G_PER_MIN"

rosetta.MDC_DIM_MILLI_G_PER_MIN = rosetta_MDC_DIM_MILLI_G_PER_MIN

rosetta_MDC_DIM_MILLI_G_PER_ML = "MDC_DIM_MILLI_G_PER_ML"

rosetta.MDC_DIM_MILLI_G_PER_ML = rosetta_MDC_DIM_MILLI_G_PER_ML

rosetta_MDC_DIM_MILLI_INTL_UNIT = "MDC_DIM_MILLI_INTL_UNIT"

rosetta.MDC_DIM_MILLI_INTL_UNIT = rosetta_MDC_DIM_MILLI_INTL_UNIT

rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_DAY = "MDC_DIM_MILLI_INTL_UNIT_PER_DAY"

rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_DAY = rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_DAY

rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_HR = "MDC_DIM_MILLI_INTL_UNIT_PER_HR"

rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_HR = rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_HR

rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_KG = "MDC_DIM_MILLI_INTL_UNIT_PER_KG"

rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_KG = rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_KG

rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_DAY = "MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_DAY"

rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_DAY = rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_DAY

rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_HR = "MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_HR"

rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_HR = rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_HR

rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_MIN = "MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_MIN"

rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_MIN = rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_MIN

rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_SEC = "MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_SEC"

rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_SEC = rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_SEC

rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_LB_PER_HR = "MDC_DIM_MILLI_INTL_UNIT_PER_LB_PER_HR"

rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_LB_PER_HR = rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_LB_PER_HR

rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_LB_PER_MIN = "MDC_DIM_MILLI_INTL_UNIT_PER_LB_PER_MIN"

rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_LB_PER_MIN = rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_LB_PER_MIN

rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ = "MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ"

rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ = rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ

rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_DAY = "MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_DAY"

rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_DAY = rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_DAY

rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_HR = "MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_HR"

rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_HR = rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_HR

rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_MIN = "MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_MIN"

rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_MIN = rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_MIN

rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_SEC = "MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_SEC"

rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_SEC = rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_M_SQ_PER_SEC

rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_MIN = "MDC_DIM_MILLI_INTL_UNIT_PER_MIN"

rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_MIN = rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_MIN

rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_ML = "MDC_DIM_MILLI_INTL_UNIT_PER_ML"

rosetta.MDC_DIM_MILLI_INTL_UNIT_PER_ML = rosetta_MDC_DIM_MILLI_INTL_UNIT_PER_ML

rosetta_MDC_DIM_MILLI_L = "MDC_DIM_MILLI_L"

rosetta.MDC_DIM_MILLI_L = rosetta_MDC_DIM_MILLI_L

rosetta_MDC_DIM_MILLI_L_PER_BEAT = "MDC_DIM_MILLI_L_PER_BEAT"

rosetta.MDC_DIM_MILLI_L_PER_BEAT = rosetta_MDC_DIM_MILLI_L_PER_BEAT

rosetta_MDC_DIM_MILLI_L_PER_BREATH = "MDC_DIM_MILLI_L_PER_BREATH"

rosetta.MDC_DIM_MILLI_L_PER_BREATH = rosetta_MDC_DIM_MILLI_L_PER_BREATH

rosetta_MDC_DIM_MILLI_L_PER_CM_H2O = "MDC_DIM_MILLI_L_PER_CM_H2O"

rosetta.MDC_DIM_MILLI_L_PER_CM_H2O = rosetta_MDC_DIM_MILLI_L_PER_CM_H2O

rosetta_MDC_DIM_MILLI_L_PER_CM_H2O_PER_KG = "MDC_DIM_MILLI_L_PER_CM_H2O_PER_KG"

rosetta.MDC_DIM_MILLI_L_PER_CM_H2O_PER_KG = rosetta_MDC_DIM_MILLI_L_PER_CM_H2O_PER_KG

rosetta_MDC_DIM_MILLI_L_PER_DL = "MDC_DIM_MILLI_L_PER_DL"

rosetta.MDC_DIM_MILLI_L_PER_DL = rosetta_MDC_DIM_MILLI_L_PER_DL

rosetta_MDC_DIM_MILLI_L_PER_HR = "MDC_DIM_MILLI_L_PER_HR"

rosetta.MDC_DIM_MILLI_L_PER_HR = rosetta_MDC_DIM_MILLI_L_PER_HR

rosetta_MDC_DIM_MILLI_L_PER_KG = "MDC_DIM_MILLI_L_PER_KG"

rosetta.MDC_DIM_MILLI_L_PER_KG = rosetta_MDC_DIM_MILLI_L_PER_KG

rosetta_MDC_DIM_MILLI_L_PER_KG_PER_DAY = "MDC_DIM_MILLI_L_PER_KG_PER_DAY"

rosetta.MDC_DIM_MILLI_L_PER_KG_PER_DAY = rosetta_MDC_DIM_MILLI_L_PER_KG_PER_DAY

rosetta_MDC_DIM_MILLI_L_PER_KG_PER_HR = "MDC_DIM_MILLI_L_PER_KG_PER_HR"

rosetta.MDC_DIM_MILLI_L_PER_KG_PER_HR = rosetta_MDC_DIM_MILLI_L_PER_KG_PER_HR

rosetta_MDC_DIM_MILLI_L_PER_KG_PER_MIN = "MDC_DIM_MILLI_L_PER_KG_PER_MIN"

rosetta.MDC_DIM_MILLI_L_PER_KG_PER_MIN = rosetta_MDC_DIM_MILLI_L_PER_KG_PER_MIN

rosetta_MDC_DIM_MILLI_L_PER_M_SQ = "MDC_DIM_MILLI_L_PER_M_SQ"

rosetta.MDC_DIM_MILLI_L_PER_M_SQ = rosetta_MDC_DIM_MILLI_L_PER_M_SQ

rosetta_MDC_DIM_MILLI_L_PER_M_SQ_PER_DAY = "MDC_DIM_MILLI_L_PER_M_SQ_PER_DAY"

rosetta.MDC_DIM_MILLI_L_PER_M_SQ_PER_DAY = rosetta_MDC_DIM_MILLI_L_PER_M_SQ_PER_DAY

rosetta_MDC_DIM_MILLI_L_PER_M_SQ_PER_HR = "MDC_DIM_MILLI_L_PER_M_SQ_PER_HR"

rosetta.MDC_DIM_MILLI_L_PER_M_SQ_PER_HR = rosetta_MDC_DIM_MILLI_L_PER_M_SQ_PER_HR

rosetta_MDC_DIM_MILLI_L_PER_M_SQ_PER_MIN = "MDC_DIM_MILLI_L_PER_M_SQ_PER_MIN"

rosetta.MDC_DIM_MILLI_L_PER_M_SQ_PER_MIN = rosetta_MDC_DIM_MILLI_L_PER_M_SQ_PER_MIN

rosetta_MDC_DIM_MILLI_L_PER_MIN = "MDC_DIM_MILLI_L_PER_MIN"

rosetta.MDC_DIM_MILLI_L_PER_MIN = rosetta_MDC_DIM_MILLI_L_PER_MIN

rosetta_MDC_DIM_MILLI_L_PER_MIN_PER_KG = "MDC_DIM_MILLI_L_PER_MIN_PER_KG"

rosetta.MDC_DIM_MILLI_L_PER_MIN_PER_KG = rosetta_MDC_DIM_MILLI_L_PER_MIN_PER_KG

rosetta_MDC_DIM_MILLI_L_PER_MIN_PER_M_SQ = "MDC_DIM_MILLI_L_PER_MIN_PER_M_SQ"

rosetta.MDC_DIM_MILLI_L_PER_MIN_PER_M_SQ = rosetta_MDC_DIM_MILLI_L_PER_MIN_PER_M_SQ

rosetta_MDC_DIM_MILLI_M = "MDC_DIM_MILLI_M"

rosetta.MDC_DIM_MILLI_M = rosetta_MDC_DIM_MILLI_M

rosetta_MDC_DIM_MILLI_M_PER_SEC = "MDC_DIM_MILLI_M_PER_SEC"

rosetta.MDC_DIM_MILLI_M_PER_SEC = rosetta_MDC_DIM_MILLI_M_PER_SEC

rosetta_MDC_DIM_MILLI_MOLE = "MDC_DIM_MILLI_MOLE"

rosetta.MDC_DIM_MILLI_MOLE = rosetta_MDC_DIM_MILLI_MOLE

rosetta_MDC_DIM_MILLI_MOLE_PER_DAY = "MDC_DIM_MILLI_MOLE_PER_DAY"

rosetta.MDC_DIM_MILLI_MOLE_PER_DAY = rosetta_MDC_DIM_MILLI_MOLE_PER_DAY

rosetta_MDC_DIM_MILLI_MOLE_PER_HR = "MDC_DIM_MILLI_MOLE_PER_HR"

rosetta.MDC_DIM_MILLI_MOLE_PER_HR = rosetta_MDC_DIM_MILLI_MOLE_PER_HR

rosetta_MDC_DIM_MILLI_MOLE_PER_KG = "MDC_DIM_MILLI_MOLE_PER_KG"

rosetta.MDC_DIM_MILLI_MOLE_PER_KG = rosetta_MDC_DIM_MILLI_MOLE_PER_KG

rosetta_MDC_DIM_MILLI_MOLE_PER_KG_PER_DAY = "MDC_DIM_MILLI_MOLE_PER_KG_PER_DAY"

rosetta.MDC_DIM_MILLI_MOLE_PER_KG_PER_DAY = rosetta_MDC_DIM_MILLI_MOLE_PER_KG_PER_DAY

rosetta_MDC_DIM_MILLI_MOLE_PER_KG_PER_HR = "MDC_DIM_MILLI_MOLE_PER_KG_PER_HR"

rosetta.MDC_DIM_MILLI_MOLE_PER_KG_PER_HR = rosetta_MDC_DIM_MILLI_MOLE_PER_KG_PER_HR

rosetta_MDC_DIM_MILLI_MOLE_PER_KG_PER_MIN = "MDC_DIM_MILLI_MOLE_PER_KG_PER_MIN"

rosetta.MDC_DIM_MILLI_MOLE_PER_KG_PER_MIN = rosetta_MDC_DIM_MILLI_MOLE_PER_KG_PER_MIN

rosetta_MDC_DIM_MILLI_MOLE_PER_L = "MDC_DIM_MILLI_MOLE_PER_L"

rosetta.MDC_DIM_MILLI_MOLE_PER_L = rosetta_MDC_DIM_MILLI_MOLE_PER_L

rosetta_MDC_DIM_MILLI_MOLE_PER_M_SQ = "MDC_DIM_MILLI_MOLE_PER_M_SQ"

rosetta.MDC_DIM_MILLI_MOLE_PER_M_SQ = rosetta_MDC_DIM_MILLI_MOLE_PER_M_SQ

rosetta_MDC_DIM_MILLI_MOLE_PER_M_SQ_PER_DAY = "MDC_DIM_MILLI_MOLE_PER_M_SQ_PER_DAY"

rosetta.MDC_DIM_MILLI_MOLE_PER_M_SQ_PER_DAY = rosetta_MDC_DIM_MILLI_MOLE_PER_M_SQ_PER_DAY

rosetta_MDC_DIM_MILLI_MOLE_PER_M_SQ_PER_HR = "MDC_DIM_MILLI_MOLE_PER_M_SQ_PER_HR"

rosetta.MDC_DIM_MILLI_MOLE_PER_M_SQ_PER_HR = rosetta_MDC_DIM_MILLI_MOLE_PER_M_SQ_PER_HR

rosetta_MDC_DIM_MILLI_MOLE_PER_M_SQ_PER_MIN = "MDC_DIM_MILLI_MOLE_PER_M_SQ_PER_MIN"

rosetta.MDC_DIM_MILLI_MOLE_PER_M_SQ_PER_MIN = rosetta_MDC_DIM_MILLI_MOLE_PER_M_SQ_PER_MIN

rosetta_MDC_DIM_MILLI_MOLE_PER_MIN = "MDC_DIM_MILLI_MOLE_PER_MIN"

rosetta.MDC_DIM_MILLI_MOLE_PER_MIN = rosetta_MDC_DIM_MILLI_MOLE_PER_MIN

rosetta_MDC_DIM_MILLI_MOLE_PER_ML = "MDC_DIM_MILLI_MOLE_PER_ML"

rosetta.MDC_DIM_MILLI_MOLE_PER_ML = rosetta_MDC_DIM_MILLI_MOLE_PER_ML

rosetta_MDC_DIM_MILLI_OHM = "MDC_DIM_MILLI_OHM"

rosetta.MDC_DIM_MILLI_OHM = rosetta_MDC_DIM_MILLI_OHM

rosetta_MDC_DIM_MILLI_SEC = "MDC_DIM_MILLI_SEC"

rosetta.MDC_DIM_MILLI_SEC = rosetta_MDC_DIM_MILLI_SEC

rosetta_MDC_DIM_MILLI_VOLT = "MDC_DIM_MILLI_VOLT"

rosetta.MDC_DIM_MILLI_VOLT = rosetta_MDC_DIM_MILLI_VOLT

rosetta_MDC_DIM_MILLI_WATT = "MDC_DIM_MILLI_WATT"

rosetta.MDC_DIM_MILLI_WATT = rosetta_MDC_DIM_MILLI_WATT

rosetta_MDC_DIM_MIN = "MDC_DIM_MIN"

rosetta.MDC_DIM_MIN = rosetta_MDC_DIM_MIN

rosetta_MDC_DIM_MM_HG_PER_PERCENT = "MDC_DIM_MM_HG_PER_PERCENT"

rosetta.MDC_DIM_MM_HG_PER_PERCENT = rosetta_MDC_DIM_MM_HG_PER_PERCENT

rosetta_MDC_DIM_MM_HG_PER_X_L = "MDC_DIM_MM_HG_PER_X_L"

rosetta.MDC_DIM_MM_HG_PER_X_L = rosetta_MDC_DIM_MM_HG_PER_X_L

rosetta_MDC_DIM_MMHG = "MDC_DIM_MMHG"

rosetta.MDC_DIM_MMHG = rosetta_MDC_DIM_MMHG

rosetta_MDC_DIM_MMHG_MIN_PER_L = "MDC_DIM_MMHG_MIN_PER_L"

rosetta.MDC_DIM_MMHG_MIN_PER_L = rosetta_MDC_DIM_MMHG_MIN_PER_L

rosetta_MDC_DIM_MMHG_SEC_PER_ML = "MDC_DIM_MMHG_SEC_PER_ML"

rosetta.MDC_DIM_MMHG_SEC_PER_ML = rosetta_MDC_DIM_MMHG_SEC_PER_ML

rosetta_MDC_DIM_MON = "MDC_DIM_MON"

rosetta.MDC_DIM_MON = rosetta_MDC_DIM_MON

rosetta_MDC_DIM_NANO_G = "MDC_DIM_NANO_G"

rosetta.MDC_DIM_NANO_G = rosetta_MDC_DIM_NANO_G

rosetta_MDC_DIM_NANO_G_PER_DAY = "MDC_DIM_NANO_G_PER_DAY"

rosetta.MDC_DIM_NANO_G_PER_DAY = rosetta_MDC_DIM_NANO_G_PER_DAY

rosetta_MDC_DIM_NANO_G_PER_HR = "MDC_DIM_NANO_G_PER_HR"

rosetta.MDC_DIM_NANO_G_PER_HR = rosetta_MDC_DIM_NANO_G_PER_HR

rosetta_MDC_DIM_NANO_G_PER_KG = "MDC_DIM_NANO_G_PER_KG"

rosetta.MDC_DIM_NANO_G_PER_KG = rosetta_MDC_DIM_NANO_G_PER_KG

rosetta_MDC_DIM_NANO_G_PER_KG_PER_DAY = "MDC_DIM_NANO_G_PER_KG_PER_DAY"

rosetta.MDC_DIM_NANO_G_PER_KG_PER_DAY = rosetta_MDC_DIM_NANO_G_PER_KG_PER_DAY

rosetta_MDC_DIM_NANO_G_PER_KG_PER_HR = "MDC_DIM_NANO_G_PER_KG_PER_HR"

rosetta.MDC_DIM_NANO_G_PER_KG_PER_HR = rosetta_MDC_DIM_NANO_G_PER_KG_PER_HR

rosetta_MDC_DIM_NANO_G_PER_KG_PER_MIN = "MDC_DIM_NANO_G_PER_KG_PER_MIN"

rosetta.MDC_DIM_NANO_G_PER_KG_PER_MIN = rosetta_MDC_DIM_NANO_G_PER_KG_PER_MIN

rosetta_MDC_DIM_NANO_G_PER_LB_PER_HR = "MDC_DIM_NANO_G_PER_LB_PER_HR"

rosetta.MDC_DIM_NANO_G_PER_LB_PER_HR = rosetta_MDC_DIM_NANO_G_PER_LB_PER_HR

rosetta_MDC_DIM_NANO_G_PER_LB_PER_MIN = "MDC_DIM_NANO_G_PER_LB_PER_MIN"

rosetta.MDC_DIM_NANO_G_PER_LB_PER_MIN = rosetta_MDC_DIM_NANO_G_PER_LB_PER_MIN

rosetta_MDC_DIM_NANO_G_PER_M_SQ = "MDC_DIM_NANO_G_PER_M_SQ"

rosetta.MDC_DIM_NANO_G_PER_M_SQ = rosetta_MDC_DIM_NANO_G_PER_M_SQ

rosetta_MDC_DIM_NANO_G_PER_M_SQ_PER_DAY = "MDC_DIM_NANO_G_PER_M_SQ_PER_DAY"

rosetta.MDC_DIM_NANO_G_PER_M_SQ_PER_DAY = rosetta_MDC_DIM_NANO_G_PER_M_SQ_PER_DAY

rosetta_MDC_DIM_NANO_G_PER_M_SQ_PER_HR = "MDC_DIM_NANO_G_PER_M_SQ_PER_HR"

rosetta.MDC_DIM_NANO_G_PER_M_SQ_PER_HR = rosetta_MDC_DIM_NANO_G_PER_M_SQ_PER_HR

rosetta_MDC_DIM_NANO_G_PER_M_SQ_PER_MIN = "MDC_DIM_NANO_G_PER_M_SQ_PER_MIN"

rosetta.MDC_DIM_NANO_G_PER_M_SQ_PER_MIN = rosetta_MDC_DIM_NANO_G_PER_M_SQ_PER_MIN

rosetta_MDC_DIM_NANO_G_PER_MIN = "MDC_DIM_NANO_G_PER_MIN"

rosetta.MDC_DIM_NANO_G_PER_MIN = rosetta_MDC_DIM_NANO_G_PER_MIN

rosetta_MDC_DIM_NANO_G_PER_ML = "MDC_DIM_NANO_G_PER_ML"

rosetta.MDC_DIM_NANO_G_PER_ML = rosetta_MDC_DIM_NANO_G_PER_ML

rosetta_MDC_DIM_NANO_INTL_UNIT_PER_KG = "MDC_DIM_NANO_INTL_UNIT_PER_KG"

rosetta.MDC_DIM_NANO_INTL_UNIT_PER_KG = rosetta_MDC_DIM_NANO_INTL_UNIT_PER_KG

rosetta_MDC_DIM_NANO_INTL_UNIT_PER_M_SQ = "MDC_DIM_NANO_INTL_UNIT_PER_M_SQ"

rosetta.MDC_DIM_NANO_INTL_UNIT_PER_M_SQ = rosetta_MDC_DIM_NANO_INTL_UNIT_PER_M_SQ

rosetta_MDC_DIM_NANO_SEC = "MDC_DIM_NANO_SEC"

rosetta.MDC_DIM_NANO_SEC = rosetta_MDC_DIM_NANO_SEC

rosetta_MDC_DIM_NANO_VOLT = "MDC_DIM_NANO_VOLT"

rosetta.MDC_DIM_NANO_VOLT = rosetta_MDC_DIM_NANO_VOLT

rosetta_MDC_DIM_NANO_VOLT_SEC = "MDC_DIM_NANO_VOLT_SEC"

rosetta.MDC_DIM_NANO_VOLT_SEC = rosetta_MDC_DIM_NANO_VOLT_SEC

rosetta_MDC_DIM_NANO_WATT = "MDC_DIM_NANO_WATT"

rosetta.MDC_DIM_NANO_WATT = rosetta_MDC_DIM_NANO_WATT

rosetta_MDC_DIM_NOS = "MDC_DIM_NOS"

rosetta.MDC_DIM_NOS = rosetta_MDC_DIM_NOS

rosetta_MDC_DIM_O2_SAT_PERCENT_SEC = "MDC_DIM_O2_SAT_PERCENT_SEC"

rosetta.MDC_DIM_O2_SAT_PERCENT_SEC = rosetta_MDC_DIM_O2_SAT_PERCENT_SEC

rosetta_MDC_DIM_OHM = "MDC_DIM_OHM"

rosetta.MDC_DIM_OHM = rosetta_MDC_DIM_OHM

rosetta_MDC_DIM_OZ = "MDC_DIM_OZ"

rosetta.MDC_DIM_OZ = rosetta_MDC_DIM_OZ

rosetta_MDC_DIM_PA_PER_X_L = "MDC_DIM_PA_PER_X_L"

rosetta.MDC_DIM_PA_PER_X_L = rosetta_MDC_DIM_PA_PER_X_L

rosetta_MDC_DIM_PARTS_PER_10_TO_MINUS_12 = "MDC_DIM_PARTS_PER_10_TO_MINUS_12"

rosetta.MDC_DIM_PARTS_PER_10_TO_MINUS_12 = rosetta_MDC_DIM_PARTS_PER_10_TO_MINUS_12

rosetta_MDC_DIM_PARTS_PER_10_TO_MINUS_15 = "MDC_DIM_PARTS_PER_10_TO_MINUS_15"

rosetta.MDC_DIM_PARTS_PER_10_TO_MINUS_15 = rosetta_MDC_DIM_PARTS_PER_10_TO_MINUS_15

rosetta_MDC_DIM_PARTS_PER_10_TO_MINUS_3 = "MDC_DIM_PARTS_PER_10_TO_MINUS_3"

rosetta.MDC_DIM_PARTS_PER_10_TO_MINUS_3 = rosetta_MDC_DIM_PARTS_PER_10_TO_MINUS_3

rosetta_MDC_DIM_PARTS_PER_10_TO_MINUS_6 = "MDC_DIM_PARTS_PER_10_TO_MINUS_6"

rosetta.MDC_DIM_PARTS_PER_10_TO_MINUS_6 = rosetta_MDC_DIM_PARTS_PER_10_TO_MINUS_6

rosetta_MDC_DIM_PARTS_PER_10_TO_MINUS_9 = "MDC_DIM_PARTS_PER_10_TO_MINUS_9"

rosetta.MDC_DIM_PARTS_PER_10_TO_MINUS_9 = rosetta_MDC_DIM_PARTS_PER_10_TO_MINUS_9

rosetta_MDC_DIM_PCT_PCV = "MDC_DIM_PCT_PCV"

rosetta.MDC_DIM_PCT_PCV = rosetta_MDC_DIM_PCT_PCV

rosetta_MDC_DIM_PER_CUBIC_X_M = "MDC_DIM_PER_CUBIC_X_M"

rosetta.MDC_DIM_PER_CUBIC_X_M = rosetta_MDC_DIM_PER_CUBIC_X_M

rosetta_MDC_DIM_PER_DAY = "MDC_DIM_PER_DAY"

rosetta.MDC_DIM_PER_DAY = rosetta_MDC_DIM_PER_DAY

rosetta_MDC_DIM_PER_HECTO_SEC_SQ = "MDC_DIM_PER_HECTO_SEC_SQ"

rosetta.MDC_DIM_PER_HECTO_SEC_SQ = rosetta_MDC_DIM_PER_HECTO_SEC_SQ

rosetta_MDC_DIM_PER_HR = "MDC_DIM_PER_HR"

rosetta.MDC_DIM_PER_HR = rosetta_MDC_DIM_PER_HR

rosetta_MDC_DIM_PER_KILO_OHM = "MDC_DIM_PER_KILO_OHM"

rosetta.MDC_DIM_PER_KILO_OHM = rosetta_MDC_DIM_PER_KILO_OHM

rosetta_MDC_DIM_PER_KILO_SEC = "MDC_DIM_PER_KILO_SEC"

rosetta.MDC_DIM_PER_KILO_SEC = rosetta_MDC_DIM_PER_KILO_SEC

rosetta_MDC_DIM_PER_MIN = "MDC_DIM_PER_MIN"

rosetta.MDC_DIM_PER_MIN = rosetta_MDC_DIM_PER_MIN

rosetta_MDC_DIM_PER_MO = "MDC_DIM_PER_MO"

rosetta.MDC_DIM_PER_MO = rosetta_MDC_DIM_PER_MO

rosetta_MDC_DIM_PER_SQ_X_M = "MDC_DIM_PER_SQ_X_M"

rosetta.MDC_DIM_PER_SQ_X_M = rosetta_MDC_DIM_PER_SQ_X_M

rosetta_MDC_DIM_PER_WK = "MDC_DIM_PER_WK"

rosetta.MDC_DIM_PER_WK = rosetta_MDC_DIM_PER_WK

rosetta_MDC_DIM_PER_X_G = "MDC_DIM_PER_X_G"

rosetta.MDC_DIM_PER_X_G = rosetta_MDC_DIM_PER_X_G

rosetta_MDC_DIM_PER_X_L = "MDC_DIM_PER_X_L"

rosetta.MDC_DIM_PER_X_L = rosetta_MDC_DIM_PER_X_L

rosetta_MDC_DIM_PER_X_L_PER_MIN = "MDC_DIM_PER_X_L_PER_MIN"

rosetta.MDC_DIM_PER_X_L_PER_MIN = rosetta_MDC_DIM_PER_X_L_PER_MIN

rosetta_MDC_DIM_PER_X_M = "MDC_DIM_PER_X_M"

rosetta.MDC_DIM_PER_X_M = rosetta_MDC_DIM_PER_X_M

rosetta_MDC_DIM_PER_X_OHM = "MDC_DIM_PER_X_OHM"

rosetta.MDC_DIM_PER_X_OHM = rosetta_MDC_DIM_PER_X_OHM

rosetta_MDC_DIM_PER_X_SEC = "MDC_DIM_PER_X_SEC"

rosetta.MDC_DIM_PER_X_SEC = rosetta_MDC_DIM_PER_X_SEC

rosetta_MDC_DIM_PER_X_SEC_SQ = "MDC_DIM_PER_X_SEC_SQ"

rosetta.MDC_DIM_PER_X_SEC_SQ = rosetta_MDC_DIM_PER_X_SEC_SQ

rosetta_MDC_DIM_PER_YR = "MDC_DIM_PER_YR"

rosetta.MDC_DIM_PER_YR = rosetta_MDC_DIM_PER_YR

rosetta_MDC_DIM_PERCENT = "MDC_DIM_PERCENT"

rosetta.MDC_DIM_PERCENT = rosetta_MDC_DIM_PERCENT

rosetta_MDC_DIM_PH = "MDC_DIM_PH"

rosetta.MDC_DIM_PH = rosetta_MDC_DIM_PH

rosetta_MDC_DIM_PSI = "MDC_DIM_PSI"

rosetta.MDC_DIM_PSI = rosetta_MDC_DIM_PSI

rosetta_MDC_DIM_PULS_PER_MIN = "MDC_DIM_PULS_PER_MIN"

rosetta.MDC_DIM_PULS_PER_MIN = rosetta_MDC_DIM_PULS_PER_MIN

rosetta_MDC_DIM_RBC = "MDC_DIM_RBC"

rosetta.MDC_DIM_RBC = rosetta_MDC_DIM_RBC

rosetta_MDC_DIM_RESP_PER_MIN = "MDC_DIM_RESP_PER_MIN"

rosetta.MDC_DIM_RESP_PER_MIN = rosetta_MDC_DIM_RESP_PER_MIN

rosetta_MDC_DIM_SEC = "MDC_DIM_SEC"

rosetta.MDC_DIM_SEC = rosetta_MDC_DIM_SEC

rosetta_MDC_DIM_SIGH = "MDC_DIM_SIGH"

rosetta.MDC_DIM_SIGH = rosetta_MDC_DIM_SIGH

rosetta_MDC_DIM_SQ_X_CM = "MDC_DIM_SQ_X_CM"

rosetta.MDC_DIM_SQ_X_CM = rosetta_MDC_DIM_SQ_X_CM

rosetta_MDC_DIM_SQ_X_INCH = "MDC_DIM_SQ_X_INCH"

rosetta.MDC_DIM_SQ_X_INCH = rosetta_MDC_DIM_SQ_X_INCH

rosetta_MDC_DIM_SQ_X_M = "MDC_DIM_SQ_X_M"

rosetta.MDC_DIM_SQ_X_M = rosetta_MDC_DIM_SQ_X_M

rosetta_MDC_DIM_SQ_X_M_PER_SEC = "MDC_DIM_SQ_X_M_PER_SEC"

rosetta.MDC_DIM_SQ_X_M_PER_SEC = rosetta_MDC_DIM_SQ_X_M_PER_SEC

rosetta_MDC_DIM_SQUARE_BREATHS_PER_MIN_PER_L = "MDC_DIM_SQUARE_BREATHS_PER_MIN_PER_L"

rosetta.MDC_DIM_SQUARE_BREATHS_PER_MIN_PER_L = rosetta_MDC_DIM_SQUARE_BREATHS_PER_MIN_PER_L

rosetta_MDC_DIM_TOD = "MDC_DIM_TOD"

rosetta.MDC_DIM_TOD = rosetta_MDC_DIM_TOD

rosetta_MDC_DIM_VOL_PERCENT = "MDC_DIM_VOL_PERCENT"

rosetta.MDC_DIM_VOL_PERCENT = rosetta_MDC_DIM_VOL_PERCENT

rosetta_MDC_DIM_WEEKS = "MDC_DIM_WEEKS"

rosetta.MDC_DIM_WEEKS = rosetta_MDC_DIM_WEEKS

rosetta_MDC_DIM_X_AMP_HR = "MDC_DIM_X_AMP_HR"

rosetta.MDC_DIM_X_AMP_HR = rosetta_MDC_DIM_X_AMP_HR

rosetta_MDC_DIM_X_AMPS = "MDC_DIM_X_AMPS"

rosetta.MDC_DIM_X_AMPS = rosetta_MDC_DIM_X_AMPS

rosetta_MDC_DIM_X_AMPS_PER_M = "MDC_DIM_X_AMPS_PER_M"

rosetta.MDC_DIM_X_AMPS_PER_M = rosetta_MDC_DIM_X_AMPS_PER_M

rosetta_MDC_DIM_X_BAR = "MDC_DIM_X_BAR"

rosetta.MDC_DIM_X_BAR = rosetta_MDC_DIM_X_BAR

rosetta_MDC_DIM_X_BEL = "MDC_DIM_X_BEL"

rosetta.MDC_DIM_X_BEL = rosetta_MDC_DIM_X_BEL

rosetta_MDC_DIM_X_BEL_MV = "MDC_DIM_X_BEL_MV"

rosetta.MDC_DIM_X_BEL_MV = rosetta_MDC_DIM_X_BEL_MV

rosetta_MDC_DIM_X_CAL = "MDC_DIM_X_CAL"

rosetta.MDC_DIM_X_CAL = rosetta_MDC_DIM_X_CAL

rosetta_MDC_DIM_X_CAL_PER_DAY = "MDC_DIM_X_CAL_PER_DAY"

rosetta.MDC_DIM_X_CAL_PER_DAY = rosetta_MDC_DIM_X_CAL_PER_DAY

rosetta_MDC_DIM_X_CANDELA = "MDC_DIM_X_CANDELA"

rosetta.MDC_DIM_X_CANDELA = rosetta_MDC_DIM_X_CANDELA

rosetta_MDC_DIM_X_COULOMB = "MDC_DIM_X_COULOMB"

rosetta.MDC_DIM_X_COULOMB = rosetta_MDC_DIM_X_COULOMB

rosetta_MDC_DIM_X_DROPS_PER_MIN = "MDC_DIM_X_DROPS_PER_MIN"

rosetta.MDC_DIM_X_DROPS_PER_MIN = rosetta_MDC_DIM_X_DROPS_PER_MIN

rosetta_MDC_DIM_X_DYNE = "MDC_DIM_X_DYNE"

rosetta.MDC_DIM_X_DYNE = rosetta_MDC_DIM_X_DYNE

rosetta_MDC_DIM_X_DYNE_SEC_PER_CM5 = "MDC_DIM_X_DYNE_SEC_PER_CM5"

rosetta.MDC_DIM_X_DYNE_SEC_PER_CM5 = rosetta_MDC_DIM_X_DYNE_SEC_PER_CM5

rosetta_MDC_DIM_X_EQUIV = "MDC_DIM_X_EQUIV"

rosetta.MDC_DIM_X_EQUIV = rosetta_MDC_DIM_X_EQUIV

rosetta_MDC_DIM_X_EQUIV_PER_CM_CUBE = "MDC_DIM_X_EQUIV_PER_CM_CUBE"

rosetta.MDC_DIM_X_EQUIV_PER_CM_CUBE = rosetta_MDC_DIM_X_EQUIV_PER_CM_CUBE

rosetta_MDC_DIM_X_EQUIV_PER_DAY = "MDC_DIM_X_EQUIV_PER_DAY"

rosetta.MDC_DIM_X_EQUIV_PER_DAY = rosetta_MDC_DIM_X_EQUIV_PER_DAY

rosetta_MDC_DIM_X_EQUIV_PER_HR = "MDC_DIM_X_EQUIV_PER_HR"

rosetta.MDC_DIM_X_EQUIV_PER_HR = rosetta_MDC_DIM_X_EQUIV_PER_HR

rosetta_MDC_DIM_X_EQUIV_PER_KG = "MDC_DIM_X_EQUIV_PER_KG"

rosetta.MDC_DIM_X_EQUIV_PER_KG = rosetta_MDC_DIM_X_EQUIV_PER_KG

rosetta_MDC_DIM_X_EQUIV_PER_KG_PER_DAY = "MDC_DIM_X_EQUIV_PER_KG_PER_DAY"

rosetta.MDC_DIM_X_EQUIV_PER_KG_PER_DAY = rosetta_MDC_DIM_X_EQUIV_PER_KG_PER_DAY

rosetta_MDC_DIM_X_EQUIV_PER_KG_PER_HR = "MDC_DIM_X_EQUIV_PER_KG_PER_HR"

rosetta.MDC_DIM_X_EQUIV_PER_KG_PER_HR = rosetta_MDC_DIM_X_EQUIV_PER_KG_PER_HR

rosetta_MDC_DIM_X_EQUIV_PER_KG_PER_MIN = "MDC_DIM_X_EQUIV_PER_KG_PER_MIN"

rosetta.MDC_DIM_X_EQUIV_PER_KG_PER_MIN = rosetta_MDC_DIM_X_EQUIV_PER_KG_PER_MIN

rosetta_MDC_DIM_X_EQUIV_PER_KG_PER_SEC = "MDC_DIM_X_EQUIV_PER_KG_PER_SEC"

rosetta.MDC_DIM_X_EQUIV_PER_KG_PER_SEC = rosetta_MDC_DIM_X_EQUIV_PER_KG_PER_SEC

rosetta_MDC_DIM_X_EQUIV_PER_L = "MDC_DIM_X_EQUIV_PER_L"

rosetta.MDC_DIM_X_EQUIV_PER_L = rosetta_MDC_DIM_X_EQUIV_PER_L

rosetta_MDC_DIM_X_EQUIV_PER_LB_PER_HR = "MDC_DIM_X_EQUIV_PER_LB_PER_HR"

rosetta.MDC_DIM_X_EQUIV_PER_LB_PER_HR = rosetta_MDC_DIM_X_EQUIV_PER_LB_PER_HR

rosetta_MDC_DIM_X_EQUIV_PER_LB_PER_MIN = "MDC_DIM_X_EQUIV_PER_LB_PER_MIN"

rosetta.MDC_DIM_X_EQUIV_PER_LB_PER_MIN = rosetta_MDC_DIM_X_EQUIV_PER_LB_PER_MIN

rosetta_MDC_DIM_X_EQUIV_PER_M_CUBE = "MDC_DIM_X_EQUIV_PER_M_CUBE"

rosetta.MDC_DIM_X_EQUIV_PER_M_CUBE = rosetta_MDC_DIM_X_EQUIV_PER_M_CUBE

rosetta_MDC_DIM_X_EQUIV_PER_M_SQ = "MDC_DIM_X_EQUIV_PER_M_SQ"

rosetta.MDC_DIM_X_EQUIV_PER_M_SQ = rosetta_MDC_DIM_X_EQUIV_PER_M_SQ

rosetta_MDC_DIM_X_EQUIV_PER_M_SQ_PER_DAY = "MDC_DIM_X_EQUIV_PER_M_SQ_PER_DAY"

rosetta.MDC_DIM_X_EQUIV_PER_M_SQ_PER_DAY = rosetta_MDC_DIM_X_EQUIV_PER_M_SQ_PER_DAY

rosetta_MDC_DIM_X_EQUIV_PER_M_SQ_PER_HR = "MDC_DIM_X_EQUIV_PER_M_SQ_PER_HR"

rosetta.MDC_DIM_X_EQUIV_PER_M_SQ_PER_HR = rosetta_MDC_DIM_X_EQUIV_PER_M_SQ_PER_HR

rosetta_MDC_DIM_X_EQUIV_PER_M_SQ_PER_MIN = "MDC_DIM_X_EQUIV_PER_M_SQ_PER_MIN"

rosetta.MDC_DIM_X_EQUIV_PER_M_SQ_PER_MIN = rosetta_MDC_DIM_X_EQUIV_PER_M_SQ_PER_MIN

rosetta_MDC_DIM_X_EQUIV_PER_MIN = "MDC_DIM_X_EQUIV_PER_MIN"

rosetta.MDC_DIM_X_EQUIV_PER_MIN = rosetta_MDC_DIM_X_EQUIV_PER_MIN

rosetta_MDC_DIM_X_EQUIV_PER_ML = "MDC_DIM_X_EQUIV_PER_ML"

rosetta.MDC_DIM_X_EQUIV_PER_ML = rosetta_MDC_DIM_X_EQUIV_PER_ML

rosetta_MDC_DIM_X_EQUIV_PER_SEC = "MDC_DIM_X_EQUIV_PER_SEC"

rosetta.MDC_DIM_X_EQUIV_PER_SEC = rosetta_MDC_DIM_X_EQUIV_PER_SEC

rosetta_MDC_DIM_X_FARAD = "MDC_DIM_X_FARAD"

rosetta.MDC_DIM_X_FARAD = rosetta_MDC_DIM_X_FARAD

rosetta_MDC_DIM_X_FOOT = "MDC_DIM_X_FOOT"

rosetta.MDC_DIM_X_FOOT = rosetta_MDC_DIM_X_FOOT

rosetta_MDC_DIM_X_G = "MDC_DIM_X_G"

rosetta.MDC_DIM_X_G = rosetta_MDC_DIM_X_G

rosetta_MDC_DIM_X_G_FORCE_M = "MDC_DIM_X_G_FORCE_M"

rosetta.MDC_DIM_X_G_FORCE_M = rosetta_MDC_DIM_X_G_FORCE_M

rosetta_MDC_DIM_X_G_FORCE_M_PER_L = "MDC_DIM_X_G_FORCE_M_PER_L"

rosetta.MDC_DIM_X_G_FORCE_M_PER_L = rosetta_MDC_DIM_X_G_FORCE_M_PER_L

rosetta_MDC_DIM_X_G_FORCE_M_PER_M_SQ = "MDC_DIM_X_G_FORCE_M_PER_M_SQ"

rosetta.MDC_DIM_X_G_FORCE_M_PER_M_SQ = rosetta_MDC_DIM_X_G_FORCE_M_PER_M_SQ

rosetta_MDC_DIM_X_G_M = "MDC_DIM_X_G_M"

rosetta.MDC_DIM_X_G_M = rosetta_MDC_DIM_X_G_M

rosetta_MDC_DIM_X_G_M_PER_M_SQ = "MDC_DIM_X_G_M_PER_M_SQ"

rosetta.MDC_DIM_X_G_M_PER_M_SQ = rosetta_MDC_DIM_X_G_M_PER_M_SQ

rosetta_MDC_DIM_X_G_M_PER_SEC = "MDC_DIM_X_G_M_PER_SEC"

rosetta.MDC_DIM_X_G_M_PER_SEC = rosetta_MDC_DIM_X_G_M_PER_SEC

rosetta_MDC_DIM_X_G_M_SQ = "MDC_DIM_X_G_M_SQ"

rosetta.MDC_DIM_X_G_M_SQ = rosetta_MDC_DIM_X_G_M_SQ

rosetta_MDC_DIM_X_G_PER_CL = "MDC_DIM_X_G_PER_CL"

rosetta.MDC_DIM_X_G_PER_CL = rosetta_MDC_DIM_X_G_PER_CL

rosetta_MDC_DIM_X_G_PER_CM_CUBE = "MDC_DIM_X_G_PER_CM_CUBE"

rosetta.MDC_DIM_X_G_PER_CM_CUBE = rosetta_MDC_DIM_X_G_PER_CM_CUBE

rosetta_MDC_DIM_X_G_PER_DAY = "MDC_DIM_X_G_PER_DAY"

rosetta.MDC_DIM_X_G_PER_DAY = rosetta_MDC_DIM_X_G_PER_DAY

rosetta_MDC_DIM_X_G_PER_DL = "MDC_DIM_X_G_PER_DL"

rosetta.MDC_DIM_X_G_PER_DL = rosetta_MDC_DIM_X_G_PER_DL

rosetta_MDC_DIM_X_G_PER_G = "MDC_DIM_X_G_PER_G"

rosetta.MDC_DIM_X_G_PER_G = rosetta_MDC_DIM_X_G_PER_G

rosetta_MDC_DIM_X_G_PER_HR = "MDC_DIM_X_G_PER_HR"

rosetta.MDC_DIM_X_G_PER_HR = rosetta_MDC_DIM_X_G_PER_HR

rosetta_MDC_DIM_X_G_PER_KG = "MDC_DIM_X_G_PER_KG"

rosetta.MDC_DIM_X_G_PER_KG = rosetta_MDC_DIM_X_G_PER_KG

rosetta_MDC_DIM_X_G_PER_KG_PER_DAY = "MDC_DIM_X_G_PER_KG_PER_DAY"

rosetta.MDC_DIM_X_G_PER_KG_PER_DAY = rosetta_MDC_DIM_X_G_PER_KG_PER_DAY

rosetta_MDC_DIM_X_G_PER_KG_PER_HR = "MDC_DIM_X_G_PER_KG_PER_HR"

rosetta.MDC_DIM_X_G_PER_KG_PER_HR = rosetta_MDC_DIM_X_G_PER_KG_PER_HR

rosetta_MDC_DIM_X_G_PER_KG_PER_MIN = "MDC_DIM_X_G_PER_KG_PER_MIN"

rosetta.MDC_DIM_X_G_PER_KG_PER_MIN = rosetta_MDC_DIM_X_G_PER_KG_PER_MIN

rosetta_MDC_DIM_X_G_PER_KG_PER_SEC = "MDC_DIM_X_G_PER_KG_PER_SEC"

rosetta.MDC_DIM_X_G_PER_KG_PER_SEC = rosetta_MDC_DIM_X_G_PER_KG_PER_SEC

rosetta_MDC_DIM_X_G_PER_L = "MDC_DIM_X_G_PER_L"

rosetta.MDC_DIM_X_G_PER_L = rosetta_MDC_DIM_X_G_PER_L

rosetta_MDC_DIM_X_G_PER_L_PER_DAY = "MDC_DIM_X_G_PER_L_PER_DAY"

rosetta.MDC_DIM_X_G_PER_L_PER_DAY = rosetta_MDC_DIM_X_G_PER_L_PER_DAY

rosetta_MDC_DIM_X_G_PER_L_PER_HR = "MDC_DIM_X_G_PER_L_PER_HR"

rosetta.MDC_DIM_X_G_PER_L_PER_HR = rosetta_MDC_DIM_X_G_PER_L_PER_HR

rosetta_MDC_DIM_X_G_PER_L_PER_MIN = "MDC_DIM_X_G_PER_L_PER_MIN"

rosetta.MDC_DIM_X_G_PER_L_PER_MIN = rosetta_MDC_DIM_X_G_PER_L_PER_MIN

rosetta_MDC_DIM_X_G_PER_L_PER_SEC = "MDC_DIM_X_G_PER_L_PER_SEC"

rosetta.MDC_DIM_X_G_PER_L_PER_SEC = rosetta_MDC_DIM_X_G_PER_L_PER_SEC

rosetta_MDC_DIM_X_G_PER_LB_PER_HR = "MDC_DIM_X_G_PER_LB_PER_HR"

rosetta.MDC_DIM_X_G_PER_LB_PER_HR = rosetta_MDC_DIM_X_G_PER_LB_PER_HR

rosetta_MDC_DIM_X_G_PER_LB_PER_MIN = "MDC_DIM_X_G_PER_LB_PER_MIN"

rosetta.MDC_DIM_X_G_PER_LB_PER_MIN = rosetta_MDC_DIM_X_G_PER_LB_PER_MIN

rosetta_MDC_DIM_X_G_PER_M_CUBE = "MDC_DIM_X_G_PER_M_CUBE"

rosetta.MDC_DIM_X_G_PER_M_CUBE = rosetta_MDC_DIM_X_G_PER_M_CUBE

rosetta_MDC_DIM_X_G_PER_M_PER_SEC = "MDC_DIM_X_G_PER_M_PER_SEC"

rosetta.MDC_DIM_X_G_PER_M_PER_SEC = rosetta_MDC_DIM_X_G_PER_M_PER_SEC

rosetta_MDC_DIM_X_G_PER_M_SQ = "MDC_DIM_X_G_PER_M_SQ"

rosetta.MDC_DIM_X_G_PER_M_SQ = rosetta_MDC_DIM_X_G_PER_M_SQ

rosetta_MDC_DIM_X_G_PER_M_SQ_PER_DAY = "MDC_DIM_X_G_PER_M_SQ_PER_DAY"

rosetta.MDC_DIM_X_G_PER_M_SQ_PER_DAY = rosetta_MDC_DIM_X_G_PER_M_SQ_PER_DAY

rosetta_MDC_DIM_X_G_PER_M_SQ_PER_HR = "MDC_DIM_X_G_PER_M_SQ_PER_HR"

rosetta.MDC_DIM_X_G_PER_M_SQ_PER_HR = rosetta_MDC_DIM_X_G_PER_M_SQ_PER_HR

rosetta_MDC_DIM_X_G_PER_M_SQ_PER_MIN = "MDC_DIM_X_G_PER_M_SQ_PER_MIN"

rosetta.MDC_DIM_X_G_PER_M_SQ_PER_MIN = rosetta_MDC_DIM_X_G_PER_M_SQ_PER_MIN

rosetta_MDC_DIM_X_G_PER_MG = "MDC_DIM_X_G_PER_MG"

rosetta.MDC_DIM_X_G_PER_MG = rosetta_MDC_DIM_X_G_PER_MG

rosetta_MDC_DIM_X_G_PER_MIN = "MDC_DIM_X_G_PER_MIN"

rosetta.MDC_DIM_X_G_PER_MIN = rosetta_MDC_DIM_X_G_PER_MIN

rosetta_MDC_DIM_X_G_PER_ML = "MDC_DIM_X_G_PER_ML"

rosetta.MDC_DIM_X_G_PER_ML = rosetta_MDC_DIM_X_G_PER_ML

rosetta_MDC_DIM_X_G_PER_SEC = "MDC_DIM_X_G_PER_SEC"

rosetta.MDC_DIM_X_G_PER_SEC = rosetta_MDC_DIM_X_G_PER_SEC

rosetta_MDC_DIM_X_INCH = "MDC_DIM_X_INCH"

rosetta.MDC_DIM_X_INCH = rosetta_MDC_DIM_X_INCH

rosetta_MDC_DIM_X_INTL_UNIT = "MDC_DIM_X_INTL_UNIT"

rosetta.MDC_DIM_X_INTL_UNIT = rosetta_MDC_DIM_X_INTL_UNIT

rosetta_MDC_DIM_X_INTL_UNIT_PER_CM_CUBE = "MDC_DIM_X_INTL_UNIT_PER_CM_CUBE"

rosetta.MDC_DIM_X_INTL_UNIT_PER_CM_CUBE = rosetta_MDC_DIM_X_INTL_UNIT_PER_CM_CUBE

rosetta_MDC_DIM_X_INTL_UNIT_PER_DAY = "MDC_DIM_X_INTL_UNIT_PER_DAY"

rosetta.MDC_DIM_X_INTL_UNIT_PER_DAY = rosetta_MDC_DIM_X_INTL_UNIT_PER_DAY

rosetta_MDC_DIM_X_INTL_UNIT_PER_HR = "MDC_DIM_X_INTL_UNIT_PER_HR"

rosetta.MDC_DIM_X_INTL_UNIT_PER_HR = rosetta_MDC_DIM_X_INTL_UNIT_PER_HR

rosetta_MDC_DIM_X_INTL_UNIT_PER_KG = "MDC_DIM_X_INTL_UNIT_PER_KG"

rosetta.MDC_DIM_X_INTL_UNIT_PER_KG = rosetta_MDC_DIM_X_INTL_UNIT_PER_KG

rosetta_MDC_DIM_X_INTL_UNIT_PER_KG_PER_DAY = "MDC_DIM_X_INTL_UNIT_PER_KG_PER_DAY"

rosetta.MDC_DIM_X_INTL_UNIT_PER_KG_PER_DAY = rosetta_MDC_DIM_X_INTL_UNIT_PER_KG_PER_DAY

rosetta_MDC_DIM_X_INTL_UNIT_PER_KG_PER_HR = "MDC_DIM_X_INTL_UNIT_PER_KG_PER_HR"

rosetta.MDC_DIM_X_INTL_UNIT_PER_KG_PER_HR = rosetta_MDC_DIM_X_INTL_UNIT_PER_KG_PER_HR

rosetta_MDC_DIM_X_INTL_UNIT_PER_KG_PER_MIN = "MDC_DIM_X_INTL_UNIT_PER_KG_PER_MIN"

rosetta.MDC_DIM_X_INTL_UNIT_PER_KG_PER_MIN = rosetta_MDC_DIM_X_INTL_UNIT_PER_KG_PER_MIN

rosetta_MDC_DIM_X_INTL_UNIT_PER_KG_PER_SEC = "MDC_DIM_X_INTL_UNIT_PER_KG_PER_SEC"

rosetta.MDC_DIM_X_INTL_UNIT_PER_KG_PER_SEC = rosetta_MDC_DIM_X_INTL_UNIT_PER_KG_PER_SEC

rosetta_MDC_DIM_X_INTL_UNIT_PER_L = "MDC_DIM_X_INTL_UNIT_PER_L"

rosetta.MDC_DIM_X_INTL_UNIT_PER_L = rosetta_MDC_DIM_X_INTL_UNIT_PER_L

rosetta_MDC_DIM_X_INTL_UNIT_PER_LB_PER_HR = "MDC_DIM_X_INTL_UNIT_PER_LB_PER_HR"

rosetta.MDC_DIM_X_INTL_UNIT_PER_LB_PER_HR = rosetta_MDC_DIM_X_INTL_UNIT_PER_LB_PER_HR

rosetta_MDC_DIM_X_INTL_UNIT_PER_LB_PER_MIN = "MDC_DIM_X_INTL_UNIT_PER_LB_PER_MIN"

rosetta.MDC_DIM_X_INTL_UNIT_PER_LB_PER_MIN = rosetta_MDC_DIM_X_INTL_UNIT_PER_LB_PER_MIN

rosetta_MDC_DIM_X_INTL_UNIT_PER_M_CUBE = "MDC_DIM_X_INTL_UNIT_PER_M_CUBE"

rosetta.MDC_DIM_X_INTL_UNIT_PER_M_CUBE = rosetta_MDC_DIM_X_INTL_UNIT_PER_M_CUBE

rosetta_MDC_DIM_X_INTL_UNIT_PER_M_SQ = "MDC_DIM_X_INTL_UNIT_PER_M_SQ"

rosetta.MDC_DIM_X_INTL_UNIT_PER_M_SQ = rosetta_MDC_DIM_X_INTL_UNIT_PER_M_SQ

rosetta_MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_DAY = "MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_DAY"

rosetta.MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_DAY = rosetta_MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_DAY

rosetta_MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_HR = "MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_HR"

rosetta.MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_HR = rosetta_MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_HR

rosetta_MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_MIN = "MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_MIN"

rosetta.MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_MIN = rosetta_MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_MIN

rosetta_MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_SEC = "MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_SEC"

rosetta.MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_SEC = rosetta_MDC_DIM_X_INTL_UNIT_PER_M_SQ_PER_SEC

rosetta_MDC_DIM_X_INTL_UNIT_PER_MIN = "MDC_DIM_X_INTL_UNIT_PER_MIN"

rosetta.MDC_DIM_X_INTL_UNIT_PER_MIN = rosetta_MDC_DIM_X_INTL_UNIT_PER_MIN

rosetta_MDC_DIM_X_INTL_UNIT_PER_ML = "MDC_DIM_X_INTL_UNIT_PER_ML"

rosetta.MDC_DIM_X_INTL_UNIT_PER_ML = rosetta_MDC_DIM_X_INTL_UNIT_PER_ML

rosetta_MDC_DIM_X_INTL_UNIT_PER_SEC = "MDC_DIM_X_INTL_UNIT_PER_SEC"

rosetta.MDC_DIM_X_INTL_UNIT_PER_SEC = rosetta_MDC_DIM_X_INTL_UNIT_PER_SEC

rosetta_MDC_DIM_X_JOULES = "MDC_DIM_X_JOULES"

rosetta.MDC_DIM_X_JOULES = rosetta_MDC_DIM_X_JOULES

rosetta_MDC_DIM_X_JOULES_PER_BREATH = "MDC_DIM_X_JOULES_PER_BREATH"

rosetta.MDC_DIM_X_JOULES_PER_BREATH = rosetta_MDC_DIM_X_JOULES_PER_BREATH

rosetta_MDC_DIM_X_JOULES_PER_L = "MDC_DIM_X_JOULES_PER_L"

rosetta.MDC_DIM_X_JOULES_PER_L = rosetta_MDC_DIM_X_JOULES_PER_L

rosetta_MDC_DIM_X_L = "MDC_DIM_X_L"

rosetta.MDC_DIM_X_L = rosetta_MDC_DIM_X_L

rosetta_MDC_DIM_X_L_PER_BEAT = "MDC_DIM_X_L_PER_BEAT"

rosetta.MDC_DIM_X_L_PER_BEAT = rosetta_MDC_DIM_X_L_PER_BEAT

rosetta_MDC_DIM_X_L_PER_BREATH = "MDC_DIM_X_L_PER_BREATH"

rosetta.MDC_DIM_X_L_PER_BREATH = rosetta_MDC_DIM_X_L_PER_BREATH

rosetta_MDC_DIM_X_L_PER_CM_H2O = "MDC_DIM_X_L_PER_CM_H2O"

rosetta.MDC_DIM_X_L_PER_CM_H2O = rosetta_MDC_DIM_X_L_PER_CM_H2O

rosetta_MDC_DIM_X_L_PER_CM_H2O_PER_KG = "MDC_DIM_X_L_PER_CM_H2O_PER_KG"

rosetta.MDC_DIM_X_L_PER_CM_H2O_PER_KG = rosetta_MDC_DIM_X_L_PER_CM_H2O_PER_KG

rosetta_MDC_DIM_X_L_PER_DAY = "MDC_DIM_X_L_PER_DAY"

rosetta.MDC_DIM_X_L_PER_DAY = rosetta_MDC_DIM_X_L_PER_DAY

rosetta_MDC_DIM_X_L_PER_DL = "MDC_DIM_X_L_PER_DL"

rosetta.MDC_DIM_X_L_PER_DL = rosetta_MDC_DIM_X_L_PER_DL

rosetta_MDC_DIM_X_L_PER_HR = "MDC_DIM_X_L_PER_HR"

rosetta.MDC_DIM_X_L_PER_HR = rosetta_MDC_DIM_X_L_PER_HR

rosetta_MDC_DIM_X_L_PER_KG = "MDC_DIM_X_L_PER_KG"

rosetta.MDC_DIM_X_L_PER_KG = rosetta_MDC_DIM_X_L_PER_KG

rosetta_MDC_DIM_X_L_PER_KG_PER_DAY = "MDC_DIM_X_L_PER_KG_PER_DAY"

rosetta.MDC_DIM_X_L_PER_KG_PER_DAY = rosetta_MDC_DIM_X_L_PER_KG_PER_DAY

rosetta_MDC_DIM_X_L_PER_KG_PER_HR = "MDC_DIM_X_L_PER_KG_PER_HR"

rosetta.MDC_DIM_X_L_PER_KG_PER_HR = rosetta_MDC_DIM_X_L_PER_KG_PER_HR

rosetta_MDC_DIM_X_L_PER_L = "MDC_DIM_X_L_PER_L"

rosetta.MDC_DIM_X_L_PER_L = rosetta_MDC_DIM_X_L_PER_L

rosetta_MDC_DIM_X_L_PER_M_SQ = "MDC_DIM_X_L_PER_M_SQ"

rosetta.MDC_DIM_X_L_PER_M_SQ = rosetta_MDC_DIM_X_L_PER_M_SQ

rosetta_MDC_DIM_X_L_PER_M_SQ_PER_DAY = "MDC_DIM_X_L_PER_M_SQ_PER_DAY"

rosetta.MDC_DIM_X_L_PER_M_SQ_PER_DAY = rosetta_MDC_DIM_X_L_PER_M_SQ_PER_DAY

rosetta_MDC_DIM_X_L_PER_M_SQ_PER_HR = "MDC_DIM_X_L_PER_M_SQ_PER_HR"

rosetta.MDC_DIM_X_L_PER_M_SQ_PER_HR = rosetta_MDC_DIM_X_L_PER_M_SQ_PER_HR

rosetta_MDC_DIM_X_L_PER_M_SQ_PER_MIN = "MDC_DIM_X_L_PER_M_SQ_PER_MIN"

rosetta.MDC_DIM_X_L_PER_M_SQ_PER_MIN = rosetta_MDC_DIM_X_L_PER_M_SQ_PER_MIN

rosetta_MDC_DIM_X_L_PER_MIN = "MDC_DIM_X_L_PER_MIN"

rosetta.MDC_DIM_X_L_PER_MIN = rosetta_MDC_DIM_X_L_PER_MIN

rosetta_MDC_DIM_X_L_PER_MIN_PER_KG = "MDC_DIM_X_L_PER_MIN_PER_KG"

rosetta.MDC_DIM_X_L_PER_MIN_PER_KG = rosetta_MDC_DIM_X_L_PER_MIN_PER_KG

rosetta_MDC_DIM_X_L_PER_MIN_PER_M_SQ = "MDC_DIM_X_L_PER_MIN_PER_M_SQ"

rosetta.MDC_DIM_X_L_PER_MIN_PER_M_SQ = rosetta_MDC_DIM_X_L_PER_MIN_PER_M_SQ

rosetta_MDC_DIM_X_L_PER_MIN_PER_ML_HG = "MDC_DIM_X_L_PER_MIN_PER_ML_HG"

rosetta.MDC_DIM_X_L_PER_MIN_PER_ML_HG = rosetta_MDC_DIM_X_L_PER_MIN_PER_ML_HG

rosetta_MDC_DIM_X_L_PER_MM_HG = "MDC_DIM_X_L_PER_MM_HG"

rosetta.MDC_DIM_X_L_PER_MM_HG = rosetta_MDC_DIM_X_L_PER_MM_HG

rosetta_MDC_DIM_X_L_PER_MM_PA = "MDC_DIM_X_L_PER_MM_PA"

rosetta.MDC_DIM_X_L_PER_MM_PA = rosetta_MDC_DIM_X_L_PER_MM_PA

rosetta_MDC_DIM_X_L_PER_SEC = "MDC_DIM_X_L_PER_SEC"

rosetta.MDC_DIM_X_L_PER_SEC = rosetta_MDC_DIM_X_L_PER_SEC

rosetta_MDC_DIM_X_L_SQ_PER_SEC = "MDC_DIM_X_L_SQ_PER_SEC"

rosetta.MDC_DIM_X_L_SQ_PER_SEC = rosetta_MDC_DIM_X_L_SQ_PER_SEC

rosetta_MDC_DIM_X_LB = "MDC_DIM_X_LB"

rosetta.MDC_DIM_X_LB = rosetta_MDC_DIM_X_LB

rosetta_MDC_DIM_X_LUMEN_PER_M_SQ = "MDC_DIM_X_LUMEN_PER_M_SQ"

rosetta.MDC_DIM_X_LUMEN_PER_M_SQ = rosetta_MDC_DIM_X_LUMEN_PER_M_SQ

rosetta_MDC_DIM_X_M = "MDC_DIM_X_M"

rosetta.MDC_DIM_X_M = rosetta_MDC_DIM_X_M

rosetta_MDC_DIM_X_M_PER_MIN = "MDC_DIM_X_M_PER_MIN"

rosetta.MDC_DIM_X_M_PER_MIN = rosetta_MDC_DIM_X_M_PER_MIN

rosetta_MDC_DIM_X_M_PER_PASCAL_SEC = "MDC_DIM_X_M_PER_PASCAL_SEC"

rosetta.MDC_DIM_X_M_PER_PASCAL_SEC = rosetta_MDC_DIM_X_M_PER_PASCAL_SEC

rosetta_MDC_DIM_X_M_PER_SEC = "MDC_DIM_X_M_PER_SEC"

rosetta.MDC_DIM_X_M_PER_SEC = rosetta_MDC_DIM_X_M_PER_SEC

rosetta_MDC_DIM_X_M_PER_VOLT = "MDC_DIM_X_M_PER_VOLT"

rosetta.MDC_DIM_X_M_PER_VOLT = rosetta_MDC_DIM_X_M_PER_VOLT

rosetta_MDC_DIM_X_MOLE = "MDC_DIM_X_MOLE"

rosetta.MDC_DIM_X_MOLE = rosetta_MDC_DIM_X_MOLE

rosetta_MDC_DIM_X_MOLE_PER_CM_CUBE = "MDC_DIM_X_MOLE_PER_CM_CUBE"

rosetta.MDC_DIM_X_MOLE_PER_CM_CUBE = rosetta_MDC_DIM_X_MOLE_PER_CM_CUBE

rosetta_MDC_DIM_X_MOLE_PER_DAY = "MDC_DIM_X_MOLE_PER_DAY"

rosetta.MDC_DIM_X_MOLE_PER_DAY = rosetta_MDC_DIM_X_MOLE_PER_DAY

rosetta_MDC_DIM_X_MOLE_PER_HR = "MDC_DIM_X_MOLE_PER_HR"

rosetta.MDC_DIM_X_MOLE_PER_HR = rosetta_MDC_DIM_X_MOLE_PER_HR

rosetta_MDC_DIM_X_MOLE_PER_KG = "MDC_DIM_X_MOLE_PER_KG"

rosetta.MDC_DIM_X_MOLE_PER_KG = rosetta_MDC_DIM_X_MOLE_PER_KG

rosetta_MDC_DIM_X_MOLE_PER_KG_PER_DAY = "MDC_DIM_X_MOLE_PER_KG_PER_DAY"

rosetta.MDC_DIM_X_MOLE_PER_KG_PER_DAY = rosetta_MDC_DIM_X_MOLE_PER_KG_PER_DAY

rosetta_MDC_DIM_X_MOLE_PER_KG_PER_HR = "MDC_DIM_X_MOLE_PER_KG_PER_HR"

rosetta.MDC_DIM_X_MOLE_PER_KG_PER_HR = rosetta_MDC_DIM_X_MOLE_PER_KG_PER_HR

rosetta_MDC_DIM_X_MOLE_PER_KG_PER_MIN = "MDC_DIM_X_MOLE_PER_KG_PER_MIN"

rosetta.MDC_DIM_X_MOLE_PER_KG_PER_MIN = rosetta_MDC_DIM_X_MOLE_PER_KG_PER_MIN

rosetta_MDC_DIM_X_MOLE_PER_KG_PER_SEC = "MDC_DIM_X_MOLE_PER_KG_PER_SEC"

rosetta.MDC_DIM_X_MOLE_PER_KG_PER_SEC = rosetta_MDC_DIM_X_MOLE_PER_KG_PER_SEC

rosetta_MDC_DIM_X_MOLE_PER_L = "MDC_DIM_X_MOLE_PER_L"

rosetta.MDC_DIM_X_MOLE_PER_L = rosetta_MDC_DIM_X_MOLE_PER_L

rosetta_MDC_DIM_X_MOLE_PER_M_CUBE = "MDC_DIM_X_MOLE_PER_M_CUBE"

rosetta.MDC_DIM_X_MOLE_PER_M_CUBE = rosetta_MDC_DIM_X_MOLE_PER_M_CUBE

rosetta_MDC_DIM_X_MOLE_PER_M_SQ = "MDC_DIM_X_MOLE_PER_M_SQ"

rosetta.MDC_DIM_X_MOLE_PER_M_SQ = rosetta_MDC_DIM_X_MOLE_PER_M_SQ

rosetta_MDC_DIM_X_MOLE_PER_M_SQ_PER_DAY = "MDC_DIM_X_MOLE_PER_M_SQ_PER_DAY"

rosetta.MDC_DIM_X_MOLE_PER_M_SQ_PER_DAY = rosetta_MDC_DIM_X_MOLE_PER_M_SQ_PER_DAY

rosetta_MDC_DIM_X_MOLE_PER_M_SQ_PER_HR = "MDC_DIM_X_MOLE_PER_M_SQ_PER_HR"

rosetta.MDC_DIM_X_MOLE_PER_M_SQ_PER_HR = rosetta_MDC_DIM_X_MOLE_PER_M_SQ_PER_HR

rosetta_MDC_DIM_X_MOLE_PER_M_SQ_PER_MIN = "MDC_DIM_X_MOLE_PER_M_SQ_PER_MIN"

rosetta.MDC_DIM_X_MOLE_PER_M_SQ_PER_MIN = rosetta_MDC_DIM_X_MOLE_PER_M_SQ_PER_MIN

rosetta_MDC_DIM_X_MOLE_PER_M_SQ_PER_SEC = "MDC_DIM_X_MOLE_PER_M_SQ_PER_SEC"

rosetta.MDC_DIM_X_MOLE_PER_M_SQ_PER_SEC = rosetta_MDC_DIM_X_MOLE_PER_M_SQ_PER_SEC

rosetta_MDC_DIM_X_MOLE_PER_MIN = "MDC_DIM_X_MOLE_PER_MIN"

rosetta.MDC_DIM_X_MOLE_PER_MIN = rosetta_MDC_DIM_X_MOLE_PER_MIN

rosetta_MDC_DIM_X_MOLE_PER_ML = "MDC_DIM_X_MOLE_PER_ML"

rosetta.MDC_DIM_X_MOLE_PER_ML = rosetta_MDC_DIM_X_MOLE_PER_ML

rosetta_MDC_DIM_X_MOLE_PER_MOLE = "MDC_DIM_X_MOLE_PER_MOLE"

rosetta.MDC_DIM_X_MOLE_PER_MOLE = rosetta_MDC_DIM_X_MOLE_PER_MOLE

rosetta_MDC_DIM_X_MOLE_PER_SEC = "MDC_DIM_X_MOLE_PER_SEC"

rosetta.MDC_DIM_X_MOLE_PER_SEC = rosetta_MDC_DIM_X_MOLE_PER_SEC

rosetta_MDC_DIM_X_NEWTON = "MDC_DIM_X_NEWTON"

rosetta.MDC_DIM_X_NEWTON = rosetta_MDC_DIM_X_NEWTON

rosetta_MDC_DIM_X_NEWTON_SEC = "MDC_DIM_X_NEWTON_SEC"

rosetta.MDC_DIM_X_NEWTON_SEC = rosetta_MDC_DIM_X_NEWTON_SEC

rosetta_MDC_DIM_X_NUTR_CAL = "MDC_DIM_X_NUTR_CAL"

rosetta.MDC_DIM_X_NUTR_CAL = rosetta_MDC_DIM_X_NUTR_CAL

rosetta_MDC_DIM_X_OHM = "MDC_DIM_X_OHM"

rosetta.MDC_DIM_X_OHM = rosetta_MDC_DIM_X_OHM

rosetta_MDC_DIM_X_OHM_M = "MDC_DIM_X_OHM_M"

rosetta.MDC_DIM_X_OHM_M = rosetta_MDC_DIM_X_OHM_M

rosetta_MDC_DIM_X_OSM = "MDC_DIM_X_OSM"

rosetta.MDC_DIM_X_OSM = rosetta_MDC_DIM_X_OSM

rosetta_MDC_DIM_X_OSM_PER_KG = "MDC_DIM_X_OSM_PER_KG"

rosetta.MDC_DIM_X_OSM_PER_KG = rosetta_MDC_DIM_X_OSM_PER_KG

rosetta_MDC_DIM_X_OSM_PER_L = "MDC_DIM_X_OSM_PER_L"

rosetta.MDC_DIM_X_OSM_PER_L = rosetta_MDC_DIM_X_OSM_PER_L

rosetta_MDC_DIM_X_OZ = "MDC_DIM_X_OZ"

rosetta.MDC_DIM_X_OZ = rosetta_MDC_DIM_X_OZ

rosetta_MDC_DIM_X_PA_PER_PERCENT = "MDC_DIM_X_PA_PER_PERCENT"

rosetta.MDC_DIM_X_PA_PER_PERCENT = rosetta_MDC_DIM_X_PA_PER_PERCENT

rosetta_MDC_DIM_X_PASCAL = "MDC_DIM_X_PASCAL"

rosetta.MDC_DIM_X_PASCAL = rosetta_MDC_DIM_X_PASCAL

rosetta_MDC_DIM_X_PASCAL_SEC_PER_L = "MDC_DIM_X_PASCAL_SEC_PER_L"

rosetta.MDC_DIM_X_PASCAL_SEC_PER_L = rosetta_MDC_DIM_X_PASCAL_SEC_PER_L

rosetta_MDC_DIM_X_PASCAL_SEC_PER_M_CUBE = "MDC_DIM_X_PASCAL_SEC_PER_M_CUBE"

rosetta.MDC_DIM_X_PASCAL_SEC_PER_M_CUBE = rosetta_MDC_DIM_X_PASCAL_SEC_PER_M_CUBE

rosetta_MDC_DIM_X_RAD_PER_SEC = "MDC_DIM_X_RAD_PER_SEC"

rosetta.MDC_DIM_X_RAD_PER_SEC = rosetta_MDC_DIM_X_RAD_PER_SEC

rosetta_MDC_DIM_X_ROTATIONS_PER_MIN = "MDC_DIM_X_ROTATIONS_PER_MIN"

rosetta.MDC_DIM_X_ROTATIONS_PER_MIN = rosetta_MDC_DIM_X_ROTATIONS_PER_MIN

rosetta_MDC_DIM_X_SEC = "MDC_DIM_X_SEC"

rosetta.MDC_DIM_X_SEC = rosetta_MDC_DIM_X_SEC

rosetta_MDC_DIM_X_TESLA = "MDC_DIM_X_TESLA"

rosetta.MDC_DIM_X_TESLA = rosetta_MDC_DIM_X_TESLA

rosetta_MDC_DIM_X_VOLT = "MDC_DIM_X_VOLT"

rosetta.MDC_DIM_X_VOLT = rosetta_MDC_DIM_X_VOLT

rosetta_MDC_DIM_X_VOLT_PER_SEC = "MDC_DIM_X_VOLT_PER_SEC"

rosetta.MDC_DIM_X_VOLT_PER_SEC = rosetta_MDC_DIM_X_VOLT_PER_SEC

rosetta_MDC_DIM_X_VOLT_SEC = "MDC_DIM_X_VOLT_SEC"

rosetta.MDC_DIM_X_VOLT_SEC = rosetta_MDC_DIM_X_VOLT_SEC

rosetta_MDC_DIM_X_WATT = "MDC_DIM_X_WATT"

rosetta.MDC_DIM_X_WATT = rosetta_MDC_DIM_X_WATT

rosetta_MDC_DIM_X_YARD = "MDC_DIM_X_YARD"

rosetta.MDC_DIM_X_YARD = rosetta_MDC_DIM_X_YARD

rosetta_MDC_DIM_YR = "MDC_DIM_YR"

rosetta.MDC_DIM_YR = rosetta_MDC_DIM_YR

rosetta_MDCX_DIM_MILLI_MOLE_PER_M_SQ_PER_SEC = "MDCX_DIM_MILLI_MOLE_PER_M_SQ_PER_SEC"

rosetta.MDCX_DIM_MILLI_MOLE_PER_M_SQ_PER_SEC = rosetta_MDCX_DIM_MILLI_MOLE_PER_M_SQ_PER_SEC

rosetta_MDCX_DIM_X_L_PER_KG_PER_MIN = "MDCX_DIM_X_L_PER_KG_PER_MIN"

rosetta.MDCX_DIM_X_L_PER_KG_PER_MIN = rosetta_MDCX_DIM_X_L_PER_KG_PER_MIN

rosetta_UOM_MDC = "UOM_MDC"

rosetta.UOM_MDC = rosetta_UOM_MDC
